---
title: "Dip/Trip Hardening, Survivorship Round 1"
author: "Kathleen Durkin"
date: "2024-08-02"
categories: ["pacific_oyster"]
format:
  html:
    toc: true
engine: knitr
#bibliography: ../../../references.bib
---

Conducted extreme stress survivorship test (42C for 4hrs) on hardened adult diploid and triploid Pacific oysters, in Resazurin to moniter respiration. See all experiment details in physical lab notebook

Note: After conducting this survivorship test, realized during discussion with Ariana that pooling the oysters of each treatment group in this little liquid volume doesn't maintain independence, effectively bringing sample size of each treatment to 1. Will need to redo with remaining oysters.

## Experiment planning (8/1)

1.  Separate treatment groups into two, maintaining size distribution. For each oyster bag (e.g., bag 045), sorted all oysters into the size classes defined during [sampling](./2024_07_29_diptrip_sampling.qmd), then split each size class into two groups of equal number. Randomly assign one group to survivorship "control" and one to survivorship "treatment"

2.  Measure approximate volume of each newly created oyster group by placing oysters in a graduated cylinder of a known volume of seawater and noting the difference.

    Keeping in line with Colby's Resazurin experiments, I want to maintain a ratio of roughly 1:4 of oyster volume to Resazurin volume.

| source bag | group           | \# oysters | volume (mL) | resazurin volume |
|------------|-----------------|------------|-------------|------------------|
| 045        | control (20C)   | 31         | 200         | 800              |
| 045        | treatment (42C) | 31         | 200         | 800              |
| 060        | control (20C)   | 23         | 150         | 600              |
| 060        | treatment (42C) | 24         | 150         | 600              |
| 064        | control (20C)   | 19         | 250         | 1000             |
| 064        | treatment (42C) | 19         | 250         | 1000             |
| 065        | control (20C)   | 25         | 275         | 1100             |
| 065        | treatment (42C) | 25         | 275         | 1100             |

## Survivorship test (8/2)

1.  Heated 2 15 gallon buckets of seawater to 42C using rod heaters. One used to mix heated Resaurin, one used to "preheat" stress treatment oysters before start of survivorship trial.

2.  Mix 2 batches of Resazurin, one with the heated 42C seawater, one with ambient temp 20C seawater. Want to maintain 1:4 ratio of oyster volume to Resazurin volume, so needed 3.75L 42C Resazurin and 3.75L 20C Resazurin.

    [3.75L Resazurin reagents:]{.underline}

    -   3701.25 mL 42C seawater

    -   37.5 mL A6 antibiotic

    -   7.5 mL stock resazurin

    -   3.75 mL DMSO

3.  Add appropriate volume and temperature of Resazurin to each labelled treatment container (see above table for volumes). Also include extra container of oyster-free Resazurin at both 42C and 20C as control.

4.  Add oysters to respective treatment group containers. Oysters going into the 42C treatment were swirled in the 42C seawater for \~30sec before adding to 42C Resazurin, to minimize temperature change upon addition. Place 42C containers in incubator set to 42C, to maintain temperature throughout test.

5.  Left oysters in treatment for 4 hours, sampling and measuring Resazurin every \~20min.

6.  After survivorship test concluded, rinsed all oyster groups in ambient seawater to remove residual Resazurin and placed in 8 separate, labelled mesh bags. Placed back in 20C seawater tank in FTR 208.

7.  After 1 hr checked all bags for mortality, and continued to check once a day for 1wk.

[Resazurin data](https://docs.google.com/spreadsheets/d/1RJ78y5iGYIPtnm9noCcP6m2AjOoFEiCR2MkG3hwspco/edit?gid=0#gid=0)

[Mortality data](https://docs.google.com/spreadsheets/d/1fu7ywbEO53oRh5pGiFUgTpugNA0cD2InWDVh1ciD-5E/edit?gid=0#gid=0)

## Sampling Resazurin

Pipette 150uL from each container onto a 96 well plate and place in microreader. Run Colby Resazurin program. Emptied, rinsed, and dried plate after 8th round of measurements and continued using.

```{r}
library(ggplot2)

# load data
resazurin_OG <- read.csv("../../../../../Data/Pacific_oysters/2024_08_02_diptrip_resazurin_compiled.csv")

# remove any NA measurement values
resazurin <- resazurin_OG[!is.na(resazurin_OG$Measurement),]

# set specified order of the groups
resazurin$Group <- factor(resazurin$Group, levels = c("045T", "060T", "064T", "065T", "045C", "060C", "064C", "065C", "TNO", "CNO"))

# plot
ggplot(resazurin, aes(x = Time, y = Measurement, color = Group, group = Group)) +
  geom_point() +
  geom_line() +
  labs(title = "Resazurin measurements over time",
       x = "Time",
       y = "Measurement",
       color = "Group") +
  theme_minimal()
```
