---
title: "Sampling hardened diploid and triploid oysters"
author: "Kathleen Durkin"
date: "2024-07-29"
categories: ["pacific_oyster"]
format:
  html:
    toc: true
engine: knitr
#bibliography: ../../../references.bib
---

Sampled each of the four treatment groups of the diploid and triploid thermal hardening experiment. As a reminder, diploid and triploid Pacific oysters were hardened using 6 treatments of 35C for 4 hours over the course of two weeks. This was followed by a 2 week recovery period, transfer to FTR, and several day acclimation period.

Sampled 16 oysters from each bag, four from each size class

| Size class | length range |
|------------|--------------|
| 1          | 0mm - 35mm   |
| 2          | 36mm - 42mm  |
| 3          | 43mm - 49mm  |
| 4          | 50mm -       |

Full sampling details can be found in my physical lab notebook.

Took 5 tissue samples from each oyster:

| tube label prefix | tube color    | test type | reagent           | storage method                                         | tissue type                                          |
|-------------------|---------------|-----------|-------------------|--------------------------------------------------------|------------------------------------------------------|
| E                 | orange/yellow | enzyme    | 500mL SEI buffer  | flash frozen in travel liquid nitrogen, stored at -80C | gill                                                 |
| R                 | red           | RNA       | 500mL RNA Later   | refrigerated for 24hr, then stored at -80C             | gill                                                 |
| D                 | blue          | DNA       | 500mL 70% ethanol | refrigerated for 24hr, then stored at -80C             | gill, but will take mantle if too little gill tissue |
| G                 | green         |           | none              | flash frozen in travel liquid nitrogen, stored at -80C | gill                                                 |
| M                 | purple        |           | none              | flash frozen in travel liquid nitrogen, stored at -80C | mantle                                               |

All tubes stored in -80C freezer in boxes labelled "KD diploid/triploid hardening"

See all sampling notes [here](https://docs.google.com/spreadsheets/d/1WVn_HcfZYoSktAjkbuCGHtzrT3mpy6ngJXK7XZGpVqk/edit?gid=0#gid=0)

Took individual pictures of all oysters with poor body condition or developed gonads, and checked gonad samples under microscope to check egg or sperm and egg development. Generally, the triploid groups had many more oysters with develped gonads than the diploids, and the diploids seemed to be more sickly (more shell deterioration, less usable tissue, etc.). Discarded remaining tissue and shells after sampling.

Also, all groups had a couple additional dead oysters identified while sorting and selecting oysters for sampling.
