---
title: "April 2024, Daily Log"
author: "Kathleen Durkin"
date: "last-modified"
categories: ["daily log"]
format:
  html:
    toc: true
---

## 30 April 2024

#### Tuesday

## 29 April 2024

#### Monday

## 26 April 2024

#### Friday

## 25 April 2024

#### Thursday

-   trying to make some figures for cod DEGs

-   class (fsh541) -- Laura wasour instructor today!

-   lab meeting

-   [tissue subsampling](../../projects/pacific_cod/2024_04_25_methylation_subsampling.qmd) (cod liver tissue, compiling methylation samples)

## 24 April 2024

#### Wednesday

-   class, GNM569 (last class!)

-   continuing cod HISAT run

-   applied for some QSCI TA positions in the fall quarter

## 23 April 2024

#### Tuesday

## 22 April 2024

#### Monday

-   class -- GNM569

-   E5 analyses ... still...

-   finished GNM569 project2

-   classwork for FSH541 tomorrow

## 19 April 2024

#### Friday

-   E5 meeting

-   continued rerunning analyses -- realized I didn't use the curated miRBase+cnidarians database from Jill, so I actually need to re-rerun pretty much everything 😭

-   classwork for GNM569

## 18 April 2024

#### Thursday

-   pubathon

-   class (FSH541)

-   lab meeting, talked about figures

-   continued rerunning E5 sRNA analyses

## 17 April 2024

#### Wednesday

-   class (GNM569)

-   finished mirdeep2 run with merged reads for E5. Tried to get started on the P.meandrina rerun, but I can't access the reads online? Something's up with Owl and I can't access things stored there 😳

-   got references for everything I cited to far in cod manuscript and inserted the in-text citations

-   updated the readme file for the cod repo

-   more working on GO enrichment analysis for the cod rnaseq data. I figured out the annotation/making an ID-GO database step, now I'm trying to do the actual enrichment (nothing about this on the lab website, so trying to look through Matt's code)

-   reading and quiz for FSH541

## 16 April 2024

#### Tuesday

-   classwork (FSH541)

-   updating cod methylation sample list again, per my discussion with Laura yesterday

-   class (FSH541)

-   lab class (FSH541) -- working on getting a HiSat workflow for aligning cod rnaseq reads to genome (note I already have a transcriptome pseduoaliignment and count matrix using kallisto, this is just an exercise)

-   mariners game tonight with the cohort!

## 15 April 2024

#### Monday

-   class (GNM569)

-   rerunning BLAST and miRdeep2 with merged P.eve reads. Having some trouble with miRdeep2, I think the merging introduced reads \<17bp long, which miRdeep2 doesn't like.

-   meeting with laura about cod project. discussed adjusting samples selected for methylation to ensure full representation of genetic diversity.

## 12 April 2024

#### Friday

Out

## 11 April 2024

#### Thursday

-   class (FSH 541)

-   classwork

-   starting on rerunning E5 sRNAseq analyses using merged reads. starting with P.eve.

## 10 April 2024

#### Wednesday

-   GNM569 class

-   last edits for GNM569 project, I'm just pushing what I have and walking the heck away🥴

-   classwork for FSH541

-   methods writing for cod manuscript

## 09 April 2024

#### Tuesday

-   classwork for FSH541

-   FSH541 Lecture

-   FSH541 Lab

-   more working on GNM569 project -- at this point I actually never want to look at a terminal window again, so.... this class may be having the wrong effect on me lol

## 08 April 2024

#### Monday

-   Literally just grinding the GNM569 project all day, at this point I'm seeing lines of bash script in my sleep

## 05 April 2024

#### Friday

-   E5 molecular meeting, committed to continuing the sRNA analyses with new merged reads

-   Grinding the GNM569 project for *6 hours straight* and making almost no progress because the TA is being singularly unhelpful 😭

## 04 April 2024

#### Thursday

-   pubathon

-   meeting w/ Steven about oyster experimental setup (see notes [here](https://docs.google.com/document/d/1IgbZgJOcZYKogHhHB1Apst1ihhXzmYLT-fLHrZf0dtc/edit#heading=h.o21bn5ytygqm))

-   class (FISH541)

-   updating lab notebook for start of April (new posts/goals docs)

## 03 April 2024

#### Wednesday

-   class (GNM569)

-   classwork for GNM569

-   classwork for FSH541 -- readings and quiz

-   meeting with Laura about cod DGE analysis --- notes [here](https://docs.google.com/document/d/1IgbZgJOcZYKogHhHB1Apst1ihhXzmYLT-fLHrZf0dtc/edit#heading=h.fukr5muir45g)

-   making some final edits to cod methylation sample list

-   lab trivia night :)

## 02 April 2024

#### Tuesday

-   FSH541 lecture

-   FSH541 lab

-   some writing on cod manuscript

## 01 April 2024

#### Monday

-   class (GNM569)

-   adding experimental metadata to cod DGE analysis and generating some PCAs with size included

-   classwork for FSH541 (reading, quiz)
