---
title: "February 2024, Daily Log"
author: "Kathleen Durkin"
date: "last-modified"
categories: ["daily log"]
format:
  html:
    toc: true
---

## 29 February 2024

#### Thursday

-   lab meeting, discussed sections "Maple Sugar Moon" and "Witch Hazel" from *Braiding Sweetgras*s

-   Pubathon meeting. Planning to have bioinformatic analysis methods for cod project written up before I leave on Wednesday

-   Classwork. Have project presentation due on Monday (3/4) and project proposal due before I leave on 3/6 for FISH521 (proposal writing class)

-   Department seminar

## 28 February 2024

#### Wednesday

-   Field day: sampling at Point Whitney (post [here](/posts/projects/misc/2024_02_28_oyster_sampling.qmd))

## 27 February 2024

#### Tuesday

-   talked w Steven about oyster project

-   class readings and meeting

-   class (FISH510)

-   last prepping for field work tomorrow: Picked up by Grace L \~6am, picking up dry ice dewer and box of materials from FTR, then driving to arrive \~9am.\
    Clothing: waterproof boots, waterproof pants, warm layers, gloves (Ariana bringing extra)\
    Packing: towel, packed breakfast + lunch, paper notebook, laptop, charger, change of clothes for going to Aaryaa's directly from work.

## 26 February 2024

#### Monday

-   added P.evermanni transcriptome info to E5 deep dive wiki ([here](https://github.com/urol-e5/deep-dive/wiki/Species-Characteristics-and-Genomic-Resources#transcripts-1)) -- see relevant github issue [here](https://github.com/urol-e5/deep-dive/issues/34#issuecomment-1963013790)

<!-- -->

-   Organized materials for oyster trip on Wednesday (see [post](/posts/projects/misc/2024_02_26_oyster_sampling_materials.qmd))
-   proposal writing class
-   outlined [current state](https://docs.google.com/document/d/1ylJC-Ds1QcObWe42tRH4hCke0nAdCrCb1vUPCC6N3X4/edit) of modified oyster project and some questions (meeting w Steven tomorrow to talk about it)

## 23 February 2024

#### Friday

-   E5 all hands meeting. Discussed original E5 proposal and plant stress priming paper (notes [here](https://docs.google.com/document/d/1IgbZgJOcZYKogHhHB1Apst1ihhXzmYLT-fLHrZf0dtc/edit#heading=h.204peiay9yxt))

-   Science Hour -- had some really great discussions w/ various lab members brainstorming different ideas/approaches for oyster work! (notes [here](https://docs.google.com/document/d/1IgbZgJOcZYKogHhHB1Apst1ihhXzmYLT-fLHrZf0dtc/edit#heading=h.u9vfnzhw26w9))

-   did some last deep dive into Quarto documentation

## 22 February 2024

#### Thursday

-   Lab meeting

-   I'm really liking the paper organization template sheet that Chris sent, and I've made a few tweaks -- details [here](/posts/projects/misc/2024_02_22_paper_organization.qmd)!

-   We talked through possible approaches to my oyster project and clarified a viable, interesting end goal. Triploid summer mortality is the big concern, so it would be useful to have some way to "diagnose" stress in the field, informing farms when/how they need to adjust their setups to avoid mass mortality (e.g., adding feed, moving bags to reduce density, shifting to cooler waters, bring into hatchery(?), etc.). Stress "priming" is also a way that hatcheries could preemptively prepare stock for stressful events. Maybe a cool tweak to the project would be to start with diploid/triploid larvae, prime some (but not others), raise to adulthood, and outplant to see how they do in the field. Throughout, measure some set of physiological features (e.g., respiration) to quantify stress and try to **develop some assay of biomarkers indicative of stress/impending mortality.** Could still do temp and nutrition stress

-   I also really like the idea that Sarah suggested about making notebook posts for specific topics when I do a deep dive into the literature on a specific thing, plus her notebook has some really cool features, so I think I'm going to try to implement some of those!

## 21 February 2024

#### Wednesday

## 20 February 2024

#### Tuesday

-   1/2 day

-   E5 gene expression meeting w/ Zach

-   trying out the [paper organization spreadsheet](https://docs.google.com/spreadsheets/d/1y2bPvPm6MpkF2q6CGqsYnvArUU61ZP2w4jUlDJBdrQg/edit?usp=sharing) that Chris sent me

-   finally cleaned office/reorganized and stored all the stuff left in it by past occupants. Still no way to open and clean out the filing cabinet...

## 19 February 2024

#### Monday

-   Presidents' Day

-   classwork -- first time practicing reviewing a manuscript, reading papers for seminar

## 16 February 2024

#### Friday

-   I'm realizing that, as much as I'm liking Zotero as a reference manager, I feel like I'm still not being as organized as I could be while reading/synthesizing papers. I want to figure out an efficient system for keeping track of papers I've read, their degree of relevance, what projects they're related to, biggest takeaways, etc., and I want to establish that system now, before I dig myself even deeper into a hole of poorly-tracked lit review... It's tough to figure out what system would work best though since I don't yet know exactly what kind of information is important to be pulling for phd work/ projects in general...

-   Started brainstorming/outlining/compiling info for oyster project ([google doc](https://docs.google.com/document/d/1ylJC-Ds1QcObWe42tRH4hCke0nAdCrCb1vUPCC6N3X4/edit))

-   classwork

## 15 February 2024

#### Thursday

-   reading -- I think I have a direction I want to go for the oyster project! Also looks like there's a gap in the literature

-   ran idea by Ariana and she had some super helpful feedback about what variables need to be considered

## 14 February 2024

#### Wednesday

-   reading more oyster papers

    -   triploidy inhibits gametogenisis -- does it also affect oysters' hermaphrodism? I.e. are triploid oysters less able to switch between male/female? If gamete production is inhibited, can you even tell?

## 13 February 2024

#### Tuesday

-   Class -- really interesting discussion of this set of critique/comment/letter to the editor papers basically arguing about the Gill-Oxygen Limitation Theory

-   Started high-level lit review of oysters to try to figure out what question(s) I want to ask for an oyster experiment. Brianik & Allem 2023 review suggests empirical studies on oyster triploidy could be a really relevant area

## 12 February 2024

#### Monday

-   Classwork and classes

## 09 February 2024

#### Friday

-   E5 meetings

-   trying to figure out what exactly the --ad-all-nodes option does in MirMachine, the documentation is p vague

-   readings/synthesis post for fish510 on monday (**5** papers this week🥴)

## 08 February 2024

#### Thursday

-   note to self: go back and add references in my notebook posts

-   looking into how to apply WGCNA to mulitomics datasets, since documentation seems to be focusd more on applying to single-omics with multiple treatments? Found som relevant papers, though I'm still a little confused by methods...

-   \^ also found different toolkit called [mixOmics](https://mixomicsteam.github.io/mixOmics-Vignette/id_01.html), specifically intended for multi-omics analysis, but all of the visualization aptions look p different from WGCNA standard visualizations and I'm not that familiar with some of the terminology, so it isn't clear to me upon first read through how it compares to WGCNA approach...

## 07 February 2024

#### Wednesday

-   read/watched some stuff on using WGCNA (for E5 RNAseq and sRNAseq data)

-   Thought I was done w P. evermanni, but Sam pointed out that gff and bed files handle genomic coordinates differently and that, even though bedtools getfasta lists gffs as acceptable input formats, probably still treats them the same as bed files, so all of my transcriptome fastas could be off by 1-2 sequences. Probably doesn't affect end result of kallisto much, since it's pseudoaligning full reads, but still need to fix it. Should be a straightforward fix, the biggest pain will be waiting another 4 hours for the adjusted transcriptome generation code to run again😭

-   Did a quick and dirty [test](/posts/projects/misc/2024_02_08_bedtools_gffvbed.qmd) using both a gff and a bed file as input to bedtools getfasta and both resulted in the same output, suggesting bedtools does appropriately differentiate between the formats! I'll still convert to bed before generating the P.evermanni transcriptome though, just in case

## 06 February 2024

#### Tuesday

-   Wrote some checks for the P.evermanni transcriptome generation script, and I'm pretty confident now that it's running correctly. I did a final rerun of the generation and wrote a [notebook post](/posts/projects/E5_coral/2024_02_06_RNAseq_kallisto.qmd) for the kallisto process for all three deep dive species. Will need to update it tomorrow once I have the final P.evermanni transcriptome and can run it through kallisto as well.

-   510 class

## 05 February 2024

#### Monday

-   Didn't allocate any time last week for the two class assignments I have due today, so cranking those out (proposal introduction for cod project, read and write up discussion for seminar papers)
-   Proposal writing class
-   Checked output for my P.evermanni genome fasta script, then generalized the script (i.e. changed input/output file assignments to use the bash variables I set at the beginning of the document) and reran. It ran much quicker this time around and resulted in a much smaller output file, which means one of the two times I ran the script something was wrong. I did some brief poking around in the two outputs and it looks like maybe the original run was accidentally done using the full gff file, instead of the CDS-only gff? I don't have time to resolve it tonight, but I'll check again tomorrow and run the code and output by someone (Zach, Steven)

## 02 February 2024

#### Friday

-   E5 molecular group meeting

-   Wrote a script to appropriately extract, group, and concatenate CDS fastas to build a genome fasta file for *P.evermanni* kallisto transcript abundance quantification (see details and some pseudocode [here](/posts/projects/E5_coral/2024_01_31_Peve_kallisto.qmd)). Script is pretty slow so I'll have to wait till Monday to get and check output file.

## 01 February 2024

#### Thursday

-   Lab meeting -- Ariana led a really great discussion about project planning and shared a *super* helpful sample [document](https://docs.google.com/spreadsheets/d/11Xw5QXnjyyJYEDEpGr4dzZ3VDq9JwmtPsxUFJBsVlW8/edit#gid=0) of how that might play out for a project, including timelines

-   Reviewed January goals, set February goals, and set up this month's daily log

-   added some pseudocode to the [Peve kallisto troubleshooting post](/posts/projects/E5_coral/2024_01_31_Peve_kallisto.qmd) and began implementing
