---
title: "January 2024, Daily Log"
author: "Kathleen Durkin"
date: "last-modified"
categories: ["daily log"]
format:
  html:
    toc: true
---

## 31 January 2024

#### Wednesday

## 29 January 2024

#### Monday

## 26 January 2024

#### Friday

## 25 January 2024

#### Thursday

## 24 January 2024

#### Wednesday

## 23 January 2024

#### Tuesday

## 22 January 2024

#### Monday

## 19 January 2024

#### Friday

## 18 January 2024

#### Thursday

## 17 January 2024

#### Wednesday

## 16 January 2024

#### Tuesday

Continued compiling/modifying/writing code for a general RNAseq analysis pipeline for use in the cod and/or E5 projects. Will be meeting w/ Zach tomorrow to talk about E5 molecular stuff (writing and gene expression analysis)

Class

## 15 January 2024

#### Monday

Classwork + papers

## 12 January 2024

#### Friday

E5 Molecular group meeting (notes [here](https://docs.google.com/document/d/1IgbZgJOcZYKogHhHB1Apst1ihhXzmYLT-fLHrZf0dtc/edit?usp=sharing))

Classwork

## 11 January 2024

#### Thursday

eScience Institute Data Carpentry workshop, Day 4

## 10 January 2024

#### Wednesday

eScience Institute Data Carpentry workshop, Day 3

Finished [review of TTS tools](../../projects/misc/2024_01_02_TTS.qmd) -- I think I'm going to go with Speechify

## 09 January 2024

#### Tuesday

eScience Institute Data Carpentry workshop, Day 2

Classes, finished transcribing [SICB notes](../../projects/misc/2024_01_02_SICB.qmd)

## 08 January 2024

#### Monday

eScience Institute Data Carpentry workshop, Day 1

First day of classes for the Winter quarter

## 06 January 2024

#### Saturday

[SICB Day 5](../../projects/misc/2024_01_02_SICB.qmd#sicb-day-5)!

## 05 January 2024

#### Friday

[SICB Day 4](../../projects/misc/2024_01_02_SICB.qmd#sicb-day-4)!

[Cnidarian Social](../../projects/misc/2024_01_02_SICB.qmd#cnidarian-social) after the conference -- super fun!

Talked w Steven about next steps of coral stuff -- move towards combining sRNA and RNAseq stuff to examine how the sRNAs are involved in genome expression

## 04 January 2024

#### Thursday

[SICB Day 3](../../projects/misc/2024_01_02_SICB.qmd#sicb-day-3)!

## 03 January 2024

#### Wednesday

[SICB Day 2](../../projects/misc/2024_01_02_SICB.qmd#sicb-day-2)!

## 02 January 2024

#### Tuesday

[SICB Day 1](../../projects/misc/2024_01_02_SICB.qmd#sicb-day-1)!

-   MISS Grant Writing Workshop (notes [here](https://docs.google.com/document/d/1_OzDwwrB3_MgcHZMNjwzF8FmA6CmD3FxBc-V2bGYIhQ/edit))

-   MISS Figures and Illustrations Workshop

## 01 January 2024

#### Monday

-   Did some Lab Notebook work -- set up new section for miscellaneous posts, set some January goals, and set up my January daily post page (which you're currently reading)

-   Went through the (many, many) talks/events at SICB for the first few days and planned out my itinerary

-   Started writing up my review of different TTS services -- find details [here](../../projects/misc/2024_01_02_TTS.qmd)
