---
title: "June 2024, Daily Log"
author: "Kathleen Durkin"
date: "last-modified"
categories: ["daily log"]
format:
  html:
    toc: true
---

## **28 June 2024**

#### **Friday**

## **27 June 2024**

#### **Thursday**

## **26 June 2024**

#### **Wednesday**

-   data entry for oyster lengths

-   Point Whitney notebook post

-   troubleshooting problems pushing github changes

## **25 June 2024**

#### **Tuesday**

-   Field day at Point Whitney (details in [notebook post](../../projects/pacific_oyster/2024_06_25_Point_Whitney.qmd))

## **24 June 2024**

#### **Monday**

-   Reading Ariana's Sea Grant biomarker proposal

-   submit treq for additional disk space on laptop

-   meeting w steven

-   some review of C.gigas thermal tolerances

## **21 June 2024**

#### **Friday**

-   Checked on Madeline's stress test oysters \@ 42C in FTR 228 (at Steven's request). Visually inspected larger oysters, removed smaller oyster plate for \~1min and manually checked each. No gaping in any, suggesting no mortality?

-   Lit review (see ongoing [notebook post](../../projects/pacific_oyster/2024_06_20_experimental_design_questions.qmd))

-   Meeting w Ariana about oyster planning

## **20 June 2024**

#### **Thursday**

Lit review (see ongoing [notebook post](../../projects/pacific_oyster/2024_06_20_experimental_design_questions.qmd))

## **19 June 2024**

#### **Wednesday**

Lit review (see ongoing [notebook post](../../projects/pacific_oyster/2024_06_20_experimental_design_questions.qmd))

## **18 June 2024**

#### **Tuesday**

-   admin stuff -- TA offer for Autumn 2024, updating class schedule, scheduling weekly summer appointments with Steven

-   Started compiling a [list of conferences](https://docs.google.com/spreadsheets/d/1LkoYG6R6xtgpPXokx35ksv-1-tsIIpnhKydhZVVCKOE/edit#gid=0) to keep track of dates/locations of ones I might want to present at or attend. And they're all during the summer, which means I have to wait a whole year to present at my first real conference...?😭

-   meeting with Ariana to talk about oyster stuff

-   completed driver safety training and UCAR registration

-   Looking into NSF GRFP rules, esp on aquaculture

## **17 June 2024**

#### **Monday**

-   Completed GSAR form for end of year (EOY) meeting with Steven

-   Reading through a bunch of Ariana's lab notebook posts to try to finalize what I can contribute to with the oysters

-   EOY meeting with Steven

-   generate basic outline of oyster project

## **14 June 2024**

#### **Friday**

-   E5 meeting

-   reading some *more* papers on ShortStack, miRNA biogenisis/structure and siRNAs following E5 meeting discussion

-   Some more looking through ShortStack outputs and added a bit to the manuscript

-   Reading some papers on the mechanisms of triploid mortality and associated physiological indicators to think about which biomarkers might be the best place to start. Learned that triploid mortality has been associated with triploid fecundity/gametogenisis, which is whack since I thought they were largely sterile

## **13 June 2024**

#### **Thursday**

## **12 June 2024**

#### **Wednesday**

-   Continue rerunning Pacific cod analyses

-   writing in the E5 manuscript, discussion section

-   did some prep for Chris's [Yellow Island Graduate Student Panel](https://docs.google.com/document/d/11JxeS9e5-MzAGy_EKtnJsAcvAaS5sQTMdS1ov9DlpP0/edit)

## **11 June 2024**

#### **Tuesday**

-   still rerunning Pacific cod analyses

-   Running into some issues while converting SAM files to sorted BAM. Occasionally quits and I have to restart it, and I've also started running out of disk space on Raven. Clearing some old files.

-   Added plots of top DEGs and their abundance across all treatments

-   noticed that in a lot of these plots, there's sort of a bimodal distribution in the 16C treatment, with \~5 samples clustering away from the median...

## **10 June 2024**

#### **Monday**

## **07 June 2024**

#### **Friday**

-   continue with Pacific cod analysis rerun

-   some reading on mature v star miRNA for [E5 issue](https://github.com/urol-e5/deep-dive/issues/49) (updated notebook post)

## **06 June 2024**

#### **Thursday**

-   started rerunning full Pacific cod analysis with sample 92 included

    -   troubleshooting trimming code that suddenly wont run -- realized the code on Raven somehow reverted to an older version, so just needed to copy over the correct code from github

-   reading on miRNA biogenisis/transport/function

## **05 June 2024**

#### **Wednesday**

-   talked with Ariana about oyster stuff

-   helped Divya with github/raven problems to finish out FISH541 work

## **04 June 2024**

#### **Tuesday**

-   more looking into that shortstack issue, also found that Pmea shortstack needs to be rerun because it's using the wrong database file (see [github issue](https://github.com/urol-e5/deep-dive/issues/49))

-   Did some reading on miRNA biogenisis and updated Shortstack notebook post from yesterday

-   Set up daily posts and goals for this month

-   Trying to figure out how to incorporate the star miRNA sequences in comparison analysis (if we decide that would be useful because of possible incorrect mature/star ID). It wouldn't work perfectly just subbing in a different list of sequences to current workflow. Star sequences are getting blast hits to the sets of stars associated with already known conserved mature miRNAs, and I'm not exactly sure how I might want to change the filtering to get what I want. After manually investigating it in Google sheets though, it looks like including star sequences wouldn't have a huge impact. Instead of 4 miRNAs conserved in all three species and 1/1/1 for each pair of species, including stars as possible mature miRNA sequences would shift the conserved counts to 5 miRNAs in all three species and 0/1/1 for the Apul-Peve, Apul-Pmea, and Peve-Pmea pairs.

## **03 June 2024**

#### **Monday**

-   Some writing in E5 manuscript

-   doing some manual investigation of the ShortStack outputs and db matches

-   noticed potential problem with ShortStack ids, full post [here](../../projects/E5_coral/2024_06_04_ShortStack_mature_v_star.qmd)
