---
title: "November 2024, Daily Log"
author: "Kathleen Durkin"
date: "last-modified"
categories: ["monthly goals"]
format:
  html
---

## 29 November 2024

#### Friday

## 28 November 2024

#### Thursday

## 27 November 2024

#### Wednesday

## 26 November 2024

#### Tuesday

## 25 November 2024

#### Monday

## 22 November 2024

#### Friday

-   adding methods to E5 expression manuscript

-   E5 meeting -- notes [here](https://docs.google.com/document/d/1Fdd6xC9tJmAf9Iydcf3er-YwabKmwK3jGVw4ppfxfhM/edit?tab=t.0)

-   Leading QSCI482 lab sections

## 21 November 2024

#### Thursday

## 20 November 2024

#### Wednesday

## 19 November 2024

#### Tuesday

## 18 November 2024

#### Monday

-   SWED101 test (makeup since I TA during the friday meetings)

-   SWED101 class

-   Steven weekly meeting

-   heard back from Hollie and scheduled committee meeting!

-   Lab meeting

-   TAing stuff -- answering student emails, putting together some code resources for students who didn't come to lab 7, prepping grading doc for SA6

-   office hours

-   

## 15 November 2024

#### Friday

-   Prepping lab materials

-   QSCI 482 lab sections

-   more trials with RNAhybrid, incorporating RNAcalibrate to generate more accurate distribution parameters

## 14 November 2024

#### Thursday

-   SWED101

-   minyan weekly meeting

-   attending/volunteer working for GSS the rest of the day!

## 13 November 2024

#### Wednesday

-   SWED101 class

-   TA meeting w student

-   finish SA4 grading

-   SWED101 HW

-   

## 12 November 2024

#### Tuesday

-   SWED101 class

-   HS student outreach today (10-12pm)

-   TAing: Grading SA4

-   office hours

-   

## 11 November 2024

#### Monday

Veteran's Day

-   summarizing sRNA expression for sRNA, miRNA, and siRNA in all three E5 species, including normalized counts

-   office hours, TA emails

## 08 November 2024

#### Friday

-   Technically out -- going to my cousin's wedding!

-   lab notebook updates

## 07 November 2024

#### Thursday

-   SWED101

-   weekly meeting w Minyan

-   admin stuff

    -   messaging Hollie about committee

    -   SICB reimbursements

    -   Paperwork for formal SAFS MS committee milestone

    -   course announcements for TAing

-   Short day/work from home, not feeling well

## 06 November 2024

#### Wednesday

-   SWED101

-   Finish Story Assignment 3 grading, publish grades

## 05 November 2024

#### Tuesday

-   SWED101

-   finished midterm grading

-   Office Hours

-   story assignment 3 grading

## 04 November 2024

#### Monday

-   SWED101 class + HW

-   midterm grading. TA emails

-   Lab Meeting

-   Office Hours

-   more midterm grading

-   Joint lab meeting with Tournabene lab

-   SAFS grad student Friendsgiving!

## 01 November 2024

#### Friday

-   prep for E5 meeting

-   help host E5 meeting, see notes/tasks [here](https://docs.google.com/document/d/1Fdd6xC9tJmAf9Iydcf3er-YwabKmwK3jGVw4ppfxfhM/edit?tab=t.0#heading=h.iamzz1xz61aa)

-   TAing lab sections, creating some helper docs for class, some grading
