---
title: "October 2024, Daily Log"
author: "Kathleen Durkin"
date: "last-modified"
categories: ["monthly goals"]
format:
  html
---

## 31 October 2024

#### Thursday

## 30 October 2024

#### Wednesday

## 29 October 2024

#### Tuesday

## 28 October 2024

#### Monday

## 25 October 2024

#### Friday

-   TAing: led both lab sections, (midterm this week).

-   Prepped for Steven meeting, outlined current progress with E5 work and plans/goals for degree progress

-   Met with Steven -- meeting notes/planning [here](./2024_10_25_Degree_ProgressPlan_Meeting.qmd)

-   readings on DNA methylation in corals, role in transposon silencing

## 24 October 2024

#### Thursday

-   SWED101 asynchronus assignment

-   emails catch up

-   TAing: emails, reviewing midterm expectations, preliminary SA3 grading

-   TAing: weekly meeting w Minyan

-   Reviewed Year 1 GSAR and thought through current status/revisions (prep for Steven meeting)

    -   Filled out current coursework on Plan of Study Form

-   Seminar

-   TGIT

-   TAing: reviewed midterm for typos/confusing wording before printing for tomorrow

## 23 October 2024

#### Wednesday

-   SWED101 class

-   start up on coral review work, got in contact with Hilborn's contact

-   Completed ShortStack 4.1.0 reruns and comparison on all three species for E5 deep-dive-expression ([notebook post](../../projects/E5_coral/2024_10_22_shortstack_4.1.0_reruns.qmd))

-   oyster water change

## 22 October 2024

#### Tuesday

## 21 October 2024

#### Monday

## 18 October 2024

#### Friday

## 17 October 2024

#### Thursday

## 16 October 2024

#### Wednesday

Finalized and submitted GRFP application!!!

## 15 October 2024

#### Tuesday

Finalized and submitted SIFP application!!!

## 14 October 2024

#### Monday

## 11 October 2024

#### Friday

## 10 October 2024

#### Thursday

## 09 October 2024

#### Wednesday

## 08 October 2024

#### Tuesday

## 07 October 2024

#### Monday

## 04 October 2024

#### Friday

## 03 October 2024

#### Thursday

## 02 October 2024

#### Wednesday

## 01 October 2024

#### Tuesday
