---
title: "September 2024, Daily Log"
author: "Kathleen Durkin"
date: "last-modified"
categories: ["monthly goals"]
format:
  html
---

## 30 September 2024

#### Monday

-   class

-   GRPF second drafts

-   SWED101 HW

-   office hours

## 27 September 2024

#### Friday

-   TAing 2 lab sections

-   working on second drafts of GRFP docs

## 26 September 2024

#### Thursday

-   class

-   sitting in on the class I'm TAing

-   SIFP reference requests

## 25 September 2024

#### Wednesday

First day of classes!

-   class

-   more lit review for SIFP, focusing on nanopore sequencing

## 24 September 2024

#### Tuesday

-   Finished first draft of GRFP Personal Statement and got feedback from Workshop mentor

-   Panelist at HMC grad student panel for bio colloquium

-   Reviewed TA position materials and met with instructor to review expectations

-   Had to figure out last minute schedule changes bc TA duty overlaps on both the classes I'm registered for

## 23 September 2024

#### Monday

-   Finished first draft of GRFP Research Statement and got feedback from Workshop mentor

-   oyster checks and water change

## 20 September 2024

#### Friday

Vacation!

## 19 September 2024

#### Thursday

Vacation!

## 18 September 2024

#### Wednesday

Vacation!

-   wrote preliminary SIFP abstract and emailed Andrea to set up another meeting about the hDNA methylation proposaluy

## 17 September 2024

#### Tuesday

-   More lit review for SIFP, focusing on alternatives to WGBS for methylation mapping

-   meeting with Steven to discuss GRFP and SIFP

    -   Concerned about not being able to get in touch with Chris and Sarah for GRFP reference, so decided to ask Ariana to act as backup 3rd reference

-   oyster checks and water changes

-   Confirmed Ariana is willing to act as backup GRFP reference! Entered into GRFP portal

-   Compiled supplementary materials for Ariana to use during letter writing.

## 16 September 2024

#### Monday

-   Lit review and compilation to prep for SIFP proposal. See summary so far [here](../../projects/misc/2024_09_16_hDNA_methylation.qmd)

-   Steven confirmed as GRFP reference, added in application portal :)

-   Still haven't heard back from Chris or Sarah, so sent followup email

## 13 September 2024

#### Friday

-   GRFP personal statement

-   preliminary lit review for the SIFP

## 12 September 2024

#### Thursday

-   Prof. McFadden confirmed as GRFP reference, added in application portal :)

-   oyster checks and water change

-   rough first draft of GRFP personal statement

## 11 September 2024

#### Wednesday

-   Prepping some materials (updated CV, research proposal abstract) for GRFP workshop tonight

-   Finalizing reference request supplementary materials

-   Sent out reference requests to Chris, Sarah, Prof. McFadden, and Steven!

-   GRFP workshop, first meeting

## 10 September 2024

#### Tuesday

-   readings on using historical DNA for microbiome characterization or DNA methylation sequencing in corals

-   Talked with Andrea Quattrini on viability of using hDNA for methylation work, and about applying for SIFP with such a project. See my general notes doc for details

-   drafting a bunch of materials to send out with GRFP reference requests

## 09 September 2024

#### Monday

-   oyster checks

## 06 September 2024

#### Friday

-   E5 molecular meeting

-   E5 edits

-   more coral gene expression and sRNA/miRNA expression summary

## 05 September 2024

#### Thursday

-   oyster checks

-   meeting and project planning with Steven

-   more coral gene expression and sRNA/miRNA expression summary

## 04 September 2024

#### Wednesday

-   Peve and Ptuh gene expression summary work

-   E5 manuscript comments, associated reading

## 03 September 2024

#### Tuesday

-   oyster checks, cleaning used glassware from the survivorship that's now empty

-   emailing Sarah Converse again about committee, since Jessica Gephart is no longer available

-   setting September goals and getting back on track with daily logs for this month

-   finishing Apul gene expression summary, first trial of WGCNA

## 02 September 2024

#### Monday

Labor Day
