---
title: "Bead Cleanup of all Samples"
author: "Kathleen Durkin"
date: "2025-07-25"
categories: ["SIFP-2025"]
format:
  html:
    toc: true
execute: 
  eval: TRUE
engine: knitr
bibliography: ../../../references.bib
---

After confirming which bead-to-sample ratio I want to use (0.7X, see the [bead titration](./2025_07_23_KAPA_bead.qmd) and [TapeStation](./2025_07_24_titration_tapestation.qmd) posts for details), I performed bead cleanup and concentration of all samples.

I used KAPA Pure Beads, and followed the protocol and modifications provided in my [KAPA bead titration](./2025_07_23_KAPA_bead.qmd) entry.

This iteration of the KAPA Pure Bead protocol was a little more complicated, though, because many of my DNA extractions have slightly different remaining volumes, due to differences in pipet loss, \# of gels run, dilutions performed, \# of extractions performed for that specimen, and whether samples were included in the titration bead trial. I'm also combining and concentrating the following:

\*Extractions 1 and 2 for for specimens 14366, 19054, 52295, 1180630, 50603\
+Extraction and titrated bead cleanups for specimens 51732, 51892

Bead cleanups require maintaining an accurate bead-to-sample ratio. However, I want to use all extracted DNA I have for each specimen, to maximize the amount of DNA available for sequencing. This means I couldn't just take an equal volume from each sample. Instead, I measured the total extraction volume of each sample as I transferred it to a well in my 0.2mL 8X tube strips. I then calculated, for each sample, what bead volume to use to maintain a bead-to-sample ratio of 0.7X.

| 8X tube strip | Catalog \#  | DNA (uL) | Beads (uL) |
|---------------|-------------|----------|------------|
| A             | 14366 \*    | 90       | 63         |
| A             | 19054 \*    | 100      | 70         |
| A             | 52295 \*    | 100      | 70         |
| A             | 1180630 \*  | 110      | 77         |
| A             | 50603 \*    | 110      | 77         |
| A             | 51732 +     | 100      | 70         |
| A             | 51892 +     | 90       | 63         |
| A             |             |          |            |
| **B**         | **14399**   | **55**   | **38.5**   |
| **B**         | **42137**   | **50**   | **35**     |
| **B**         | **51730**   | **70**   | **49**     |
| **B**         | **51782**   | **45**   | **31.5**   |
| **B**         | **100609**  | **45**   | **31.5**   |
| **B**         | **100610**  | **45**   | **31.5**   |
| **B**         | **1007393** | **45**   | **31.5**   |
| **B**         | **1018355** | **55**   | **38.5**   |
| C             | 1606824     | 50       | 35         |
| C             | 1606826     | 55       | 38.5       |
| C             | 1740336     | 55       | 38.5       |
| C             | 1740363     | 50       | 35         |
| C             | 1740390     | 45       | 31.5       |
| C             | 1740407     | 65       | 45.5       |
| C             | 50368       | 50       | 35         |
| C             | 51727       | 50       | 35         |
| **D**         | **51729**   | **45**   | **31.5**   |
| **D**         | **51857**   | **45**   | **31.5**   |
| **D**         | **51858**   | **45**   | **31.5**   |
| **D**         | **51859**   | **45**   | **31.5**   |
| **D**         | **51860**   | **40**   | **28**     |
| **D**         | **51861**   | **30**   | **21**     |
| **D**         |             |          |            |
| **D**         |             |          |            |

After pipetting all samples into 8X tube strips (in the same order as shown in the volume table above), I filled 4 8X tube strips with the corresponding volumes of KAPA Pure Beads (temp-acclimated and vortexed). This allowed me to quickly add the appropriate volume of beads to all samples using a multi-channel pipet.

Eluted all samples in 30uL of Zymo Elution Buffer.
