---
title: "Native Barcoding Library Prep, Group 1 Library 4"
author: "Kathleen Durkin"
date: "2025-08-18"
categories: ["SIFP-2025"]
format:
  html:
    toc: true
execute: 
  eval: TRUE
engine: knitr
bibliography: ../../../references.bib
---

Now that I'm satisfied with the tweaks to the Native Barcoding gDNA protocol I've made, I will incorporate them all for a library prep of Group 1 (Library 4) that will hopefully be good enough to sequence on MinION.

As a reminder, I'm using [Native Barcoding 96 V14, gDNA protocol](./protocols/ligation-sequencing-gdna-native-barcoding-v14-sqk-nbd114-24-document-checklist-MinION-en-NBE_9169_v114_revV_02Jul2025-39.pdf), with the following modifications:

[**DNA Repair & End-Prep**]{.underline}\
Step 4: aliquot 1000ng DNA per sample (not 400ng)\
Step 6: exclude DCS, making up remaining 1uL with sample DNA or nuclease-free water

[**Native Barcode Ligation**]{.underline}\
Step 7: use 3.75uL end-prepped DNA for each sample, and exclude the nuclease-free water

| Catalog \# | Conc. (ng/uL) | uL for 1000ng | uL for 12uL | Label/Barcode |
|------------|---------------|---------------|-------------|---------------|
| 1606826    | 408           | 2.5           | 9.5         | 12            |
| 1740336    | 368           | 2.7           | 9.3         | 13            |
| 1740363    | 343           | 2.9           | 9.1         | 14            |

**End-Prep Master Mix:**

|                                   | 1X       | 4X         |
|-----------------------------------|----------|------------|
| NEBNext FFPE DNA Repair Buffer    | 0.875 uL | **3.5 uL** |
| Ultra II End-Prep Reaction Buffer | 0.875 uL | **3.5 uL** |
| Ultra II End-Prep Enzyme Mix      | 0.75 uL  | **3 uL**   |
| NEBNext FFPE DNA Repair Mix       | 0.5 uL   | **2 uL**   |

Made a 4X Master Mix and added 3uL to each sample

[Qubit 1 (Barcodes ligated, in 35uL)]{.underline}\
Standard 1: 38.64\
Standard 2: 16901.25\
Library 2: **14.9 ng/uL**

[Qubit 2 (Adapters ligated, in 15uL)]{.underline}\
Standard 1: 39.66\
Standard 2: 10449.45\
Library 2: **36.6 ng/uL**
