---
title: "MinION Run, Group2 Library 2"
author: "Kathleen Durkin"
date: "2025-08-24"
categories: ["SIFP-2025"]
format:
  html:
    toc: true
execute: 
  eval: FALSE
engine: knitr
bibliography: ../../../references.bib
---

Run group 2 Library 2 on a MinION flow cell to sequence.

Following MinION loading protocol found in the Native Barcoding 96 V14 gDNA protocol. Loading flow cell with 200fmol DNA, after seeing higher pore occupancy with this amount (in comparison to 100fmol).

Need 200fmol DNa in 12uL EB. G2L2 is **24.2ng/uL**, so 200fmol of 700bp DNA is **86.24ng**.

$$
\frac{86.24ng}{24.2\frac{ng}{uL}} = 3.56uL G2L2 \ \ \ \rightarrow \ \ \ use\ 3.5uL\ G2L2
$$

So mix **3.5uL G2L2** with **8.5uL EB**.

[**Flow cell:**]{.underline}\
ID: FBD39370\
1482 pores on pore check\
1400 pores after priming and loading

Started run at 10:26pm 8/24/25. Based on MinION G1L4, expect half-life of the pores to be \~12 hrs, so I'll be back in office tomorow morning at around that time. If at 1/2 pore loss by then, will likely wash.

At 20minutes into the run, looking good! Pore activity bars are all stable, with 49.7% sequencing and 13.4% available (so \~80% of available pores are sequencing).

[**Washes:**]{.underline}

Wash #1 at 13hr into run. Re-loaded with 200fmol G2L2. 224 pores -\> 867 pores/

Wash #2 at 23hr in. Reloaded with 200fmol G2L2. 238 pores -\> 563 pores

Wash #3 at 1 day 12 hr into run. Actally had to fully stop run to allow for a mandatory computer update (took \~5min), then restarted "new run", confirmed flow cell was still sequencing, then paused, washed, reloaded, and let run for remaining 36 hours. 212 pores -\> 410 pores. Out of G2L2, so could only load \~100fmol (2uL G2L2 plus 10uL EB).

[**Added 9/30/25:\
**]{.underline}Full run reports:\
[Pre-update](https://gannet.fish.washington.edu/kdurkin1/SIFP_2025/Group2_MinION/Library2/20250824_2226_MD-101223_FBD39370_195b7d5f/report_FBD39370_20250824_2226_195b7d5f.html)\
[Post-update](https://gannet.fish.washington.edu/kdurkin1/SIFP_2025/Group2_MinION/Library2_post_update/20250826_1059_MD-101223_FBD39370_b38d8279/report_FBD39370_20250826_1100_b38d8279.html)

Output stored here:\
[Pre-update](https://gannet.fish.washington.edu/kdurkin1/SIFP_2025/Group2_MinION/Library2/)\
[Post-update](https://gannet.fish.washington.edu/kdurkin1/SIFP_2025/Group2_MinION/Library2_post_update/)
