---
title: "Qiagen Extraction & Zymo Clean of 1800s Re-extractions"
author: "Kathleen Durkin"
date: "2025-09-04"
categories: ["SIFP-2025"]
format:
  html:
    toc: true
execute: 
  eval: FALSE
engine: knitr
bibliography: ../../../references.bib
---

Finished re-extraction of the 5 1800s specimens using the Qiagen DNEasy Kit. Digestions began 09/01/25 7pm, pulled digestions 09/04/25 \~7am. See digestion details [here](./2025_09_01_reextractions.qmd).

Followed Qiagen DNEasy extraction protocol found [here](2025_07_11_extractions.qmd).

Samples: 50368, 50603, 19054, 14399, 42137.

[**Notes:**]{.underline}

-   Eluted in 100uL Qiagen AE

-   50368 has lots of big sclerites.

After Qiagen extraction, immediately cleaned extractions using the Zymo Genomic DNA Clean and Concentrate Kit. Followed protocol included [here](2025_07_12_zymo_cleanup.qmd).

Eluted in 50uL of 60C Zymo EB/

[**Notes:**]{.underline}

-   42137 had an almost black Qiagen extraction, but almost clear after Zymo!

[**Qubit of Zymo-cleaned extractions:**]{.underline}

Used dsDNA 1X HS kit, followed protocol found [here](./2025_07_14_qubit.qmd), using 1uL of sample input.

Standard 1: 35.68\
Standard 2: 16857.03\
50368: **84.0 ng/uL**\
50603: **9.72 ng/uL**\
19054: **1.58 ng/uL**\
14399: **30.8 ng/uL\
**42137: **54.0 ng/uL**

Next step would normally be a gel, but I'm short on time and want to conserve DNA. Since I already know the KAPA bead-to-sample ratio I want to use, I'll go straight to bead clean/size selection.
