---
title: "Pore Check for all Flongle Flow Cells"
author: "Kathleen Durkin"
date: "2025-08-13"
categories: ["SIFP-2025"]
format:
  html:
    toc: true
execute: 
  eval: TRUE
engine: knitr
bibliography: ../../../references.bib
---

To compare the Library 1 and Library 2 prep protocols, and the modified protocol doesn't affect sequencing success, running Group 1 Library 2 on a Flongle flow cell.

Library 2 has an avg fragment length of 1700bp and a concentration of 16.5ng/uL.

Flongle requires 5-10 fmol DNA in 5uL EB. For my fragment size, this corresponds to 10.5ng DNA for 10fmol. Will max out DNA. Library concentration is too high to accurately pipette the equivalent of 10ng. Instead, will make final library of 20fmol (21ng) of DNA in 10uL EB, and only use 5uL for Flongle loading.

21ng of DNA from 16.5ng/uL -\> 21/16.5 -\> **1.27uL Library 2**. Add to (10uL - 1.27uL) = **8.73uL EB**

Followed [Flongle flow cell loading protocol](./protocols/ligation-sequencing-gdna-native-barcoding-v14-sqk-nbd114-96-document-checklist-Flongle-en-NBE_9171_v114_revS_02Jul2025-29.pdf).

[Flongle flow cell specs:]{.underline}\
LOT: 33001524\
SN: B028104122\
ID: **AYW685**\
\# pores on check: **59 pores**\
\# pores after loading: **43 pores**\
