---
title: "Flongle run, Group 1 Library 4"
author: "Kathleen Durkin"
date: "2025-08-18"
categories: ["SIFP-2025"]
format:
  html:
    toc: true
execute: 
  eval: TRUE
engine: knitr
bibliography: ../../../references.bib
---

Running Group 1, Library 4 on a Flongle to confirm successful library prep.

Need 10fmol DNA in 5uL EB. Assume 1700bp average length: 10fmol = 10.5ng DNA.

Library 4 is 36.6ng/uL, so too concentrated to accurately pipette 10.5ng. Instead, make a 4X mix:

$\frac{10.5ng\ DNA}{5uL\ EB} = \frac{42ng\ DNA}{20uL\ EB}$

To get volume of G1L4 to add:

$\frac{42ng\ DNA}{36.6 ng/uL\ G1L4} = 1.15uL\ G1L4$

So added **1.15 uL G1L4** to (20-1.15uL) = **18.85uL EB**. Then used 5uL of this to make Flongle loading library.

[**Flongle flow cell**]{.underline}\
SN: B028104167\
LOT: 33001524\
ID: AYL248\
60 pores on check\
33 pores after loading\
\
This is a pretty significant drop in pores after library loading, even for a Flongle.

Ran for 24 hours.

This Flongle run had very poor results -- low output and quickly degrading pores. After discussion with Dan, though, he thinks this was a problem with the flow cell itself (supported by the dramatic pore loss after loading), not the library. I'll go ahead with the Group 1 Library 4 prep and try it on a MinION.

[**Added 9/30/25:\
**]{.underline}[Full run report](https://gannet.fish.washington.edu/kdurkin1/SIFP_2025/Group1_Flongle/Group1/Library4/20250818_1549_MD-101223_AYL248_54e75371/report_AYL248_20250818_1550_54e75371.html)\
[Output stored here](https://gannet.fish.washington.edu/kdurkin1/SIFP_2025/Group1_Flongle/Group1/Library4/)
