---
title: "SICB 2024"
author: "Kathleen Durkin"
date: "2024-01-04"
categories: ["miscellaneous"]
format:
  html:
    toc: true
---

## SICB Day 1

**MISS Grant Writing Workshop**

-   (notes [here](https://docs.google.com/document/d/1_OzDwwrB3_MgcHZMNjwzF8FmA6CmD3FxBc-V2bGYIhQ/edit))

**MISS Figures and Illustrations Workshop**

## SICB Day 2

**Facultatively sypmbiotic species as models for exploring immune-symbiosis interplay (Lauren Fuess)**

**Tracking heavy metals during bleaching stress and recovery in Hawaiin reef-building corals (Callum Backstrom)**

-   Go Callum!

**Reacclimation to normal temperature failed to restore gamete performance in heatwave-exposed urchins (Jazcenya Gonzalez)**

-   Could apply this to our systems -- heatwave conditions instead of persistent higher temps, and include the reacclimation component

-   Detrimental generational impacts -- sperm speed and motility decreased (along with a couple of other metrics) and, while fertilization was maintained, embryo development was significantly negatively impacted

**It's about time: Unraveling the molecualr clocks of fiddler crab embryos and larvae (Caitlin BrabbleRose)**

-   Fidler crabs have *internal* circadian and/or circitidal clock -- exhibit specific behavior in lab, even when separated from external cues!! Woah!!

-   Possible differential expression of some genes due to circadian and/or circitidal patterns!

**Transcriptomic responses of gecarcinid land crabs to acute and prolonged desiccation stress (Victoria Watson-Zink)**

**Patterns of intergenerational DNA methylation inheritance in Acropora (Christopher Peterson)**

-   allele-specific methylation design

-   methylation heritability varied among the crosses (among two Acropora species and their hybrids)

-   Possibly some methylation is heritable and some isn't -- why?

-   A whole bunch of different mathematical analyses of their methylation data

**Building an 'epigenetic clock': Utelizing DNA methylation patterns to predict age in fish (Emma Strand)**

-   Look into Gloucester marine genomic institute (in Boston)

-   Whole genome bisulfate sequencing

-   Elastic net penalized regression model

-   Prelim data, but looks like there *may* be some methylation sites that can be used to predict age

**Integrating genetics, phenotype, and physiology in a hybrid population of Plethodon (Kyle MOxley)**

**Understanding the impacts of nutrient pollution on an urban coral in a n era of climate change (Caroline Fleming Ianniello)**

-   Wow, coral species Astrangia poculata is a temperate coral species that lives in super urban areas -- they're even found in harbors of NYC!

-   No apparent effect of nitrogen alone on basal metabolic rate

-   However, significant metabolic depression when you combine nitrogen in form of ammonium with temperatures. Also see significant bleaching in combo.

-   Preferentially uptakes ammonium to nitrate

**Comparative analyses of long non-coding RNA activity in three corla species (Zachary Bengtsson)**

-   Go Zach!

-   True sequence siilarity vs. conserved regions?

**Toxin tales: alkaloid load correlates with gene expression differences in poison frogs (Aurora Alvarez-Buylla)**

**Global change in the sensory landscape: Color signal evolution across changing light environments (John David Curlis)**

**Impacts of marine heatwaves on coral environmental memory and cross-generational acclimatization (Danielle Becker)**

-   Remember phenotypic plasticity can be adaptive and maladaptive

-   Rather than use static heat stress, could try more realistically mimicking MHWs by using cyclic temps with higher max (mimic daily temp cycle)

-   Parental exposure to MHW conditions does impact larval survivorship under thermal stress -- environmental memory

-   This is a Putnam lab person! works w Ariana

**Characterizing dark gene functions in corals through microscopy and sRNA-seq approaches (Kevin Wong)**

-   Super cool!

**Symbionts to the rescue: Symbiodiiaceae facilitate coral survival in extreme bay environments (Maya Powell)**

**Fine-scale morphological plasticity in staghorn corals as a function of flow, light, and genotype (Maya Gomez)**

## SICB Day 3

**Immune response of Pycnopodia helianthoides to sea star wasting disease (Grace Crandall)**

-   Go Grace!

```{=html}
<!-- -->
```
-   Can you see DEGs in absence of stress, just related to normal function?

**Identifying genes mediating local adaptation using targeted vs. whole-genome approaches (Nathan Rank)**

**Optimal foraging height of arboreal lizards: the role of visual acuity (Steven Adolph)**

\^ This is one of my professors from undergrad!

**Active tension driven soft coral pulsing: Exploring emergent behavior through elasticity and tension (Matea Santiago)**

-   Exploring polyp movement differences across species?

**A multi-omics approach investigating regulation of symbiont state in a facultatively symbiotic coral (Erin Borbee)**

-   Changes in symbiont density associated with changes in immunity, BUT since tropical corals depend on symbionts, changes in symbiont density are often related to stress/disease -- how to disentangle how symbiont density alone is related to immunity.

-   Use facultative coral (A. paculata) which is not obligate and can healthily host range of symbiont densities, unrelated to stress

-   Used mixed colonies (both brown and white sections in same individual), did transcriptomics, immune assays, microbiome, genotyping (to validate genetically identical samples, not chimeric)

-   NO DEGs or differences in immune assays between brown and white colonies (remember, no treatment here, just comparing different symbiont-load sections of within the same individual)

-   BUT past work using completely brown and completely white individuals of same species DID find significant differences in immune assays!

-   I really like and am interested in conducting this type of multi-omics work!

**Cross-ocean coral transplantation to restore resilience in Caribbean reefs (Mikhail Matz)**

-   That Caribbean coral paper I was looking for: Evolutionary history drives biogeographic patterns of coral reef resilience

-   Super interesting talk, discussing reasons why cross-ocean transplant may be appropriate/necessary for Caribbean reefs. Basically, because of super low recruitment and low diversity in Caribbean reefs, almost every reef in the Caribbean is ecologically extinct (not meeting replacement levels). The a) low native diversity, b) existing high native prevalence of disease, c) 11th hour situation, mean that transplant from the *much* more reproductive Indo-Pacific could be appropriate to preserve existence of reef habitat at all in Caribbean.

-   I really like how this presenter, who is clearly well established in career, didn't use any excessive or complicated jargon in their talk, but were still super engaging and interesting. A nice reprieve after so many pretty formally-spoken talks yesterday

-   What kind of consideration needs to be given to the (few, but present) Caribbean reefs that are still stable and ecologically viable? Introduced super-recruiters would definitely outcompete the natives there

**Leveraging coral disease 'omics datasets for disease classification and predictive modeling (Laura Mydlarz)**

**Identifying shared and host-specific transcriptome charictaristics of the cnidarian-algal mutualism (Madison Emery)**

-   The algal symbiosis mutualism has evolved separately several times in Cnidaria -- woah!

-   Didn't realize there's a jellyfish taxa of cnidarians with obligate symbionts

-   In Cassiopeia (facultative) the symbiotic individual seem to mount more damaging (to the host) immune responses than the aposymbiotic individuals (so individuals with symbionts are *less* likely to survive)

-   Between two species with different symbiont evolutions, more than half of the DEOGs were differentially expressed in *different directions!*

**Tolerance of infection could support resilience at multiple levels (James Adelman)**

**Resilience to high temperature and hypoxia in fish: view from the genome and epigenome (Patricia Schulte)**

**Interplay of acclimatization and adaptation modulates resilience to climate change in marine inverts (Hollie Putnam)**

## SICB Day 4

**Biological springs are most energy efficient when loaded and unloaded at equal rates (Mark Ilton)**

\^ One of my undergad profs!

**Chasing squishy and crunchy invaders: eDNA for dynamic invasive species surveillance in tide pools (Emily Lancaster)**

-   Shells of dead animals (e.g. bivalves) can still shed eDNA, even if the body tissue is gone -- woah!

**Antarctic marine benthic communities: Image transects reveal lower abundances in Eastern than Western (Kenneth Halanych)**

**Striking gold: Successes in rare species detection using eDNA, acoustics, and visual surveys (Corinne Richards-Zawacki)**

**A multiomic approach to understand tradeoffs between symbiosis and immunity in a reef-building coral (Maria Valadez Ingersoll)**

-   Single cell RNAseq and SPLiTseq

**Genome skimming resolves east Pacific Pocillopora species diversity and population differentiation (Michael Connelly)**

**Plasticity in response to temperatures magnitude and fluctuation -- from coloration to thermal tolerance (Austin Hoffman)**

-   Could do something like this, have two treatment axes, one for set of mean temps, one for set of temp variations

**Genetic underpinnings of developmental plasticity and acute thermal responses in a coastal copepod (Alison Hall)**

-   Differences in total detected DEGs can always be influenced bu underlying genetic variation in samples

**Multigenerational plasticity to hypoxia and acidification in Atlantic silversides (Medidia menidia) (Christopher Murray)**

-   transcriptional front loading

**Approaches for minimally invasive long-term ecological montiering (Christine Mantegna)**

-   Go Chris!!!

**Seasonal variation in thermal tolerance and hypoxia tolerance of a threatened minnow and congener (Jessica Reemeyer)**

-   Really interesting general question: it's common to study more common species to infer info about closely-related imperiled species. But how trustworthy is this? How transferrable are conclusions about thermal tolerance (etc.) between closely related species?

-   Are corals and other marine inverts commonly affect by DO levels Is it even relevant (aka is DO variable in marine environments in the same way it is in freshwater)?

-   The very closely related species *didn't* respond in exactly the same way, suggesting we can't always use "surrogate" species -- study your species if possible!

**Rapid change in a rainforest anole: results from the first six years of a translocation experiment (Michael Logan)**

-   Really cool talk an being able to directly track phenotypic change/adaptation of translocated lizards

**Variable warm temperature elevates thermal tolerance but impairs freshwater tolerance in killifish (Michelle Monette)**

### Cnidarian Social

Spoke with Carly Kenkel and another woman whose name I can't remember now 😅, and the other person told us about her recent work with anemones studying the effect of estrogen pollution -- super interesting! So far they haven't seen any direct effect on the anemone host or anemone fertility/reproduction, which we might normally expect based on role of estrogen in vertebrates. There was, however, a significant effect on the symbiont populations -- in presence of estrogen, symbionts were increasingly photosynthetically efficient -- woah! The effect was so strong that they could actually see differences in the color of the water the anemones were held in because of increased levels of algae in the water. Increasing estrogen levels led to this gradient of increasingly green water 😮. Also touched on studying impact of sediment suspension (affects symbiont productivity and/or polyp feeding?)

We also talked a bit about the possibility of coral polyps in the same aggregate colony sharing the "symbiont load," and related nutrients, which could explain when some species have "patchy" symbiont distribution around colony. Apparently there's a kind of plant that grows in/near salty water and, to rid itself of excess salt, basically picks a leaf to die and sends all the salt there, leaving the rest of the plant healthy. Maybe similar stuff happens in corals?

## SICB Day 5

**The importance of life history strategies in the recovery of corals after thermal stress (Jacqueline Padilla-Gamino)**

-   Super interesting idea! Basically, maybe the combination of MHW and differing egg/sperm developmental timelines are causing egg/sperm mismatch when spawning happens!

-   Eggs take a long time to develop and start in late summer, and thus are already in development during MHW/bleaching events. Sperm, however, as "cheap" and don't start developing until March, so never experience bleaching before the spawning season in early summer. That means that, during spawning, you can end up with bleaching-affected eggs trying to match with unstressed sperm -- maybe that "mismatch" is causing problems!

-   Bred bleached (B) and non-bleached (NB) corals. Found that BxB corals and NBxNB corals were most successful in larval development, while BxNB and NBxB corals didn't do as well. Support for this possible mismatch problem

-   While I'm sure this is at least partially because of bleaching-related stress effects of the viability of the eggs or something similar, this is making me think about the possible role of epigenetics here. We know that environmental conditions can be associated with epigenetic modifications like methylation, and that such epigenetic modifications can also take place in the gametes and thus become heritable. Is it possible that there are epigenetic modifications happening in the eggs during these bleaching events that are not happening to the sperm, and that this "mismatch" of the epigenome is less successful that the combination of two stress-modified gametes (BxB) or of two non-modified gametes (NBxNB)?

**Assessing physiological and molecular plasticity in the early stages of Porites astreoides (Florence Fields)**

**Intraspecific variation in thermal tolerance in the endangered Caribbean coral, Acropora palmata (Holland Elder)**

-   Keep in mind bleaching, like other stress reponses, is continuous, not binary!

**The butterfly(fish) effect: Using Caetodontidae territories as bioindicators (Corrine Avidan)**

**Microbial predictors of bleacing in Great Barrier Reef Acropora millepora (Karim Primov)**

**Iron wars over ligand soup: Exploring chemical crosstalk in Symbiodiniaceae-bacteria interactions (Hannah Reich)**

-   Bacteria can help eukaryotic partners (like algae) access hard-to-get iron

-   Possible connection here to Callum's talk about impacts of heavy metal contamination on coral/holobiont?

**Environmental drivers of coral-associated algal and microbial communities across multiple scales (Coleen Bove)**
