---
title: "Getting situated in Raven"
author: "Kathleen Durkin"
date: "2023-10-16"
categories:
    - onboarding
---

Sam was able to resend me login credentials for Raven (the Lab's primary server, implemented through a browser version of RStudio), so I started getting situated on it. Since I have a pending task related to blasting a cod transcriptome, I copied over my github repo RobertsLab_OnboardingTasks and took another look at the blast tutorial .Rmd file (001-blast.Rmd). The last time I tried to run this tutorial file (on RStudio locally) I ran into problems running bash through RStudio at all.

Thankfully that isn't an issue working in Raven, but now I'm kind of stumped because of the need to download and run blast. I can't find any "higher level" directories above my own Raven account that might hold relevant software like ncbi-blast, but it seems weird that I'd need to individually download the software for use on a shared server...The code included in the tutorial file for this also wouldn't work on my machine, since it's written with Mac-specific and outdated versions of blast. I downloaded the most recent Windows version of blast to my local machine, but I don't think I can access local software from Raven since it's a server.
