---
title: "December 2023, Daily Log"
author: "Kathleen Durkin"
date: "2023-12-5"
categories: ["daily log"]
format:
  html:
    toc: true
---

# Daily Log

## 29 December 2023

#### Friday

## 28 December 2023

#### Thursday

## 27 December 2023

#### Wednesday

## 26 December 2023

#### Tuesday

## 25 December 2023

#### Monday

-   Out -- university holiday

## 22 December 2023

#### Friday

## 21 December 2023

#### Thursday

## 20 December 2023

#### Wednesday

## 19 December 2023

#### Tuesday

## 18 December 2023

#### Monday

## 15 December 2023

#### Friday

## 14 December 2023

#### Thursday

## 13 December 2023

#### Wednesday

## 12 December 2023

#### Tuesday

## 11 December 2023

#### Monday

## 08 December 2023

#### Friday

## 07 December 2023

#### Thursday

## 06 December 2023

#### Wednesday

-   Studied and took practice midterm for QSCI 482 (test on Friday) -- got a 95!

-   Read Chpt.2 for DEI -focused lab meeting tomorrow

## 05 December 2023

#### Tuesday

Office setup supplies arrived and I unpackaged and setup my new monitor, laptop stand, keyboard, and mouse! Still need to find some batteries for the wireless keyboard though.

The [*P.meandrina* miRdeep2](https://github.com/urol-e5/deep-dive/blob/main/F-Pmea/code/11-Pmea-sRNAseq-miRdeep2.md) finished running!

A quick comparison of the different miRNA ID approaches for the three species we've been looking at:

+-----------------------------------+----------------------------------------------+-------------------------+-------------------------+------------------------------------+----------------------------------+
|                                   | miRTrace\                                    | MirMachine\             | BLASTn\                 | miRdeep2                           | ShortStack\                      |
|                                   |                                              |                         | (E-val=10)              |                                    |                                  |
+===================================+==============================================+=========================+=========================+====================================+==================================+
| *A. pulchra\                      | lophotrochozoa, rodents, primates,           | Predicted loci: **109** | miRBase: **19,120,159** | Predicted miRNAs: **4,553**        | Potential loci: **18,772**       |
| *(*A.millepora* for genome-based) |                                              |                         |                         |                                    |                                  |
|                                   |                                              | Unique families: **11** | MirGene: **19,037,617** | Matches to known miRNAs: **4,137** | miRBase matches: **46**          |
|                                   |                                              |                         |                         |                                    |                                  |
|                                   |                                              |                         |                         | Novel miRNAs: **416**              | \# characterized as miRNA: **0** |
+-----------------------------------+----------------------------------------------+-------------------------+-------------------------+------------------------------------+----------------------------------+
| *P. evermanni*                    | insects                                      | Predicted loci: **83**  | miRBase: **8,824,359**  | Predicted miRNAs: **5,812**        | Potential loci: **15,040**       |
|                                   |                                              |                         |                         |                                    |                                  |
|                                   |                                              | Unique familes: **15**  | MirGene: **8,783,659**  | Matches to known miRNAS: **5,096** | miRBase matches: **25**          |
|                                   |                                              |                         |                         |                                    |                                  |
|                                   |                                              |                         |                         | Novel miRNAs: **716**              | \# characterized as miRNA: **0** |
+-----------------------------------+----------------------------------------------+-------------------------+-------------------------+------------------------------------+----------------------------------+
| *P. meandrina*                    | nematode, insects, lophotrochozoa, primates  | Predicted loci: **40**  | miRBase: **13,708,946** | Predicted miRNAs: **2,429**        | Potential loci: **7,306**        |
|                                   |                                              |                         |                         |                                    |                                  |
|                                   |                                              | Unique families: **7**  | MirGene: **13,614,786** | Matches to known miRNAs: **2,143** | miRBase matches: **86**          |
|                                   |                                              |                         |                         |                                    |                                  |
|                                   |                                              |                         |                         | Novel miRNAs: **286**              | \# characterized as miRNA: **0** |
+-----------------------------------+----------------------------------------------+-------------------------+-------------------------+------------------------------------+----------------------------------+

## 04 December 2023

#### Monday

Classes. Learned about Celeste's work with tunicates!

## 01 December 2023

#### Friday

-   E5 Molecular working group meeting -- reviewed sRNA progress

-   Science Hour -- talked with Sam about some of my recent questions/confusion spots for miRNA stuff
