---
title: "November 2023, Daily Log"
author: "Kathleen Durkin"
date: "2023-11"
categories: ["daily log"]
format:
  html:
    toc: true
---

# Daily Log

## 30 November 2023

#### Thursday

## 29 November 2023

#### Wednesday

## 28 November 2023

#### Tuesday

## 27 November 2023

#### Monday

## 24 November 2023

#### Friday

-   On Vacation

## 23 November 2023

#### Thursday

-   On Vacation
-   Happy Birthday to me 🎉

## 22 November 2023

#### Wednesday

-   On Vacation

## 21 November 2023

#### Tuesday

-   On Vacation

## 20 November 2023

#### Monday

## 17 November 2023

#### Friday

## 16 November 2023

#### Thursday

## 15 November 2023

#### Wednesday

## 14 November 2023

#### Tuesday

## 13 November 2023

#### Monday

## 10 November 2023

#### Friday

## 09 November 2023

#### Thursday -- Lab Meeting, Debugging Raven-\>Github Issue

-   Lab Meeting! DEI discussion

-   Talked with Steven about Raven-\>Github issue (can't currently push from Raven). Meanwhile, backed up current work to Gannet

-   Classes and assignments

## 08 November 2023

#### Wednesday -- E5 sRNA work (*P. meandrina*) and Website Reformatting

-   Debugging my modification of Sam's sRNA trimming code for application to *P. meandrina.*

-   Reformatting Lab Notebook structure

-   Read Chpt.1 of "Race After Technology" for lab DEI discussion tomorrow

## 07 November 2023

#### Tuesday -- Classes and Homework

Mostly classes, seminar readings, and QSCI assignment today.

## 06 November 2023 

#### Monday -- E5 Molecular Working Group

Met with the E5 molecular working group to review status of long and short ncRNA deep dive. Got started on applying Sam's code for sRNA analysis to *P. meandrina*.

Also presented a version of my GSS talk (UCE target enrichment to improve soft coral species delimitation) for FISH510 assignment and got some helpful feedback! Will make some tweaks and cut down time before my practice talk in Nov. 16 lab meeting.

## 03 November 2023

#### Friday

Set November monthly goals

Met with Steven during Science hour

## 02 November 2023

#### Thursday -- Calculating RNASeq sample size

Calculated necessary sample size for cod RNA sequencing, given an assumed coefficient of variation and detectable difference in expression -- view document [here](https://github.com/RobertsLab/project-cod-temperature/blob/main/code/04-RNASeq-sample-size.md).

Met with the E5 molecular working group for the first time!

## 01 November 2023

#### Wednesday -- SICB Registration, Reviewing October Goals

In the spirit of yesterday's holiday, I completed the scary task of registering for SICB out-of-pocket and then submitting the reimbursement request 🥴. This afternoon I also attended a workshop on making research presentations and slides more communicative and accessible, led by Tim.

With the start of a new month I reviewed my October goals (see that here)

Also, as seen above, I've figured out how to add emojis to my lab notebook -- gamechanger!
