{
  "hash": "d6b947cc3a52e281444c130abb39ec72",
  "result": {
    "markdown": "---\ntitle: \"Deep-Dive Expression: Functional annotation/enrichment of each miRNA's targets\"\nauthor: \"Kathleen Durkin\"\ndate: \"2025-04-09\"\ncategories: [\"E5-coral\"]\nformat:\n  html:\n    toc: true\nexecute: \n  eval: FALSE\nengine: knitr\nbibliography: ../../../references.bib\n---\n\n\nThis code attempts to identify the function of each miRNA by running functional enrichment analysis on each miRNA's set of target genes.\n\n[Code](https://github.com/urol-e5/deep-dive-expression/blob/main/D-Apul/code/09.1-Apul-mRNA-miRNA-interactions-functional-enrichment.Rmd)\\\n[Rendered code](https://github.com/urol-e5/deep-dive-expression/blob/main/D-Apul/code/09.1-Apul-mRNA-miRNA-interactions-functional-enrichment.md?plain=1)\\\n[Output files](https://github.com/urol-e5/deep-dive-expression/tree/main/D-Apul/output/09.1-Apul-mRNA-miRNA-interactions-functional-enrichment)\n\nAlso see post on [functional enrichment of all targets](./2025_04_08_dde_miranda_FE.qmd)\n\n# 1 Format topGO files\n\n## 1.1 Read in and format annotation files\n\n``` r\n# Read in Apul annotations\nannot_locations <- read.delim(\"../output/02-Apul-reference-annotation/Apulcra-genome-mRNA-IDmapping-2024_12_12.tab\")\n# Remove unneeded columns \nannot_locations <- annot_locations %>% dplyr::select(-X, -V13)\n# Ensure there are no duplicate rows\nannot_locations <- annot_locations %>% distinct()\n\nhead(annot_locations)\n```\n\n```         \n##                     V1     V3 Protein.names\n## 1   ntLink_4:1155-1537 P35061   Histone H2A\n## 2   ntLink_4:2660-3441 P84239    Histone H3\n## 3   ntLink_4:4515-6830 P35061   Histone H2A\n## 4   ntLink_4:7096-7859 P84239    Histone H3\n## 5   ntLink_4:8474-9669 P35061   Histone H2A\n## 6 ntLink_4:11162-11925 P84239    Histone H3\n##                                     Organism Gene.Ontology..biological.process.\n## 1          Acropora formosa (Staghorn coral)                                   \n## 2 Urechis caupo (Innkeeper worm) (Spoonworm)                                   \n## 3          Acropora formosa (Staghorn coral)                                   \n## 4 Urechis caupo (Innkeeper worm) (Spoonworm)                                   \n## 5          Acropora formosa (Staghorn coral)                                   \n## 6 Urechis caupo (Innkeeper worm) (Spoonworm)                                   \n##                                            Gene.Ontology.IDs\n## 1 GO:0000786; GO:0003677; GO:0005634; GO:0030527; GO:0046982\n## 2 GO:0000786; GO:0003677; GO:0005634; GO:0030527; GO:0046982\n## 3 GO:0000786; GO:0003677; GO:0005634; GO:0030527; GO:0046982\n## 4 GO:0000786; GO:0003677; GO:0005634; GO:0030527; GO:0046982\n## 5 GO:0000786; GO:0003677; GO:0005634; GO:0030527; GO:0046982\n## 6 GO:0000786; GO:0003677; GO:0005634; GO:0030527; GO:0046982\n```\n\n``` r\n# Looks good!\n```\n\nThis file shows each gene as it's genomic location. We want to use gene IDs to associate genes, so add gene IDs to this annotation table\n\nRead in file that associates each mRNA genomic location with corresponding gene ID\n\n``` r\nmRNA_FUNids <- read.table(\"../output/15-Apul-annotate-UTRs/Apul-mRNA-FUNids.txt\", header=FALSE, col.names=c(\"location\", \"type\", \"mRNA_ID\", \"gene_ID\", \"product\"), sep=\"\\t\")\n\n# Remove unwanted text from parent column\nmRNA_FUNids$gene_ID <- gsub(\"Parent=\", \"\", mRNA_FUNids$gene_ID)\n# Only need to keep mRNA location and gene ID\nmRNA_FUNids <- mRNA_FUNids %>% dplyr::select(location, gene_ID)\n```\n\njoin with annotation file\n\n``` r\n# join\nannot <- left_join(annot_locations, mRNA_FUNids, by = c(\"V1\" = \"location\"))\n\n# ensure there are no duplicate rows\nannot <- annot %>% distinct()\n```\n\n## 1.2 Set up gene2GO object\n\nWant to isolate a list of GO terms per gene\n\n``` r\ngene2go <- annot %>% filter(!is.na(Gene.Ontology.IDs)) %>% dplyr::select(gene_ID, Gene.Ontology.IDs)\ngene2go <- gene2go %>% dplyr::rename(GO.ID = Gene.Ontology.IDs)\n\ngene2go_list <- setNames(\n  strsplit(as.character(gene2go$GO.ID), \";\"), \n  gene2go$gene_ID\n)\n```\n\nNote: I think this means genes that had a Uniprot ID but no GO terms are excluded from this analysis\n\n## 1.3 Define reference set\n\nDefine reference set of genes. This should be all genes *found in our samples*, NOT all genes in the A.pulchra genome. Some genes (e.g., reproduction pathways) may not be found/expected in our samples for valid biological reasons.\n\n``` r\n# Read in counts matrix\nApul_counts <- read.csv(\"../output/07-Apul-Hisat/Apul-gene_count_matrix.csv\")\n# Exclude genes with all 0 counts\nApul_counts <- Apul_counts[rowSums(Apul_counts[, 2:6]) != 0, ]\n\n# Select gene IDs of the genes present in our samples\nall_genes <- Apul_counts$gene_id\nlength(all_genes)\n```\n\n```         \n## [1] 33624\n```\n\nSo we have a reference set of 33624 genes present in our samples.\n\n## 1.4 Read in PCC/miranda data\n\nThis is a table of all putative miRNA-mRNA binding predicted by miRanda, plus Pearsons correlation coefficients for coexpression of each putative binding pair.\n\n``` r\ndata <- read.csv(\"../output/09-Apul-mRNA-miRNA-interactions/miranda_PCC_miRNA_mRNA.csv\")\nhead(data)\n```\n\n```         \n##   X         miRNA       mRNA    PCC.cor   p_value adjusted_p_value score energy\n## 1 1  Cluster_5981 FUN_028147  0.6825537 0.2041707        0.9986496   146 -22.19\n## 2 2 Cluster_15340 FUN_013332  0.6371070 0.2476393        0.9986496   158 -23.15\n## 3 3  Cluster_5981 FUN_041253 -0.2250869 0.7158492        0.9986496   153 -20.50\n## 4 4  Cluster_3366 FUN_010827  0.3671005 0.5433145        0.9986496   163 -22.14\n## 5 5  Cluster_3367 FUN_010827  0.5369304 0.3507987        0.9986496   163 -22.14\n## 6 6 Cluster_15340 FUN_003342  0.1096213 0.8607058        0.9986496   154 -20.65\n##   query_start_end subject_start_end total_bp_shared query_similar\n## 1            2 21           185 209              21        66.67%\n## 2            2 20           198 220              19        68.42%\n## 3            2 21           699 719              19        73.68%\n## 4            2 18           346 368              16        81.25%\n## 5            2 18           346 368              16        81.25%\n## 6            2 20           562 585              20        65.00%\n##   subject_similar\n## 1          71.43%\n## 2          84.21%\n## 3          73.68%\n## 4          93.75%\n## 5          93.75%\n## 6          80.00%\n```\n\nSet function to select genes of interest (ie those that have pvalue \\< 0.05)\n\n``` r\ntopDiffGenes <- function(allScore) {\nreturn(allScore < 0.05)}\n```\n\n# 2 FA of all miRNA targets\n\nFunctional annotation of all putative miRNA targets\n\n``` r\ncor_bind_FA <- left_join(data, annot, by = c(\"mRNA\" = \"gene_ID\")) %>% distinct()\n\nnrow(cor_bind_FA)\n```\n\n```         \n## [1] 4657\n```\n\n``` r\nnrow(cor_bind_FA[!is.na(cor_bind_FA$Gene.Ontology.IDs),])\n```\n\n```         \n## [1] 923\n```\n\nOf the 4657 putative miRNA targets predicted by miRanda, 923 have available annotations\n\n``` r\nsig_cor_bind_FA <- cor_bind_FA[cor_bind_FA$p_value < 0.05,]\n\nnrow(sig_cor_bind_FA)\n```\n\n```         \n## [1] 266\n```\n\n``` r\nnrow(sig_cor_bind_FA[!is.na(sig_cor_bind_FA$Gene.Ontology.IDs),])\n```\n\n```         \n## [1] 52\n```\n\nOf the 266 putative miRNA targets predicted by miRanda that are also have significantly correlated expression, only 52 have available annotations. This is an average of 1-2 annotated targets per miRNA. This unfortunately means **functional enrichment analysis will likely be uninformative for most groups of significantly coexpressed targets.**\n\nSave\n\n``` r\nwrite.csv(cor_bind_FA, \"../output/09.1-Apul-mRNA-miRNA-interactions-functional-enrichment/miRNA_targets_FA.csv\")\nwrite.csv(sig_cor_bind_FA, \"../output/09.1-Apul-mRNA-miRNA-interactions-functional-enrichment/miRNA_sig_cor_targets_FA.csv\")\n```\n\n# 3 FE of specific miRNA's targets (all targets)\n\nCreate topGO function for use with miRNA names\n\n``` r\nmiRNA_topGO_FE <- function(miRNA.name, input_interactions) {\n  \n  #Isolate genes in our input module of interest\n  interacting_genes <- input_interactions %>%\n    filter(miRNA == miRNA.name) %>%\n    pull(mRNA)\n  \n  if (length(interacting_genes) > 0) {\n    # Create factor for all reference genes, where 1 represents module membership and 0 means the gene is not in module of interest\n    gene_list <- factor(as.integer(all_genes %in% interacting_genes))\n    names(gene_list) <- all_genes\n    str(gene_list)\n    \n    ## Biological Process ##\n    # Create topGO object\n    GO_BP <- new(\"topGOdata\", \n                ontology = \"BP\", # Biological Process\n                allGenes = gene_list,\n                annot = annFUN.gene2GO, \n                gene2GO = gene2go_list,\n                geneSel=topDiffGenes)\n    \n    # Run GO enrichment test\n    GO_BP_FE <- runTest(GO_BP, algorithm = \"weight01\", statistic = \"fisher\")\n    # View the results\n    GO_BP_results <- GenTable(GO_BP, Fisher = GO_BP_FE, orderBy = \"Fisher\",  topNodes = 100, numChar = 51)\n    # Filter by significant results\n    GO_BP_results$Fisher<-as.numeric(GO_BP_results$Fisher)\n    GO_BP_results_sig<-GO_BP_results[GO_BP_results$Fisher<0.05,]\n    \n    \n    ## Molecular Function ##\n    # Create topGO object\n    GO_MF <- new(\"topGOdata\", \n                ontology = \"MF\", # Molecular Function\n                allGenes = gene_list,\n                annot = annFUN.gene2GO, \n                gene2GO = gene2go_list,\n                geneSel=topDiffGenes)\n    \n    # Run GO enrichment test\n    GO_MF_FE <- runTest(GO_MF, algorithm = \"weight01\", statistic = \"fisher\")\n    # View the results\n    GO_MF_results <- GenTable(GO_MF, Fisher = GO_MF_FE, orderBy = \"Fisher\",  topNodes = 100, numChar = 51)\n    # Filter by significant results\n    GO_MF_results$Fisher<-as.numeric(GO_MF_results$Fisher)\n    GO_MF_results_sig<-GO_MF_results[GO_MF_results$Fisher<0.05,]\n  \n    # Return\n    # Add type column only if results exist\n    if (nrow(GO_BP_results_sig) > 0) {\n      GO_BP_results_sig$type <- \"Biological.Process\"\n    }\n    if (nrow(GO_MF_results_sig) > 0) {\n      GO_MF_results_sig$type <- \"Molecular.Function\"\n    }\n    GO_results <- rbind(GO_BP_results_sig, GO_MF_results_sig)\n    print(GO_results)\n  }\n}\n```\n\nLoop through all miRNA and run functional enrichment on the miRNA's targets (all predicted targets)\n\n``` r\ninteracting_miRNAs <- unique(cor_bind_FA$miRNA) %>% na.omit\nresults_all_targets <- NULL  # initialize empty df\n\nfor(miRNA in interacting_miRNAs) {\n  \n  # Run topGO enrichment function\n  miRNA_results <- miRNA_topGO_FE(miRNA, cor_bind_FA)\n  \n  # Only keep results if not empty\n  if (nrow(miRNA_results) > 0) {\n    \n    # Add the miRNA source column\n    miRNA_results$miRNA <- miRNA\n\n    # Bind to the accumulating results data frame\n    results_all_targets <- rbind(results_all_targets, miRNA_results)\n  }\n}\n```\n\n``` r\nhead(results_all_targets)\n```\n\n```         \n##        GO.ID                                                   Term Annotated\n## 1 GO:0001745                             compound eye morphogenesis         3\n## 2 GO:0001933         negative regulation of protein phosphorylation         5\n## 3 GO:0009734                      auxin-activated signaling pathway         5\n## 4 GO:0004459                       L-lactate dehydrogenase activity         1\n## 5 GO:0004760                  serine-pyruvate transaminase activity         1\n## 6 GO:0004742 dihydrolipoyllysine-residue acetyltransferase activ...         1\n##   Significant Expected Fisher               type        miRNA\n## 1           1     0.03  0.027 Biological.Process Cluster_5981\n## 2           1     0.05  0.045 Biological.Process Cluster_5981\n## 3           1     0.05  0.045 Biological.Process Cluster_5981\n## 4           1     0.01  0.012 Molecular.Function Cluster_5981\n## 5           1     0.01  0.012 Molecular.Function Cluster_5981\n## 6           1     0.01  0.012 Molecular.Function Cluster_5981\n```\n\nSave results\n\n``` r\nwrite.csv(results_all_targets, \"../output/09.1-Apul-mRNA-miRNA-interactions-functional-enrichment/miRNA_all_targets_topGO_FE.csv\")\n```\n\n# 4 FE of specific miRNA's targets (significant cor targets)\n\nLoop through all miRNA and run functional enrichment on the miRNA's significantly correlated targets\n\n``` r\ninteracting_miRNAs_sig <- unique(sig_cor_bind_FA$miRNA) %>% na.omit\nresults_sig_cor_targets <- NULL  # initialize empty df\n\nfor(miRNA in interacting_miRNAs_sig) {\n  \n  # Run topGO enrichment function\n  miRNA_results <- miRNA_topGO_FE(miRNA, sig_cor_bind_FA)\n  \n  # Only keep results if not empty\n  if (nrow(miRNA_results) > 0) {\n    \n    # Add the miRNA source column\n    miRNA_results$miRNA <- miRNA\n\n    # Bind to the accumulating results data frame\n    results_sig_cor_targets <- rbind(results_sig_cor_targets, miRNA_results)\n  }\n}\n```\n\n``` r\nhead(results_sig_cor_targets)\n```\n\n```         \n##        GO.ID                                           Term Annotated\n## 1 GO:0001947                                  heart looping         4\n## 2 GO:0003341                                cilium movement        22\n## 3 GO:0004842         ubiquitin-protein transferase activity        35\n## 4 GO:0002221 pattern recognition receptor signaling pathway        11\n## 5 GO:0004252             serine-type endopeptidase activity        53\n## 6 GO:0001933 negative regulation of protein phosphorylation         5\n##   Significant Expected Fisher               type         miRNA\n## 1           1     0.00 0.0028 Biological.Process Cluster_19193\n## 2           1     0.02 0.0150 Biological.Process Cluster_10051\n## 3           1     0.02 0.0240 Molecular.Function Cluster_10051\n## 4           1     0.01 0.0077 Biological.Process Cluster_16409\n## 5           1     0.04 0.0370 Molecular.Function Cluster_16409\n## 6           1     0.00 0.0035 Biological.Process  Cluster_3250\n```\n\nSave results\n\n``` r\nwrite.csv(results_sig_cor_targets, \"../output/09.1-Apul-mRNA-miRNA-interactions-functional-enrichment/miRNA_sig_cor_targets_topGO_FE.csv\")\n```\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}