{
  "hash": "f04e3ee27f4236df347f52766d1283e0",
  "result": {
    "markdown": "---\ntitle: \"Timeseries: miRNA-lncRNA Coexpression\"\nauthor: \"Kathleen Durkin\"\ndate: \"2025-04-10\"\ncategories: [\"E5-coral\"]\nformat:\n  html:\n    toc: true\nexecute: \n  eval: TRUE\nengine: knitr\nbibliography: ../../../references.bib\n---\n\n\n[Code](https://github.com/urol-e5/timeseries_molecular/blob/main/D-Apul/code/14.2-Apul-miRNA-lncRNA-coexpression.Rmd)\\\n[Rendered code](https://github.com/urol-e5/timeseries_molecular/blob/main/D-Apul/code/14.2-Apul-miRNA-lncRNA-coexpression.md)\\\n[Output files](https://github.com/urol-e5/timeseries_molecular/tree/main/D-Apul/output/14.2-Apul-miRNA-lncRNA-coexpression)\n\nI've already used miRanda to predict miRNA-lncRNA binding. Now I want to assess coexpression for miRNA-lncRNA pairs using Pearson's correlation coefficient.\n\n``` r\n#library(energy)\nlibrary(tidyr)\nlibrary(dplyr)\nlibrary(readr)\nlibrary(ggplot2)\n```\n\nNow that we've found putative interactions, including those with high complementarity, in `10-Apul-lncRNA-miRNA-miRanda` we need to validate by examining patterns of coexpression. We'd expect a putatively-interacting miRNA-lncRNA pair to be highly coexpressed, and we'd expect a strong negative relationship to indicate either a lncRNA sponging miRNA OR an miRNA targeting lncRNA for degradation.\n\n## 0.1 Obtain Pearson's coefficient correlation values\n\nRead in, format, and normalize data\n\n``` r\nmiRNA_counts <- read.delim(\"../output/03.10-D-Apul-sRNAseq-expression-DESeq2/Apul_miRNA_ShortStack_counts_formatted.txt\")\n# Simplify column names\ncolnames(miRNA_counts) <- sub(\"_.*\", \"\", colnames(miRNA_counts))\ncolnames(miRNA_counts) <- sub(\"X\", \"\", colnames(miRNA_counts))\n\n# Remove any miRNA with 0 counts across samples \nmiRNA_counts<-miRNA_counts %>%\n    mutate(Total = rowSums(.[, 1:5]))%>%\n    filter(!Total==0)%>%\n    dplyr::select(!Total)\n\nlncRNA_counts_full <- read.delim(\"../output/08-Apul-lncRNA/counts.txt\", skip=1) \nrownames(lncRNA_counts_full) <- lncRNA_counts_full$Geneid\nlncRNA_counts <- lncRNA_counts_full %>% select(-Geneid, -Chr, -Start, -End, -Strand, -Length)\n\n# Format lncRNA column names to match the miRNA names\ncolnames(lncRNA_counts) <- sub(\"...data.\", \"\", colnames(lncRNA_counts))\ncolnames(lncRNA_counts) <- sub(\".sorted.bam\", \"\", colnames(lncRNA_counts))\n# Order lncRNA column names to match the miRNA column order\nlncRNA_counts <- lncRNA_counts[, colnames(miRNA_counts)]\n\n# Check that the columns match name and order for both dataframes\ncolnames(lncRNA_counts) == colnames(miRNA_counts)\n```\n\n```         \n##  [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE\n## [16] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE\n## [31] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE\n```\n\n``` r\n# Remove any lncRNAs with 0 for all samples \nlncRNA_counts <- lncRNA_counts %>%\n    mutate(Total = rowSums(.[, 1:5]))%>%\n    filter(!Total==0)%>%\n    dplyr::select(!Total)\n\n# Function to normalize counts (simple RPM normalization)\nnormalize_counts <- function(counts) {\n  rpm <- t(t(counts) / colSums(counts)) * 1e6\n  return(rpm)\n}\n\nmiRNA_norm <- normalize_counts(miRNA_counts)\nlncRNA_norm <- normalize_counts(lncRNA_counts)\n```\n\n``` r\n# Function to calculate PCC and p-value for a pair of vectors\ncalc_pcc <- function(x, y) {\n  result <- cor.test(x, y, method = \"pearson\")\n  return(c(PCC = result$estimate, p_value = result$p.value))\n}\n\n# Create a data frame of all miRNA-lncRNA pairs\npairs <- expand.grid(miRNA = rownames(miRNA_norm), lncRNA = rownames(lncRNA_norm))\n\n# Calculate PCC and p-value for each pair\npcc_results <- pairs %>%\n  rowwise() %>%\n  mutate(\n    pcc_stats = list(calc_pcc(miRNA_norm[miRNA,], lncRNA_norm[lncRNA,]))\n  ) %>%\n  unnest_wider(pcc_stats)\n\n# Adjust p-values for FDR\npcc_results <- pcc_results %>%\n  mutate(adjusted_p_value = p.adjust(p_value, method = \"fdr\"))\n\n# Save as csv\nwrite.csv(pcc_results, \"../output/14.2-Apul-miRNA-lncRNA-coexpression/Apul-PCC_miRNA_lncRNA-full.csv\")\n```\n\nCheck\n\n``` r\n# Read in results \npcc_results <- read.csv(\"../output/14.2-Apul-miRNA-lncRNA-coexpression/Apul-PCC_miRNA_lncRNA-full.csv\")\n\n# Use this code to download the PCC results if needed \n#pcc_results <- read.csv(\"https://gannet.fish.washington.edu/kdurkin1/ravenbackups/timeseries_molecular/D-Apul/output/14.2-Apul-miRNA-lncRNA-coexpression/Apul-PCC_miRNA_lncRNA-full.csv\")\n\nnrow(pcc_results)\n```\n\n```         \n## [1] 950283\n```\n\n``` r\nnrow(pcc_results%>% filter(abs(PCC.cor) > 0.90))\n```\n\n```         \n## [1] 3\n```\n\n``` r\nnrow(pcc_results %>% filter(p_value < 0.05))\n```\n\n```         \n## [1] 81605\n```\n\n``` r\nnrow(pcc_results %>% filter(p_value < 0.05 & abs(PCC.cor) > 0.90))\n```\n\n```         \n## [1] 3\n```\n\nof the 950,283 possible miRNA-lncRNA interactions, 3 have a Pearson's correlation coefficient with a magnitude above 0.9, and 81,605 have a significant correlation (pval\\<0.05). All of the coefficients with a magnitude \\>0.9 are significant.\n\nI find it interesting that so many putative interactions have significant pvalues, but so few have correlation coefficients above 0.9. What does the distribution of significant correlation coefficients look like?\n\n``` r\nggplot(pcc_results[pcc_results$p_value < 0.05,], aes(x = PCC.cor)) +\n  geom_density(fill = \"blue\", alpha = 0.5) +\n  labs(title = \"Density of Significant Correlations\",\n       x = \"Correlation Coefficient\",\n       y = \"Density\") +\n  theme_minimal()\n```\n\n![](./images/14.2-Apul-miRNA-lncRNA-coexpression_files/figure-gfm/unnamed-chunk-5-1.png)<!-- -->\n\n``` r\nggplot(pcc_results[pcc_results$p_value < 0.05,], aes(x = abs(PCC.cor))) +\n  geom_density(fill = \"blue\", alpha = 0.5) +\n  labs(title = \"Density of Significant Correlations (magnitudes)\",\n       x = \"Magnitude of Correlation Coefficient\",\n       y = \"Density\") +\n  theme_minimal()\n```\n\n![](./images/14.2-Apul-miRNA-lncRNA-coexpression_files/figure-gfm/unnamed-chunk-5-2.png)<!-- -->\n\nMean of the absolute value of correlation for significant correlation coefficients is `{r} round(mean(abs(pcc_results[pcc_results$p_value < 0.05,]$PCC.cor)),2)`\n\n# 1 Incorporate miRanda target prediction results\n\n## 1.1 full lncRNA\n\nI realized that the lncRNA counts matrix includes some duplicate lncRNA, where two or more distinct lncRNA IDs share the exact same genomic coordinates. As far as I can tell all of the duplicate lncRNAs have counts of 0 across all samples, so it was likely just a naming error. This also means the duplicates didn't affect the correlation calculations above, since I filtered out lncRNAs that had all-0 counts before PCC.\n\nI'll need to filter then out though to facilitate joining.\n\n``` r\n# Create mapping table that shows the full genomic location for each lncRNA\nlncRNA_mapping <- data.frame(\n  lncRNA = lncRNA_counts_full$Geneid,\n  location = paste0(lncRNA_counts_full$Chr, \":\", (lncRNA_counts_full$Start-1), \"-\", lncRNA_counts_full$End)\n)\n\n# Isolate lncRNA that have been repeated\nrepeats <- lncRNA_mapping[duplicated(lncRNA_mapping$location) | duplicated(lncRNA_mapping$location, fromLast = TRUE), ]\n\n# Isolate the repeated lncRNA counts\nrepeats_counts <- lncRNA_counts_full %>% filter(Geneid %in% repeats$lncRNA)\n\nnrow(lncRNA_mapping)\n```\n\n```         \n## [1] 24181\n```\n\n``` r\nlength(unique(lncRNA_mapping$location))\n```\n\n```         \n## [1] 23782\n```\n\n``` r\nnrow(lncRNA_mapping) - length(unique(lncRNA_mapping$location))\n```\n\n```         \n## [1] 399\n```\n\n``` r\nhead(repeats_counts)\n```\n\n```         \n##                Geneid      Chr   Start     End Strand Length\n## lncRNA_062 lncRNA_062 ntLink_6 7465722 7467150      +   1429\n## lncRNA_063 lncRNA_063 ntLink_6 7465722 7467150      +   1429\n## lncRNA_071 lncRNA_071 ntLink_6 7548691 7551215      +   2525\n## lncRNA_072 lncRNA_072 ntLink_6 7548691 7551215      +   2525\n## lncRNA_080 lncRNA_080 ntLink_6 9559991 9569239      +   9249\n## lncRNA_081 lncRNA_081 ntLink_6 9559991 9569239      +   9249\n##            ...data.1A10.sorted.bam ...data.1A12.sorted.bam\n## lncRNA_062                       0                       0\n## lncRNA_063                       0                       0\n## lncRNA_071                       0                       0\n## lncRNA_072                       0                       0\n## lncRNA_080                       0                       0\n## lncRNA_081                       0                       0\n##            ...data.1A1.sorted.bam ...data.1A2.sorted.bam ...data.1A8.sorted.bam\n## lncRNA_062                      0                      0                      0\n## lncRNA_063                      0                      0                      0\n## lncRNA_071                      0                      0                      0\n## lncRNA_072                      0                      0                      0\n## lncRNA_080                      0                      0                      0\n## lncRNA_081                      0                      0                      0\n##            ...data.1A9.sorted.bam ...data.1B10.sorted.bam\n## lncRNA_062                      0                       0\n## lncRNA_063                      0                       0\n## lncRNA_071                      0                       0\n## lncRNA_072                      0                       0\n## lncRNA_080                      0                       0\n## lncRNA_081                      0                       0\n##            ...data.1B1.sorted.bam ...data.1B2.sorted.bam ...data.1B5.sorted.bam\n## lncRNA_062                      0                      0                      0\n## lncRNA_063                      0                      0                      0\n## lncRNA_071                      0                      0                      0\n## lncRNA_072                      0                      0                      0\n## lncRNA_080                      0                      0                      0\n## lncRNA_081                      0                      0                      0\n##            ...data.1B9.sorted.bam ...data.1C10.sorted.bam\n## lncRNA_062                      0                       0\n## lncRNA_063                      0                       0\n## lncRNA_071                      0                       0\n## lncRNA_072                      0                       0\n## lncRNA_080                      0                       0\n## lncRNA_081                      0                       0\n##            ...data.1C4.sorted.bam ...data.1D10.sorted.bam\n## lncRNA_062                      0                       0\n## lncRNA_063                      0                       0\n## lncRNA_071                      0                       0\n## lncRNA_072                      0                       0\n## lncRNA_080                      0                       0\n## lncRNA_081                      0                       0\n##            ...data.1D3.sorted.bam ...data.1D4.sorted.bam ...data.1D6.sorted.bam\n## lncRNA_062                      0                      0                      0\n## lncRNA_063                      0                      0                      0\n## lncRNA_071                      0                      0                      0\n## lncRNA_072                      0                      0                      0\n## lncRNA_080                      0                      0                      0\n## lncRNA_081                      0                      0                      0\n##            ...data.1D8.sorted.bam ...data.1D9.sorted.bam ...data.1E1.sorted.bam\n## lncRNA_062                      0                      0                      0\n## lncRNA_063                      0                      0                      0\n## lncRNA_071                      0                      0                      0\n## lncRNA_072                      0                      0                      0\n## lncRNA_080                      0                      0                      0\n## lncRNA_081                      0                      0                      0\n##            ...data.1E3.sorted.bam ...data.1E5.sorted.bam ...data.1E9.sorted.bam\n## lncRNA_062                      0                      0                      0\n## lncRNA_063                      0                      0                      0\n## lncRNA_071                      0                      0                      0\n## lncRNA_072                      0                      0                      0\n## lncRNA_080                      0                      0                      0\n## lncRNA_081                      0                      0                      0\n##            ...data.1F11.sorted.bam ...data.1F4.sorted.bam\n## lncRNA_062                       0                      0\n## lncRNA_063                       0                      0\n## lncRNA_071                       0                      0\n## lncRNA_072                       0                      0\n## lncRNA_080                       0                      0\n## lncRNA_081                       0                      0\n##            ...data.1F8.sorted.bam ...data.1G5.sorted.bam\n## lncRNA_062                      0                      0\n## lncRNA_063                      0                      0\n## lncRNA_071                      0                      0\n## lncRNA_072                      0                      0\n## lncRNA_080                      0                      0\n## lncRNA_081                      0                      0\n##            ...data.1H11.sorted.bam ...data.1H12.sorted.bam\n## lncRNA_062                       0                       0\n## lncRNA_063                       0                       0\n## lncRNA_071                       0                       0\n## lncRNA_072                       0                       0\n## lncRNA_080                       0                       0\n## lncRNA_081                       0                       0\n##            ...data.1H6.sorted.bam ...data.1H7.sorted.bam ...data.1H8.sorted.bam\n## lncRNA_062                      0                      0                      0\n## lncRNA_063                      0                      0                      0\n## lncRNA_071                      0                      0                      0\n## lncRNA_072                      0                      0                      0\n## lncRNA_080                      0                      0                      0\n## lncRNA_081                      0                      0                      0\n##            ...data.2B2.sorted.bam ...data.2B3.sorted.bam ...data.2C1.sorted.bam\n## lncRNA_062                      0                      0                      0\n## lncRNA_063                      0                      0                      0\n## lncRNA_071                      0                      0                      0\n## lncRNA_072                      0                      0                      0\n## lncRNA_080                      0                      0                      0\n## lncRNA_081                      0                      0                      0\n##            ...data.2C2.sorted.bam ...data.2D2.sorted.bam ...data.2E2.sorted.bam\n## lncRNA_062                      0                      0                      0\n## lncRNA_063                      0                      0                      0\n## lncRNA_071                      0                      0                      0\n## lncRNA_072                      0                      0                      0\n## lncRNA_080                      0                      0                      0\n## lncRNA_081                      0                      0                      0\n##            ...data.2F1.sorted.bam ...data.2G1.sorted.bam\n## lncRNA_062                      0                      0\n## lncRNA_063                      0                      0\n## lncRNA_071                      0                      0\n## lncRNA_072                      0                      0\n## lncRNA_080                      0                      0\n## lncRNA_081                      0                      0\n```\n\nThere are 399 duplicate lncRNAs in the counts data\n\nSince I'll be using `lncRNA_mapping` for joining purposes, it must contain only unique genomic locations.\n\nDeduplicate `lncRNA_mapping`:\n\n``` r\nunique_mapping <- lncRNA_mapping[!duplicated(lncRNA_mapping$location), ]\n\nnrow(lncRNA_mapping) - nrow(unique_mapping)\n```\n\n```         \n## [1] 399\n```\n\nGreat! Now that we have a mapping file of only our unique lncRNAs, we can proceed to incorporating the miRanda output.\n\n``` r\n# miRNA-lncRNA_full miRanda output\nmiRNA_lncRNA_miRanda <- read_delim(\"../output/10-Apul-lncRNA-miRNA-miRanda/Apul-miRanda-lncRNA-strict-parsed.txt\", col_names=FALSE)\n```\n\n```         \n## Rows: 178148 Columns: 9\n## ── Column specification ────────────────────────────────────────────────────────\n## Delimiter: \"\\t\"\n## chr (6): X1, X2, X5, X6, X8, X9\n## dbl (3): X3, X4, X7\n## \n## ℹ Use `spec()` to retrieve the full column specification for this data.\n## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n``` r\ncolnames(miRNA_lncRNA_miRanda) <- c(\"mirna\", \"Target\", \"Score\", \"Energy_Kcal_Mol\", \"Query_Aln\", \"Subject_Aln\", \"Al_Len\", \"Subject_Identity\", \"Query_Identity\")\n\n\n# format miRNA names\nmiRNA_lncRNA_miRanda$mirna <- gsub(\">\", \"\", miRNA_lncRNA_miRanda$mirna)\nmiRNA_lncRNA_miRanda$mirna <- gsub(\"\\\\..*\", \"\", miRNA_lncRNA_miRanda$mirna)\n\n# Join with mapping file to annote miRanda results with lncRNA IDs\nmiRNA_lncRNA_miRanda <- left_join(miRNA_lncRNA_miRanda, unique_mapping, by=c(\"Target\" = \"location\"))\n\n# Create a columns that contains both the miRNA and interacting lncRNA\npcc_results$interaction <- paste0(pcc_results$miRNA, \":\", pcc_results$lncRNA)\nmiRNA_lncRNA_miRanda$interaction <- paste0(miRNA_lncRNA_miRanda$mirna, \":\", miRNA_lncRNA_miRanda$lncRNA)\n\n# Annotate miRanda results w PCC info \nmiRNA_lncRNA_miRanda <- left_join(miRNA_lncRNA_miRanda, pcc_results, by=\"interaction\")\n```\n\n``` r\n# Filter to high complementarity putative targets\ntarget_21bp <- miRNA_lncRNA_miRanda[miRNA_lncRNA_miRanda$Al_Len > 20,]\ntarget_21bp_3mis <- target_21bp[target_21bp$Subject_Identity>85,]\n\n# How many w significant correlation?\nnrow(miRNA_lncRNA_miRanda)\n```\n\n```         \n## [1] 178148\n```\n\n``` r\nnrow(miRNA_lncRNA_miRanda %>% filter(!is.na(PCC.cor)))\n```\n\n```         \n## [1] 115512\n```\n\n``` r\nnrow(miRNA_lncRNA_miRanda %>% filter(p_value < 0.05))\n```\n\n```         \n## [1] 9677\n```\n\n``` r\nnrow(target_21bp %>% filter(p_value < 0.05))\n```\n\n```         \n## [1] 1396\n```\n\n``` r\nnrow(target_21bp_3mis %>% filter(p_value < 0.05))\n```\n\n```         \n## [1] 0\n```\n\nFor miRNA binding to lncRNA, miRanda predicts 178,148 putative interactions. Of these, 115,512 yield a correlation value (indicating the lncRNA is actually present in our counts data); 9,677 have significant PCCs; 1,396 are \\>21bp and have signficant PCCs; and 0 are \\>21bp with \\<=3 mismatches and have significant PCCs.\n\n# 2 Summary\n\nHow does different input and/or complementarity filtering affect \\# putative interactions:\n\nReminder summary of miRanda results:\n\n| Input  | All     | 21bp                     | 21bp, \\>=3 mismatch  |\n|:-------|:--------|:-------------------------|:---------------------|\n| lncRNA | 178,148 | 24,018 (13.48% of total) | 22 (0.012% of total) |\n\nFor different filters, how many putative interactions ***also show significant coexpression*** (PCC pval \\< 0.05)?\n\n| Input  | All     | 21bp                    | 21bp, \\>=3 mismatch  |\n|:-------|:--------|:------------------------|:---------------------|\n| lncRNA | 105,835 | 14,503 (13.7% of total) | 13 (0.012% of total) |\n\nNote that some putative interactions indicated by miRanda are not present in the counts data (i.e. the miRNA and/or lncRNA had 0 counts inour RNAseq data), and are thus excluded from the PCC-filtered data\n\nIs there a clear \"cutoff\" for what complementarity parameters are most associated with significant coexpression?\n\n``` r\nsignificant_df <- miRNA_lncRNA_miRanda %>% filter(p_value < 0.05)\n\n# Plot with jitter (significant coexpression only)\nggplot(significant_df, aes(x = Al_Len, \n                           y = as.numeric(gsub(\"%\", \"\", Subject_Identity)))) +\n  geom_density_2d_filled(contour_var = \"density\", alpha = 0.8) +\n  scale_x_continuous(breaks = seq(min(significant_df$Al_Len), max(significant_df$Al_Len), by = 1)) +\n  labs(x = \"Alignment Length (Al_Len)\", \n       y = \"Subject Identity (%)\", \n       title = \"2D Density: Alignment Length vs. Subject Identity (p < 0.05)\") +\n  theme_minimal()\n```\n\n![](./images/14.2-Apul-miRNA-lncRNA-coexpression_files/figure-gfm/unnamed-chunk-10-1.png)Interesting! There are significant coexpressions happening across both metrics of complementarity, but we see clustering between 17 and 20nt alignment length.\n\nIn other words, for all the miRNA-lncRNA binding interactions predicted by miRanda, interactions with high alignment lengths (17-20nt) appear most likely to also show significantly correlated expression.\n\nThere's also a cluster at the top left corner, showing us that many interactions significant correlations have low alignment lengths but perfect complementarity. this likely represents perfect binding in the seed region.\n\n``` r\n# Save putative interactions with significantly correlated coexpression for visualization\n# (e.g. creating an interaction network plot in Cytoscape)\nwrite.csv(significant_df, \"../output/14.2-Apul-miRNA-lncRNA-coexpression/miRanda-PCC-significant-miRNA_lncRNA.csv\", row.names = FALSE)\n```\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}