---
title: "October Goals"
author: "Kathleen Durkin"
date: "2023-10-18"
categories:
    - misc.
---

After fairly continuous head-bashing with RStudio/bash/blast for the last two weeks I'm kind of tired of it, so today I'm going to focus on other stuff -- like setting some goals! I've had \~3 weeks now to get settled into the lab and Steven and I have had the chance to talk about possible directions for the near future, so let's put some stuff in writing :)

-   **Successfully run a blast search in Raven.** This feels basic, but considering the myriad difficulties I've had with RStudio/Github/Raven/bash/blast over the last few weeks, something tells me it won't be :/

-   **Read up on the cod temperature/growth project.** I'm going to be sticking with this project for a while, so I want to get a better background understanding of project goals, methodology, and data collection/processing to-date. I'm really excited to be working on an experimental project, since my previous work has all used broad survey data from various sample collection trips and museum collections! This project may also involve more wetwork, which I'd be really excited to get my hands on -- as much as I love coding, I'm already missing the lab a bit.

-   **Read up on E5 coral project and start to get settled in it.** I'm also going to be joining the E5 coral project -- returning to my coral background! (Technically my background is in *soft* corals not stony, but details details details). I've already looked through the E5 coral website a few times, but I want to do a deeper dive once I know exactly what aspect of the project I'm going to be working on (maybe short RNAs?)

-   **Get registered for SICB.** That's it :)
