---
title: "Getting situated in Raven (cont.)"
author: "Kathleen Durkin"
date: "2023-10-17"
categories:
    - onboarding
---

I continued trying to figure out how to work in Raven today and ran into another fun problem -- my Raven RStudio isn't connected to my github, even though I copied the directory I'm working in directly from Github in the same way I would copy a repo to RStudio on my local machine. I realized I wasn't able to commit or push/pull, and using the command \`\`\``{bash} git config –global user.name "shedurkin"`\`\`\` didn't fix the issue. It clearly isn't an issue with my shell script/terminal because I've been successfully running command line code on Raven. Maybe Raven isn't supposed to end up tied to github? I would think the code and stuff should all end up on github for backup/reproducibility purposes, but I can also see why sending some things to github (e.g. output files) could require an unreasonable amount of storage...

I also managed to modify the 001-blast.Rmd tutorial script to download a windows version of ncbi blast to Raven and run the .exe, but I wasn't able to successfully access the blast.exe component used in the first task of the tutorial file (setting blast directory). Neither I nor google can figure out why with a cursory search and I unfortunately have class soon, but in the worst case I can bring this up at lab meeting on Thursday.
