---
title: "Lit Review"
author: "Kathleen Durkin"
date: "2023-10-05"
categories:
    - onboarding
    - lit review
---

Continued reading through recent lab publications (see entry from yesterday) and compiled some questions about them to ask Steven at Science Hour tomorrow (see below). I also completed the required HazCom training (and returned updated training documentation to Sam), requested access to the UW chemical inventory/safety system, and wrote and uploaded a personal description, lab notebook link, email, and picture, to the lab website.

[Questions:]{.underline}

General

-   I read that both cytosine and adenine can be methylated, but every paper I've read so far studying methylation only looked at methylation of cytosine -- is there a reason adenine methylation is not commonly studied?

-   Is all methylation (in gamete cells) heritable/potentially heritable? Do we know? If not, do we know why/what determines heritability? What about other forms of epigenetic modification?

    -   Similarly, what proportion of methylation (or epigenetic modification in general) affects gamete cells?

George et al. 2023 (Triploid Pacific oysters exhibit stress response dysregulation...)

-   George et al. 2023 studied polyploidy in oysters because of its common use in oyster aquaculture -- does polyploidy have any potential conservation applications, particularly in eukaryotes, for whom ployploidy is often better tolerated? One scenario I can think of is intentional hybridization of two species to selectively breed a more resilient population -- since polyploidy is more common in hybrids, may be important to understand its impacts. I also know polyploidy sometimes happens in corals (especially Caribbean corals), which can reproduce asexually fairly easily. (Need to read related paper Stephens et al. 2023 -- w/ Putnam and Bhattacharya!)

-   Confused about a couple aspects of the experimental setup:

    -   Stated that lab obtained 500 oysters for the experiment, but then states that the starting sample size of each of the six treatments (2 controls, 2 single stressor, 2 multiple stressors) was 112, which adds to way over 500 oysters

    -   For the multiple stressors treatment, why was aerial exposure not repeated multiple times (since low tide happens on a regular daily schedule, not just once during a given warming event)?

-   In Results, why is survival probability not the direct inverse of mortality?

-   I think I noticed some typos... do you want to know about them or just leave it be?

Putnam et al. 2023 (Dynamic DNA methylation contributes to carryover effects...)

-   In the results section I saw that shell area was used as a proxy for shell size -- is it assumed that shell *thickness* remains fairly constant? Do we know this will hold during acidification? Also, are shell size and body mass tightly correlated? (I would assume so, but it would be interesting if acidic conditions messed with that relationship)

-   In Fig.3 I'm a little confused about the y-axes of 3c and 3d -- what is the baseline (the "1") for these relative size values? It doesn't seem like it could be original size (as in a and b)

-   What is the difference between differentially methylated regions (DMRs) and differentially methylated genes (DMGs)? Are DMRs just methylation of non-coding DNA (e.g. introns)?

-   I have no idea what's going on in figure 4 :(

-   or figure 5

-   What are DEGs (pg12)? Also, are CpGs just cytosine/guanine pairs?

General interests:

Understanding and mitigating impacts of climate change/anthropogenic disturbance on marine ecosytems

Specific interests:

epigenetics (and heritbility of epigenetic modifications), phenotypic plasticity, microbiome, disease resistance/resilience, ecotoxicology

Additional papers to read:

Eirin-Lopez and Putnam, 2019 (shows DNA methylation varies in response to environmental factors in marine inverts)

Stephens et al. 2023 (Ploidy variation and its implications for reproduction and population dynamics in two sympatric coral species)

Strader et al. 2019 (heritable epigenetic modifications and transgenerational plasticity in sea urchins)
