---
title: "Getting situated in Raven (cont.)"
author: "Kathleen Durkin"
date: "2023-10-19"
categories:
    - onboarding
---

Revelations from lab meeting today! Several of my Raven problems were solved during our raven/github-focused meeting today -- notes below:

-   **Connecting Raven with my Github.** I needed to enter

    \`\`\``{bash} git config –global user.email "[mygithubemailthatIdon'twanttopublicize]"   git config –global user.name "shedurkin"`\`\`\`

    *and* then log in to git using my username and a personal access token (which I have now created). I'm now fully connected to github from Raven and have successfully pushed/pulled!

-   **Getting/accessing ncbi blast software on Raven.** Blast is indeed already downloaded and accessible on Raven, it's just in a higher-level directory that I couldn't find because I didn't know about it (I can only default view my home directory on Raven). The higher-level lab directory is /home/shared, and ncbi-blast v. 2.12.0 is already installed there!

-   **Pushing large files to Github.** Don't! Any file (e.g. output file) sizes larger than 100MB should *not* be pushed to Github - instead, put it on Gannet (another lab server intended for large-file-size data and output storage). Already github-issued Sam/Steven to ask for access to Gannet.
