{
  "hash": "2fe253e82101e2b99f1bf86eafc5848e",
  "result": {
    "markdown": "---\ntitle: \"TapeStation QC of Bead-Cleaned Samples\"\nauthor: \"Kathleen Durkin\"\ndate: \"2025-07-25\"\ncategories: [\"SIFP-2025\"]\nformat:\n  html:\n    toc: true\nexecute: \n  eval: TRUE\nengine: knitr\nbibliography: ../../../references.bib\n---\n\n\nAfter cleaning and concentrating all extractions using KAPA Pure Beads, used the TapeStation with a Genomic Tape to check DNA concetration, quality, and size distribution. Followed [protocol for Agilent 4200 gDNA](./protocols/Agilent_4200_gDNA_QuickGuide.pdf).\n\nSee full TapeStation summaries here: [Tape 1 summary](https://gannet.fish.washington.edu/kdurkin1/SIFP_2025/TapeStation/2025_07_25_summary_tape1.pdf), [Tape 2 summary](https://gannet.fish.washington.edu/kdurkin1/SIFP_2025/TapeStation/2025_07_25_summary_tape2.pdf)\n\n![Oldest age group](./data/2025_07_25_TapeStation/2025_07_25_comparison_oldGroup.png)\n\n![Mid-age group](./data/2025_07_25_TapeStation/2025_07_25_comparison_midGroup.png)\n\n![Modern age group](./data/2025_07_25_TapeStation/2025_07_25_comparison_modernGroup.png)\n\n(Note the above plots have different y-axis scales)\n\n| Tape \\# | Catalog \\# | Year Collected | DIN | Conc. (ng/uL) | \\% reads \\>300bp long |\n|------------|------------|------------|------------|------------|------------|\n| 1       | 14366      | 1886           | \\-  | 1.57          | 63.15                 |\n| 1       | 19054      | 1898           | 1.2 | 21.6          | 82.13                 |\n| 1       | 52295      | 1912           | 1.0 | 19.9          | 61.63                 |\n| 1       | 1180630    | 1912           | 1.0 | 4.33          | 62.25                 |\n| 1       | 50603      | 1912           | 1.0 | 42.4          | 73.82                 |\n| 1       | 51732      | 1960           | 2.1 | 157           | 93.80                 |\n| 1       | 51892      | 1960           | 1.9 | 137           | 94.20                 |\n| 1       | 14399      | 1886           | 1.2 | 100           | 86.10                 |\n| 1       | 42137      | 1898           | 1.1 | 46.3          | 86.49                 |\n| 1       | 51730      | 1960           | 1.1 | 59.6          | 71.13                 |\n| 1       | 51728      | 1960           | 1.4 | 23.7          | 89.90                 |\n| 1       | 100609     | 2000           | 2.9 | 261           | 96.34                 |\n| 1       | 100610     | 2000           | 1.9 | 164           | 93.57                 |\n| 1       | 1007393    | 2000           | 2.8 | 218           | 93.49                 |\n| 1       | 1018355    | 2002           | 1.8 | 115           | 89.98                 |\n| 2       | 1606824    | 2019           | 1.7 | 353           | 90.80                 |\n| 2       | 1606826    | 2019           | 3.4 | 408           | 97.21                 |\n| 2       | 1740336    | 2019           | 3.1 | 368           | 96.99                 |\n| 2       | 1740363    | 2019           | 3.3 | 343           | 97.40                 |\n| 2       | 1740390    | 2019           | 2.4 | 291           | 96.83                 |\n| 2       | 1740407    | 2019           | 3.1 | 260           | 96.89                 |\n| 2       | 50368      | 1880           | 1.7 | 68.3          | 91.68                 |\n| 2       | 51727      | 1960           | 1.3 | 15.3          | 87.12                 |\n| 2       | 51729      | 1960           | 1.5 | 18.7          | 89.23                 |\n| 2       | 51857      | 1960           | 1.4 | 109           | 93.00                 |\n| 2       | 51858      | 1960           | 1.3 | 24.2          | 88.78                 |\n| 2       | 51859      | 1960           | 1.5 | 117           | 92.46                 |\n| 2       | 51860      | 1960           | 1.4 | 15.6          | 86.46                 |\n| 2       | 51861      | 1960           | 1.7 | 94.1          | 94.72                 |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(googlesheets4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'googlesheets4' was built under R version 4.2.3\n```\n:::\n\n```{.r .cell-code}\nlibrary(tidyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tidyr' was built under R version 4.2.3\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(plotly)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'plotly' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'plotly'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:ggplot2':\n\n    last_plot\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:stats':\n\n    filter\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:graphics':\n\n    layout\n```\n:::\n\n```{.r .cell-code}\nconc <- read_sheet(\"https://docs.google.com/spreadsheets/d/1zDMy7AOCM8Ug85q4vr9CoMDxfF-zDJk1DnaxakSt1Hg/edit?usp=sharing\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n! Using an auto-discovered, cached token.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n  To suppress this message, modify your code or options to clearly consent to\n  the use of a cached token.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n  See gargle's \"Non-interactive auth\" vignette for more details:\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n  <https://gargle.r-lib.org/articles/non-interactive-auth.html>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nℹ The googlesheets4 package is using a cached token for 'kdurkin1@uw.edu'.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nAuto-refreshing stale OAuth token.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n✔ Reading from \"E_tourneforti\".\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n✔ Range 'E_tourneforti_samples'.\n```\n:::\n\n```{.r .cell-code}\nconc$Collection.Age <- ifelse(conc$Year.Collected < 1920, \"pre-1920\",\n                              ifelse(conc$Year.Collected > 1999, \"Modern\", \"1960s-70s\"))\nconc$Collection.Age <- factor(conc$Collection.Age,\n                              levels = c(\"pre-1920\", \"1960s-70s\", \"Modern\"),\n                              ordered = TRUE)\n\np1 <- ggplot(conc, aes(x=Tapestation.Perc.300up, \n                       y=Tapestation.Conc.ngul, \n                       color = Collection.Age,\n                       text = paste(\"Catalog #:\", Catalog.Number,\n                                    \"<br>Year:\", Year.Collected,\n                                    \"<br>% >300kb:\", Tapestation.Perc.300up,\n                                    \"<br>Conc:\", Tapestation.Conc.ngul))) +\n  geom_jitter(size = 2, width = 0.25, height = 0) +\n  geom_hline(yintercept = 13.33, color = 'black') +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +\n  xlab(\"Percent of reads >300kb\") +\n  ylab(\"Concentration (ng/uL)\")\n\np2 <- ggplot(conc, aes(x=Tapestation.DIN, \n                       y=Tapestation.Conc.ngul, \n                       color=Collection.Age,\n                       text = paste(\"Catalog #:\", Catalog.Number,\n                                    \"<br>Year:\", Year.Collected,\n                                    \"<br>DIN:\", Tapestation.DIN,\n                                    \"<br>Conc:\", Tapestation.Conc.ngul))) +\n  geom_jitter(size = 2, width = 0.25, height = 0) +\n  geom_hline(yintercept = 13.33, color = 'black') +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +\n  xlab(\"DNA Integrity Number (DIN)\") +\n  ylab(\"Concentration (ng/uL)\")\n\np3 <- ggplot(conc, aes(x=Tapestation.DIN, \n                       y=Tapestation.Perc.300up, \n                       color=Collection.Age,\n                       text = paste(\"Catalog #:\", Catalog.Number,\n                                    \"<br>Year:\", Year.Collected,\n                                    \"<br>DIN:\", Tapestation.DIN,\n                                    \"<br>% >300kb:\", Tapestation.Perc.300up))) +\n  geom_jitter(size = 2, width = 0.25, height = 0) +\n  geom_hline(yintercept = 13.33, color = 'black') +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +\n  xlab(\"DNA Integrity Number (DIN)\") +\n  ylab(\"Percent of reads >300kb\")\n\nggplotly(p1, tooltip = \"text\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-41c93611145ec2e11d2b\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-41c93611145ec2e11d2b\">{\"x\":{\"data\":[{\"x\":[73.968535690270357,82.136434086360964,86.331517713735806,86.097818125528278,91.636865359563387,63.322095035552046,61.634344945074993,62.495753557654098,null,null,null],\"y\":[42.399999999999999,21.600000000000001,46.299999999999997,100,68.299999999999997,1.5700000000000001,19.899999999999999,4.3300000000000001,null,null,null],\"text\":[\"Catalog #: USNM 50603 <br>Year: 1912 <br>% >300kb: 73.82 <br>Conc: 42.4\",\"Catalog #: USNM 19054 <br>Year: 1898 <br>% >300kb: 82.13 <br>Conc: 21.6\",\"Catalog #: USNM 42137 <br>Year: 1898 <br>% >300kb: 86.49 <br>Conc: 46.3\",\"Catalog #: USNM 14399 <br>Year: 1886 <br>% >300kb: 86.1 <br>Conc: 100\",\"Catalog #: USNM 50368 <br>Year: 1880 <br>% >300kb: 91.68 <br>Conc: 68.3\",\"Catalog #: USNM 14366 <br>Year: 1886 <br>% >300kb: 63.15 <br>Conc: 1.57\",\"Catalog #: USNM 52295 <br>Year: 1912 <br>% >300kb: 61.63 <br>Conc: 19.9\",\"Catalog #: USNM 1180630 <br>Year: 1912 <br>% >300kb: 62.25 <br>Conc: 4.33\",\"Catalog #: USNM 1207569 <br>Year: 1886 <br>% >300kb: NA <br>Conc: NA\",\"Catalog #: USNM 14366 <br>Year: 1886 <br>% >300kb: NA <br>Conc: NA\",\"Catalog #: USNM 52026 <br>Year: 1898 <br>% >300kb: NA <br>Conc: NA\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(68,1,84,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(68,1,84,1)\"}},\"hoveron\":\"points\",\"name\":\"pre-1920\",\"legendgroup\":\"pre-1920\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[93.125277973362245,92.398484275713557,94.865541973994112,94.346942819934341,93.817232425045219,70.930371136865574,89.747369423718197,86.944222375755203,89.174301912444648,88.993882158626803,86.603670002464199],\"y\":[109,117,94.099999999999994,137,157,59.600000000000001,23.699999999999999,15.300000000000001,18.699999999999999,24.199999999999999,15.6],\"text\":[\"Catalog #: USNM 51857 <br>Year: 1960 <br>% >300kb: 93 <br>Conc: 109\",\"Catalog #: USNM 51859 <br>Year: 1960 <br>% >300kb: 92.46 <br>Conc: 117\",\"Catalog #: USNM 51861 <br>Year: 1960 <br>% >300kb: 94.72 <br>Conc: 94.1\",\"Catalog #: USNM 51892 <br>Year: 1960 <br>% >300kb: 94.2 <br>Conc: 137\",\"Catalog #: USNM 51732 <br>Year: 1960 <br>% >300kb: 93.8 <br>Conc: 157\",\"Catalog #: USNM 51730 <br>Year: 1960 <br>% >300kb: 71.13 <br>Conc: 59.6\",\"Catalog #: USNM 51728 <br>Year: 1960 <br>% >300kb: 89.9 <br>Conc: 23.7\",\"Catalog #: USNM 51727 <br>Year: 1960 <br>% >300kb: 87.12 <br>Conc: 15.3\",\"Catalog #: USNM 51729 <br>Year: 1960 <br>% >300kb: 89.23 <br>Conc: 18.7\",\"Catalog #: USNM 51858 <br>Year: 1960 <br>% >300kb: 88.78 <br>Conc: 24.2\",\"Catalog #: USNM 51860 <br>Year: 1960 <br>% >300kb: 86.46 <br>Conc: 15.6\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(33,144,140,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(33,144,140,1)\"}},\"hoveron\":\"points\",\"name\":\"1960s-70s\",\"legendgroup\":\"1960s-70s\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[96.360750993629921,97.098563969470561,97.228796827583579,96.924794405475254,97.324282017224462,93.412982004978687,93.72872659541666,90.145337622747761,90.550515700317916,96.928008834873324],\"y\":[261,260,343,368,408,164,218,115,353,291],\"text\":[\"Catalog #: USNM 100609 <br>Year: 2000 <br>% >300kb: 96.34 <br>Conc: 261\",\"Catalog #: USNM 1740407 <br>Year: 2019 <br>% >300kb: 96.89 <br>Conc: 260\",\"Catalog #: USNM 1740363 <br>Year: 2019 <br>% >300kb: 97.4 <br>Conc: 343\",\"Catalog #: USNM 1740336 <br>Year: 2019 <br>% >300kb: 96.99 <br>Conc: 368\",\"Catalog #: USNM 1606826 <br>Year: 2019 <br>% >300kb: 97.21 <br>Conc: 408\",\"Catalog #: USNM 100610 <br>Year: 2000 <br>% >300kb: 93.57 <br>Conc: 164\",\"Catalog #: USNM 1007393 <br>Year: 2000 <br>% >300kb: 93.49 <br>Conc: 218\",\"Catalog #: USNM 1018355 <br>Year: 2002 <br>% >300kb: 89.98 <br>Conc: 115\",\"Catalog #: USNM 1606824 <br>Year: 2019 <br>% >300kb: 90.8 <br>Conc: 353\",\"Catalog #: USNM 1740390 <br>Year: 2019 <br>% >300kb: 96.83 <br>Conc: 291\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(253,231,37,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(253,231,37,1)\"}},\"hoveron\":\"points\",\"name\":\"Modern\",\"legendgroup\":\"Modern\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[59.849848091467521,99.108778870831941],\"y\":[13.33,13.33],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283104,\"r\":7.3059360730593621,\"b\":40.182648401826491,\"l\":43.105022831050235},\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[59.849848091467521,99.108778870831941],\"tickmode\":\"array\",\"ticktext\":[\"60\",\"70\",\"80\",\"90\"],\"tickvals\":[60,70,80,90],\"categoryorder\":\"array\",\"categoryarray\":[\"60\",\"70\",\"80\",\"90\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-45,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Percent of reads >300kb\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-18.7515,428.32150000000001],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"100\",\"200\",\"300\",\"400\"],\"tickvals\":[0,100,200,300,400],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"100\",\"200\",\"300\",\"400\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Concentration (ng/uL)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"title\":{\"text\":\"Collection.Age\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"fe81e601da3\":{\"x\":{},\"y\":{},\"colour\":{},\"text\":{},\"type\":\"scatter\"},\"fe83901348e\":{\"yintercept\":{}}},\"cur_data\":\"fe81e601da3\",\"visdat\":{\"fe81e601da3\":[\"function (y) \",\"x\"],\"fe83901348e\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n\n```{.r .cell-code}\nggplotly(p2, tooltip = \"text\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-d7a601bda6dc67097ee3\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-d7a601bda6dc67097ee3\">{\"x\":{\"data\":[{\"x\":[1.1171276855748147,1.143094512913376,1.0961635840591044,1.3171535111498087,1.4571594767505303,null,1.1700200388440862,0.91233863891102374,null,null,null],\"y\":[42.399999999999999,21.600000000000001,46.299999999999997,100,68.299999999999997,1.5700000000000001,19.899999999999999,4.3300000000000001,null,null,null],\"text\":[\"Catalog #: USNM 50603 <br>Year: 1912 <br>DIN: 1 <br>Conc: 42.4\",\"Catalog #: USNM 19054 <br>Year: 1898 <br>DIN: 1.2 <br>Conc: 21.6\",\"Catalog #: USNM 42137 <br>Year: 1898 <br>DIN: 1.1 <br>Conc: 46.3\",\"Catalog #: USNM 14399 <br>Year: 1886 <br>DIN: 1.2 <br>Conc: 100\",\"Catalog #: USNM 50368 <br>Year: 1880 <br>DIN: 1.7 <br>Conc: 68.3\",\"Catalog #: USNM 14366 <br>Year: 1886 <br>DIN: NA <br>Conc: 1.57\",\"Catalog #: USNM 52295 <br>Year: 1912 <br>DIN: 1 <br>Conc: 19.9\",\"Catalog #: USNM 1180630 <br>Year: 1912 <br>DIN: 1 <br>Conc: 4.33\",\"Catalog #: USNM 1207569 <br>Year: 1886 <br>DIN: NA <br>Conc: NA\",\"Catalog #: USNM 14366 <br>Year: 1886 <br>DIN: NA <br>Conc: NA\",\"Catalog #: USNM 52026 <br>Year: 1898 <br>DIN: NA <br>Conc: NA\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(68,1,84,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(68,1,84,1)\"}},\"hoveron\":\"points\",\"name\":\"pre-1920\",\"legendgroup\":\"pre-1920\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.3960145701188593,1.6839895080775023,1.5375069904141128,1.7410067074000835,2.0059096506098286,1.115787588316016,1.3687665558885782,1.0619627373060212,1.4614651193842292,1.4102322868537158,1.4114205125719308],\"y\":[109,117,94.099999999999994,137,157,59.600000000000001,23.699999999999999,15.300000000000001,18.699999999999999,24.199999999999999,15.6],\"text\":[\"Catalog #: USNM 51857 <br>Year: 1960 <br>DIN: 1.4 <br>Conc: 109\",\"Catalog #: USNM 51859 <br>Year: 1960 <br>DIN: 1.5 <br>Conc: 117\",\"Catalog #: USNM 51861 <br>Year: 1960 <br>DIN: 1.7 <br>Conc: 94.1\",\"Catalog #: USNM 51892 <br>Year: 1960 <br>DIN: 1.9 <br>Conc: 137\",\"Catalog #: USNM 51732 <br>Year: 1960 <br>DIN: 2.1 <br>Conc: 157\",\"Catalog #: USNM 51730 <br>Year: 1960 <br>DIN: 1.1 <br>Conc: 59.6\",\"Catalog #: USNM 51728 <br>Year: 1960 <br>DIN: 1.4 <br>Conc: 23.7\",\"Catalog #: USNM 51727 <br>Year: 1960 <br>DIN: 1.3 <br>Conc: 15.3\",\"Catalog #: USNM 51729 <br>Year: 1960 <br>DIN: 1.5 <br>Conc: 18.7\",\"Catalog #: USNM 51858 <br>Year: 1960 <br>DIN: 1.3 <br>Conc: 24.2\",\"Catalog #: USNM 51860 <br>Year: 1960 <br>DIN: 1.4 <br>Conc: 15.6\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(33,144,140,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(33,144,140,1)\"}},\"hoveron\":\"points\",\"name\":\"1960s-70s\",\"legendgroup\":\"1960s-70s\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2.7064387793419882,3.0951786237070338,3.3990768524352459,3.1054082780843602,3.2838912402279674,2.1421411006944253,2.9486964785726739,2.0054823982762171,1.4687227225396782,2.3389891801401972],\"y\":[261,260,343,368,408,164,218,115,353,291],\"text\":[\"Catalog #: USNM 100609 <br>Year: 2000 <br>DIN: 2.9 <br>Conc: 261\",\"Catalog #: USNM 1740407 <br>Year: 2019 <br>DIN: 3.1 <br>Conc: 260\",\"Catalog #: USNM 1740363 <br>Year: 2019 <br>DIN: 3.3 <br>Conc: 343\",\"Catalog #: USNM 1740336 <br>Year: 2019 <br>DIN: 3.1 <br>Conc: 368\",\"Catalog #: USNM 1606826 <br>Year: 2019 <br>DIN: 3.4 <br>Conc: 408\",\"Catalog #: USNM 100610 <br>Year: 2000 <br>DIN: 1.9 <br>Conc: 164\",\"Catalog #: USNM 1007393 <br>Year: 2000 <br>DIN: 2.8 <br>Conc: 218\",\"Catalog #: USNM 1018355 <br>Year: 2002 <br>DIN: 1.8 <br>Conc: 115\",\"Catalog #: USNM 1606824 <br>Year: 2019 <br>DIN: 1.7 <br>Conc: 353\",\"Catalog #: USNM 1740390 <br>Year: 2019 <br>DIN: 2.4 <br>Conc: 291\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(253,231,37,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(253,231,37,1)\"}},\"hoveron\":\"points\",\"name\":\"Modern\",\"legendgroup\":\"Modern\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.78800172823481263,3.5234137631114573],\"y\":[13.33,13.33],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283104,\"r\":7.3059360730593621,\"b\":40.182648401826491,\"l\":43.105022831050235},\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.78800172823481263,3.5234137631114573],\"tickmode\":\"array\",\"ticktext\":[\"1.0\",\"1.5\",\"2.0\",\"2.5\",\"3.0\",\"3.5\"],\"tickvals\":[1,1.5,2,2.5,3,3.5],\"categoryorder\":\"array\",\"categoryarray\":[\"1.0\",\"1.5\",\"2.0\",\"2.5\",\"3.0\",\"3.5\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-45,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"DNA Integrity Number (DIN)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-18.7515,428.32150000000001],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"100\",\"200\",\"300\",\"400\"],\"tickvals\":[0,100,200,300,400],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"100\",\"200\",\"300\",\"400\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Concentration (ng/uL)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"title\":{\"text\":\"Collection.Age\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"fe82bd77d02\":{\"x\":{},\"y\":{},\"colour\":{},\"text\":{},\"type\":\"scatter\"},\"fe871925989\":{\"yintercept\":{}}},\"cur_data\":\"fe82bd77d02\",\"visdat\":{\"fe82bd77d02\":[\"function (y) \",\"x\"],\"fe871925989\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n\n```{.r .cell-code}\nggplotly(p3, tooltip = \"text\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-a4d1bc5c86d7b05814b6\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-a4d1bc5c86d7b05814b6\">{\"x\":{\"data\":[{\"x\":[1.2157199719222263,1.3613673012470826,1.0172809855081142,1.1690909180790185,1.7577706996118649,null,1.2242492478108034,1.0950219922233373,null,null,null],\"y\":[73.819999999999993,82.129999999999995,86.489999999999995,86.099999999999994,91.680000000000007,63.149999999999999,61.630000000000003,62.25,null,null,null],\"text\":[\"Catalog #: USNM 50603 <br>Year: 1912 <br>DIN: 1 <br>% >300kb: 73.82\",\"Catalog #: USNM 19054 <br>Year: 1898 <br>DIN: 1.2 <br>% >300kb: 82.13\",\"Catalog #: USNM 42137 <br>Year: 1898 <br>DIN: 1.1 <br>% >300kb: 86.49\",\"Catalog #: USNM 14399 <br>Year: 1886 <br>DIN: 1.2 <br>% >300kb: 86.1\",\"Catalog #: USNM 50368 <br>Year: 1880 <br>DIN: 1.7 <br>% >300kb: 91.68\",\"Catalog #: USNM 14366 <br>Year: 1886 <br>DIN: NA <br>% >300kb: 63.15\",\"Catalog #: USNM 52295 <br>Year: 1912 <br>DIN: 1 <br>% >300kb: 61.63\",\"Catalog #: USNM 1180630 <br>Year: 1912 <br>DIN: 1 <br>% >300kb: 62.25\",\"Catalog #: USNM 1207569 <br>Year: 1886 <br>DIN: NA <br>% >300kb: NA\",\"Catalog #: USNM 14366 <br>Year: 1886 <br>DIN: NA <br>% >300kb: NA\",\"Catalog #: USNM 52026 <br>Year: 1898 <br>DIN: NA <br>% >300kb: NA\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(68,1,84,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(68,1,84,1)\"}},\"hoveron\":\"points\",\"name\":\"pre-1920\",\"legendgroup\":\"pre-1920\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.6154317396925761,1.6906461277976632,1.6157524374313652,2.1395614336710422,2.3240596935153008,1.2095204014563934,1.47092098868452,1.1658670241711662,1.3994570015929639,1.0504378925077618,1.2984564051497727],\"y\":[93,92.459999999999994,94.719999999999999,94.200000000000003,93.799999999999997,71.129999999999995,89.900000000000006,87.120000000000005,89.230000000000004,88.780000000000001,86.459999999999994],\"text\":[\"Catalog #: USNM 51857 <br>Year: 1960 <br>DIN: 1.4 <br>% >300kb: 93\",\"Catalog #: USNM 51859 <br>Year: 1960 <br>DIN: 1.5 <br>% >300kb: 92.46\",\"Catalog #: USNM 51861 <br>Year: 1960 <br>DIN: 1.7 <br>% >300kb: 94.72\",\"Catalog #: USNM 51892 <br>Year: 1960 <br>DIN: 1.9 <br>% >300kb: 94.2\",\"Catalog #: USNM 51732 <br>Year: 1960 <br>DIN: 2.1 <br>% >300kb: 93.8\",\"Catalog #: USNM 51730 <br>Year: 1960 <br>DIN: 1.1 <br>% >300kb: 71.13\",\"Catalog #: USNM 51728 <br>Year: 1960 <br>DIN: 1.4 <br>% >300kb: 89.9\",\"Catalog #: USNM 51727 <br>Year: 1960 <br>DIN: 1.3 <br>% >300kb: 87.12\",\"Catalog #: USNM 51729 <br>Year: 1960 <br>DIN: 1.5 <br>% >300kb: 89.23\",\"Catalog #: USNM 51858 <br>Year: 1960 <br>DIN: 1.3 <br>% >300kb: 88.78\",\"Catalog #: USNM 51860 <br>Year: 1960 <br>DIN: 1.4 <br>% >300kb: 86.46\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(33,144,140,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(33,144,140,1)\"}},\"hoveron\":\"points\",\"name\":\"1960s-70s\",\"legendgroup\":\"1960s-70s\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[3.0059541506692766,2.9486249444540591,3.0672369357896967,2.9626300981268288,3.2641725536435842,2.0320029030321165,2.798144445591606,2.0445038355654104,1.7091592324897646,2.2104786594631149],\"y\":[96.340000000000003,96.890000000000001,97.400000000000006,96.989999999999995,97.209999999999994,93.569999999999993,93.489999999999995,89.980000000000004,90.799999999999997,96.829999999999998],\"text\":[\"Catalog #: USNM 100609 <br>Year: 2000 <br>DIN: 2.9 <br>% >300kb: 96.34\",\"Catalog #: USNM 1740407 <br>Year: 2019 <br>DIN: 3.1 <br>% >300kb: 96.89\",\"Catalog #: USNM 1740363 <br>Year: 2019 <br>DIN: 3.3 <br>% >300kb: 97.4\",\"Catalog #: USNM 1740336 <br>Year: 2019 <br>DIN: 3.1 <br>% >300kb: 96.99\",\"Catalog #: USNM 1606826 <br>Year: 2019 <br>DIN: 3.4 <br>% >300kb: 97.21\",\"Catalog #: USNM 100610 <br>Year: 2000 <br>DIN: 1.9 <br>% >300kb: 93.57\",\"Catalog #: USNM 1007393 <br>Year: 2000 <br>DIN: 2.8 <br>% >300kb: 93.49\",\"Catalog #: USNM 1018355 <br>Year: 2002 <br>DIN: 1.8 <br>% >300kb: 89.98\",\"Catalog #: USNM 1606824 <br>Year: 2019 <br>DIN: 1.7 <br>% >300kb: 90.8\",\"Catalog #: USNM 1740390 <br>Year: 2019 <br>DIN: 2.4 <br>% >300kb: 96.83\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(253,231,37,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(253,231,37,1)\"}},\"hoveron\":\"points\",\"name\":\"Modern\",\"legendgroup\":\"Modern\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.90493640710134071,3.3765171320503575],\"y\":[13.33,13.33],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283104,\"r\":7.3059360730593621,\"b\":40.182648401826491,\"l\":43.105022831050235},\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.90493640710134071,3.3765171320503575],\"tickmode\":\"array\",\"ticktext\":[\"1.0\",\"1.5\",\"2.0\",\"2.5\",\"3.0\"],\"tickvals\":[1,1.5,2,2.5,3],\"categoryorder\":\"array\",\"categoryarray\":[\"1.0\",\"1.5\",\"2.0\",\"2.5\",\"3.0\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-45,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"DNA Integrity Number (DIN)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[9.1265000000000001,101.60350000000001],\"tickmode\":\"array\",\"ticktext\":[\"25\",\"50\",\"75\",\"100\"],\"tickvals\":[25,50,75,100],\"categoryorder\":\"array\",\"categoryarray\":[\"25\",\"50\",\"75\",\"100\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Percent of reads >300kb\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"title\":{\"text\":\"Collection.Age\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"fe842c72b6a\":{\"x\":{},\"y\":{},\"colour\":{},\"text\":{},\"type\":\"scatter\"},\"fe8589d5364\":{\"yintercept\":{}}},\"cur_data\":\"fe842c72b6a\",\"visdat\":{\"fe842c72b6a\":[\"function (y) \",\"x\"],\"fe8589d5364\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n## Sample selection\n\nBased on the above results, I can pick which samples are most suited for sequencing, considering DNA concentration (as a proxy for total DNA available) and DNA integrity. I'm not sure whether % \\>300bp reads or DIN is the most appropriate measure of DNA integrity here, but they're highly correlated. I want n=5 for each of my three collection periods.\n\n[**Modern (\\<25 yo)**]{.underline}\\\nUSNM 1606826\\\nUSNM 1740336\\\nUSNM 1740363\\\nUSNM 100609\\\nUSNM 1740407\n\n[**Mid-age (1960s-1970s):**]{.underline}\\\nUSNM 51732\\\nUSNM 51892\\\nUSNM 51861\\\nUSNM 51857\\\nUSNM 51859\n\n[**Historic (\\>100 yo):**]{.underline}\\\nUSNM 50368\\\nUSNM 14399\\\nUSNM 42137\\\nUSNM 19054\\\nUSNM 50603\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected <- c(\"USNM 1606826\", \"USNM 1740336\", \"USNM 1740363\", \"USNM 100609\", \"USNM 1740407\", \"USNM 51732\", \"USNM 51892\", \"USNM 51861\", \"USNM 51857\", \"USNM 51859\", \"USNM 50368\", \"USNM 14399\", \"USNM 42137\", \"USNM 19054\", \"USNM 50603\")\n\nconc$Selection <- ifelse(conc$Catalog.Number %in% selected, \"yes\", \"no\")\n\np21 <- ggplot(conc, aes(x=Tapestation.Perc.300up, \n                       y=Tapestation.Conc.ngul, \n                       color = Collection.Age,\n                       shape=Selection,\n                       text = paste(\"Catalog #:\", Catalog.Number,\n                                    \"<br>Year:\", Year.Collected,\n                                    \"<br>% >300kb:\", Tapestation.Perc.300up,\n                                    \"<br>Conc:\", Tapestation.Conc.ngul))) +\n  geom_jitter(size = 2, width = 0.25, height = 0) +\n  geom_hline(yintercept = 13.33, color = 'black') +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +\n  xlab(\"Percent of reads >300kb\") +\n  ylab(\"Concentration (ng/uL)\")\n\np22 <- ggplot(conc, aes(x=Tapestation.DIN, \n                       y=Tapestation.Conc.ngul, \n                       color=Collection.Age,\n                       shape=Selection,\n                       text = paste(\"Catalog #:\", Catalog.Number,\n                                    \"<br>Year:\", Year.Collected,\n                                    \"<br>DIN:\", Tapestation.DIN,\n                                    \"<br>Conc:\", Tapestation.Conc.ngul))) +\n  geom_jitter(size = 2, width = 0.25, height = 0) +\n  geom_hline(yintercept = 13.33, color = 'black') +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +\n  xlab(\"DNA Integrity Number (DIN)\") +\n  ylab(\"Concentration (ng/uL)\")\n\nggplotly(p21, tooltip = \"text\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-51f403f6004919c0a250\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-51f403f6004919c0a250\">{\"x\":{\"data\":[{\"x\":[63.001645788876338,61.621655097925107,62.187695567146875,null,null,null],\"y\":[1.5700000000000001,19.899999999999999,4.3300000000000001,null,null,null],\"text\":[\"Catalog #: USNM 14366 <br>Year: 1886 <br>% >300kb: 63.15 <br>Conc: 1.57\",\"Catalog #: USNM 52295 <br>Year: 1912 <br>% >300kb: 61.63 <br>Conc: 19.9\",\"Catalog #: USNM 1180630 <br>Year: 1912 <br>% >300kb: 62.25 <br>Conc: 4.33\",\"Catalog #: USNM 1207569 <br>Year: 1886 <br>% >300kb: NA <br>Conc: NA\",\"Catalog #: USNM 14366 <br>Year: 1886 <br>% >300kb: NA <br>Conc: NA\",\"Catalog #: USNM 52026 <br>Year: 1898 <br>% >300kb: NA <br>Conc: NA\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(68,1,84,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(68,1,84,1)\"}},\"hoveron\":\"points\",\"name\":\"(pre-1920,no)\",\"legendgroup\":\"(pre-1920,no)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[73.850599016346962,82.203256700532506,86.677047198996874,85.999920710246073,91.554475349206484],\"y\":[42.399999999999999,21.600000000000001,46.299999999999997,100,68.299999999999997],\"text\":[\"Catalog #: USNM 50603 <br>Year: 1912 <br>% >300kb: 73.82 <br>Conc: 42.4\",\"Catalog #: USNM 19054 <br>Year: 1898 <br>% >300kb: 82.13 <br>Conc: 21.6\",\"Catalog #: USNM 42137 <br>Year: 1898 <br>% >300kb: 86.49 <br>Conc: 46.3\",\"Catalog #: USNM 14399 <br>Year: 1886 <br>% >300kb: 86.1 <br>Conc: 100\",\"Catalog #: USNM 50368 <br>Year: 1880 <br>% >300kb: 91.68 <br>Conc: 68.3\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(68,1,84,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"triangle-up\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(68,1,84,1)\"}},\"hoveron\":\"points\",\"name\":\"(pre-1920,yes)\",\"legendgroup\":\"(pre-1920,yes)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[70.894997844351451,89.910125726345001,86.928639987022621,89.363243454969492,88.546716131940485,86.340398265435354],\"y\":[59.600000000000001,23.699999999999999,15.300000000000001,18.699999999999999,24.199999999999999,15.6],\"text\":[\"Catalog #: USNM 51730 <br>Year: 1960 <br>% >300kb: 71.13 <br>Conc: 59.6\",\"Catalog #: USNM 51728 <br>Year: 1960 <br>% >300kb: 89.9 <br>Conc: 23.7\",\"Catalog #: USNM 51727 <br>Year: 1960 <br>% >300kb: 87.12 <br>Conc: 15.3\",\"Catalog #: USNM 51729 <br>Year: 1960 <br>% >300kb: 89.23 <br>Conc: 18.7\",\"Catalog #: USNM 51858 <br>Year: 1960 <br>% >300kb: 88.78 <br>Conc: 24.2\",\"Catalog #: USNM 51860 <br>Year: 1960 <br>% >300kb: 86.46 <br>Conc: 15.6\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(33,144,140,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(33,144,140,1)\"}},\"hoveron\":\"points\",\"name\":\"(1960s-70s,no)\",\"legendgroup\":\"(1960s-70s,no)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[92.989193727262318,92.273932652468787,94.630506939399055,94.44471626384184,93.692842503963035],\"y\":[109,117,94.099999999999994,137,157],\"text\":[\"Catalog #: USNM 51857 <br>Year: 1960 <br>% >300kb: 93 <br>Conc: 109\",\"Catalog #: USNM 51859 <br>Year: 1960 <br>% >300kb: 92.46 <br>Conc: 117\",\"Catalog #: USNM 51861 <br>Year: 1960 <br>% >300kb: 94.72 <br>Conc: 94.1\",\"Catalog #: USNM 51892 <br>Year: 1960 <br>% >300kb: 94.2 <br>Conc: 137\",\"Catalog #: USNM 51732 <br>Year: 1960 <br>% >300kb: 93.8 <br>Conc: 157\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(33,144,140,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"triangle-up\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(33,144,140,1)\"}},\"hoveron\":\"points\",\"name\":\"(1960s-70s,yes)\",\"legendgroup\":\"(1960s-70s,yes)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[93.462569649382488,93.543474427433679,90.023544492684309,90.877390789869239,96.756241603563538],\"y\":[164,218,115,353,291],\"text\":[\"Catalog #: USNM 100610 <br>Year: 2000 <br>% >300kb: 93.57 <br>Conc: 164\",\"Catalog #: USNM 1007393 <br>Year: 2000 <br>% >300kb: 93.49 <br>Conc: 218\",\"Catalog #: USNM 1018355 <br>Year: 2002 <br>% >300kb: 89.98 <br>Conc: 115\",\"Catalog #: USNM 1606824 <br>Year: 2019 <br>% >300kb: 90.8 <br>Conc: 353\",\"Catalog #: USNM 1740390 <br>Year: 2019 <br>% >300kb: 96.83 <br>Conc: 291\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(253,231,37,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(253,231,37,1)\"}},\"hoveron\":\"points\",\"name\":\"(Modern,no)\",\"legendgroup\":\"(Modern,no)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[96.56760649712291,96.796032006721944,97.524553227680741,96.935103566045868,97.034496142566198],\"y\":[261,260,343,368,408],\"text\":[\"Catalog #: USNM 100609 <br>Year: 2000 <br>% >300kb: 96.34 <br>Conc: 261\",\"Catalog #: USNM 1740407 <br>Year: 2019 <br>% >300kb: 96.89 <br>Conc: 260\",\"Catalog #: USNM 1740363 <br>Year: 2019 <br>% >300kb: 97.4 <br>Conc: 343\",\"Catalog #: USNM 1740336 <br>Year: 2019 <br>% >300kb: 96.99 <br>Conc: 368\",\"Catalog #: USNM 1606826 <br>Year: 2019 <br>% >300kb: 97.21 <br>Conc: 408\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(253,231,37,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"triangle-up\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(253,231,37,1)\"}},\"hoveron\":\"points\",\"name\":\"(Modern,yes)\",\"legendgroup\":\"(Modern,yes)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[59.826510191437322,99.319698134168519],\"y\":[13.33,13.33],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283104,\"r\":7.3059360730593621,\"b\":40.182648401826491,\"l\":43.105022831050235},\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[59.826510191437322,99.319698134168519],\"tickmode\":\"array\",\"ticktext\":[\"60\",\"70\",\"80\",\"90\"],\"tickvals\":[60,70,80,90],\"categoryorder\":\"array\",\"categoryarray\":[\"60\",\"70\",\"80\",\"90\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-45,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Percent of reads >300kb\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-18.7515,428.32150000000001],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"100\",\"200\",\"300\",\"400\"],\"tickvals\":[0,100,200,300,400],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"100\",\"200\",\"300\",\"400\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Concentration (ng/uL)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"title\":{\"text\":\"Collection.Age<br />Selection\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"fe83e57349d\":{\"x\":{},\"y\":{},\"colour\":{},\"shape\":{},\"text\":{},\"type\":\"scatter\"},\"fe82211679f\":{\"yintercept\":{}}},\"cur_data\":\"fe83e57349d\",\"visdat\":{\"fe83e57349d\":[\"function (y) \",\"x\"],\"fe82211679f\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n\n```{.r .cell-code}\nggplotly(p22, tooltip = \"text\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-62b6a1e06bfc4f1bb199\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-62b6a1e06bfc4f1bb199\">{\"x\":{\"data\":[{\"x\":[null,0.81284771708305925,1.0458329378161579,null,null,null],\"y\":[1.5700000000000001,19.899999999999999,4.3300000000000001,null,null,null],\"text\":[\"Catalog #: USNM 14366 <br>Year: 1886 <br>DIN: NA <br>Conc: 1.57\",\"Catalog #: USNM 52295 <br>Year: 1912 <br>DIN: 1 <br>Conc: 19.9\",\"Catalog #: USNM 1180630 <br>Year: 1912 <br>DIN: 1 <br>Conc: 4.33\",\"Catalog #: USNM 1207569 <br>Year: 1886 <br>DIN: NA <br>Conc: NA\",\"Catalog #: USNM 14366 <br>Year: 1886 <br>DIN: NA <br>Conc: NA\",\"Catalog #: USNM 52026 <br>Year: 1898 <br>DIN: NA <br>Conc: NA\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(68,1,84,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(68,1,84,1)\"}},\"hoveron\":\"points\",\"name\":\"(pre-1920,no)\",\"legendgroup\":\"(pre-1920,no)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.1640808769734576,1.0909489009529352,1.3232405550312252,1.4248660054756328,1.6668367927661165],\"y\":[42.399999999999999,21.600000000000001,46.299999999999997,100,68.299999999999997],\"text\":[\"Catalog #: USNM 50603 <br>Year: 1912 <br>DIN: 1 <br>Conc: 42.4\",\"Catalog #: USNM 19054 <br>Year: 1898 <br>DIN: 1.2 <br>Conc: 21.6\",\"Catalog #: USNM 42137 <br>Year: 1898 <br>DIN: 1.1 <br>Conc: 46.3\",\"Catalog #: USNM 14399 <br>Year: 1886 <br>DIN: 1.2 <br>Conc: 100\",\"Catalog #: USNM 50368 <br>Year: 1880 <br>DIN: 1.7 <br>Conc: 68.3\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(68,1,84,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"triangle-up\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(68,1,84,1)\"}},\"hoveron\":\"points\",\"name\":\"(pre-1920,yes)\",\"legendgroup\":\"(pre-1920,yes)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.0669131173286588,1.5055823258357122,1.3040237794164569,1.5157553397584707,1.3512270715553314,1.3313208325766026],\"y\":[59.600000000000001,23.699999999999999,15.300000000000001,18.699999999999999,24.199999999999999,15.6],\"text\":[\"Catalog #: USNM 51730 <br>Year: 1960 <br>DIN: 1.1 <br>Conc: 59.6\",\"Catalog #: USNM 51728 <br>Year: 1960 <br>DIN: 1.4 <br>Conc: 23.7\",\"Catalog #: USNM 51727 <br>Year: 1960 <br>DIN: 1.3 <br>Conc: 15.3\",\"Catalog #: USNM 51729 <br>Year: 1960 <br>DIN: 1.5 <br>Conc: 18.7\",\"Catalog #: USNM 51858 <br>Year: 1960 <br>DIN: 1.3 <br>Conc: 24.2\",\"Catalog #: USNM 51860 <br>Year: 1960 <br>DIN: 1.4 <br>Conc: 15.6\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(33,144,140,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(33,144,140,1)\"}},\"hoveron\":\"points\",\"name\":\"(1960s-70s,no)\",\"legendgroup\":\"(1960s-70s,no)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.3405534709803759,1.6815517860231921,1.9293054704787209,1.9612320373766123,2.213725332194008],\"y\":[109,117,94.099999999999994,137,157],\"text\":[\"Catalog #: USNM 51857 <br>Year: 1960 <br>DIN: 1.4 <br>Conc: 109\",\"Catalog #: USNM 51859 <br>Year: 1960 <br>DIN: 1.5 <br>Conc: 117\",\"Catalog #: USNM 51861 <br>Year: 1960 <br>DIN: 1.7 <br>Conc: 94.1\",\"Catalog #: USNM 51892 <br>Year: 1960 <br>DIN: 1.9 <br>Conc: 137\",\"Catalog #: USNM 51732 <br>Year: 1960 <br>DIN: 2.1 <br>Conc: 157\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(33,144,140,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"triangle-up\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(33,144,140,1)\"}},\"hoveron\":\"points\",\"name\":\"(1960s-70s,yes)\",\"legendgroup\":\"(1960s-70s,yes)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.7976848603924735,2.7262678814120589,1.9466938335215673,1.554173328843899,2.44222590662539],\"y\":[164,218,115,353,291],\"text\":[\"Catalog #: USNM 100610 <br>Year: 2000 <br>DIN: 1.9 <br>Conc: 164\",\"Catalog #: USNM 1007393 <br>Year: 2000 <br>DIN: 2.8 <br>Conc: 218\",\"Catalog #: USNM 1018355 <br>Year: 2002 <br>DIN: 1.8 <br>Conc: 115\",\"Catalog #: USNM 1606824 <br>Year: 2019 <br>DIN: 1.7 <br>Conc: 353\",\"Catalog #: USNM 1740390 <br>Year: 2019 <br>DIN: 2.4 <br>Conc: 291\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(253,231,37,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(253,231,37,1)\"}},\"hoveron\":\"points\",\"name\":\"(Modern,no)\",\"legendgroup\":\"(Modern,no)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2.8873022927204146,2.9990035434253515,3.0954422042239456,3.0647902443539352,3.5651063802419229],\"y\":[261,260,343,368,408],\"text\":[\"Catalog #: USNM 100609 <br>Year: 2000 <br>DIN: 2.9 <br>Conc: 261\",\"Catalog #: USNM 1740407 <br>Year: 2019 <br>DIN: 3.1 <br>Conc: 260\",\"Catalog #: USNM 1740363 <br>Year: 2019 <br>DIN: 3.3 <br>Conc: 343\",\"Catalog #: USNM 1740336 <br>Year: 2019 <br>DIN: 3.1 <br>Conc: 368\",\"Catalog #: USNM 1606826 <br>Year: 2019 <br>DIN: 3.4 <br>Conc: 408\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(253,231,37,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"triangle-up\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(253,231,37,1)\"}},\"hoveron\":\"points\",\"name\":\"(Modern,yes)\",\"legendgroup\":\"(Modern,yes)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.67523478392511604,3.7027193133998662],\"y\":[13.33,13.33],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283104,\"r\":7.3059360730593621,\"b\":40.182648401826491,\"l\":43.105022831050235},\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.67523478392511604,3.7027193133998662],\"tickmode\":\"array\",\"ticktext\":[\"1\",\"2\",\"3\"],\"tickvals\":[1,2,3],\"categoryorder\":\"array\",\"categoryarray\":[\"1\",\"2\",\"3\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-45,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"DNA Integrity Number (DIN)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-18.7515,428.32150000000001],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"100\",\"200\",\"300\",\"400\"],\"tickvals\":[0,100,200,300,400],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"100\",\"200\",\"300\",\"400\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Concentration (ng/uL)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"title\":{\"text\":\"Collection.Age<br />Selection\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"fe840ed475c\":{\"x\":{},\"y\":{},\"colour\":{},\"shape\":{},\"text\":{},\"type\":\"scatter\"},\"fe8323f507c\":{\"yintercept\":{}}},\"cur_data\":\"fe840ed475c\",\"visdat\":{\"fe840ed475c\":[\"function (y) \",\"x\"],\"fe8323f507c\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\r\n<script src=\"../../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\r\n<script src=\"../../../site_libs/plotly-binding-4.10.4/plotly.js\"></script>\r\n<script src=\"../../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\r\n<script src=\"../../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\r\n<link href=\"../../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\r\n<script src=\"../../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\r\n<link href=\"../../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\r\n<script src=\"../../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}