---
title: "Lit Review and Science Hour"
author: "Kathleen Durkin"
date: "2023-10-06"
categories:
    - onboarding
    - lit review
---

Completed an additional employee training and went over my lit review questions (see Oct.5 entry) with Steven. Also github-issued Sam about getting added to Raven.

[Questions:]{.underline}

General

-   I read that both cytosine and adenine can be methylated, but every paper I've read so far studying methylation only looked at methylation of cytosine -- is there a reason adenine methylation is not commonly studied?

    -   A: adenine is only methylated in certain taxa (e.g. bacteria), and isn't methylated in marine inverts

-   Is all methylation (in gamete cells) heritable/potentially heritable? Do we know? If not, do we know why/what determines heritability? What about other forms of epigenetic modification?

    -   Similarly, what proportion of methylation (or epigenetic modification in general) affects gamete cells?

    -   A: Differs among taxa. We have secondary evidence that it is in marine inverts. For taxa where there's more evidence, modification has to happen during early developmental stages of gonads (presumably to alter the gamete cells). A lot of it is unknown though (similar for other forms of modification e.g. histone modification)

George et al. 2023 (Triploid Pacific oysters exhibit stress response dysregulation...)

-   George et al. 2023 studied polyploidy in oysters because of its common use in oyster aquaculture -- does polyploidy have any potential conservation applications, particularly in eukaryotes, for whom ployploidy is often better tolerated? One scenario I can think of is intentional hybridization of two species to selectively breed a more resilient population -- since polyploidy is more common in hybrids, may be important to understand its impacts. I also know polyploidy sometimes happens in corals (especially Caribbean corals), which can reproduce asexually fairly easily. (Need to read related paper Stephens et al. 2023 -- w/ Putnam and Bhattacharya!)

    -   A: Since polyploidy reduces breeding potential so could be useful in conservation. But don;t have any information on relationship between polyploidy and methylation or the mechanisms of how polyploidy affects methylation

-   Confused about a couple aspects of the experimental setup:

    -   Stated that lab obtained 500 oysters for the experiment, but then states that the starting sample size of each of the six treatments (2 controls, 2 single stressor, 2 multiple stressors) was 112, which adds to way over 500 oysters

        -   A:

    -   For the multiple stressors treatment, why was aerial exposure not repeated multiple times (since low tide happens on a regular daily schedule, not just once during a given warming event)?

        -   A: Don't want to go overboard and kill all the oysters, so start out trying with less stressful stress conditions. Want to understand more than just the death outcome.

-   In Results, why is survival probability not the direct inverse of mortality?

    -   A: doesn't know, maybe check supplemental materials or ask in Slack

-   I think I noticed some typos... do you want to know about them or just leave it be?

Putnam et al. 2023 (Dynamic DNA methylation contributes to carryover effects...)

-   In the results section I saw that shell area was used as a proxy for shell size -- is it assumed that shell *thickness* remains fairly constant? Do we know this will hold during acidification? Also, are shell size and body mass tightly correlated? (I would assume so, but it would be interesting if acidic conditions messed with that relationship)

    -   A: Not assumed, but it wasn't measured. Emma Tidman paper looks at effect of acidification on various measures of shell strength/size.

    -   A: Emma also looked at body mass/tissue impacts of acidification (but yes, there is generally a correlation between shell size and body mass)

-   In Fig.3 I'm a little confused about the y-axes of 3c and 3d -- what is the baseline (the "1") for these relative size values? It doesn't seem like it could be original size (as in a and b)

    -   A: check supplemental

-   What is the difference between differentially methylated regions (DMRs) and differentially methylated genes (DMGs)? Are DMRs just methylation of non-coding DNA (e.g. introns)?

    -   A: Regions are just more broad than genes (so regions could contain genes). The scale (in terms of number of bp) goes loci -\> genes -\> regions.

-   I have no idea what's going on in figure 4 :(

    -   A: each cell represents gene and the z-score is basically showing a heatmap of gene expression. The "tree" looking thing is just showing clustering of individuals based on expression level.

-   or figure 5

    -   A: Steven is also kind of confused about this rn, but check supplementals for more

-   What are DEGs (pg12)? Also, are CpGs just cytosine/guanine pairs?

    -   DEG=Differentially expressed gene (rather than differentially methylated), and yes, CpGs are cytosine/guanine pairs
