---
title: "RStudio/Bash Struggles (cont.)"
author: "Kathleen Durkin"
date: "2023-10-12"
categories:
    - onboarding
    - project-cod-temperature
---

I think I may have fixed the issue running bash code chunks in Rmd files! Included the following:

```{r setup, include=T}
knitr::opts_chunk$set(engine.path=list(bash='C:/Program Files/Git/git-bash.exe'))
```

And now, while I still don't seem to get any output when I try to run individual code chunks by pressing the "play" button in the top right corner, knitting the document works! I still haven't figured out how to permanently set the default shell script for running bash code chunks from Rmd files (checking default shell using "Sys.which("bash")" from the console still returns "C::\\\\WINDOWS\\\\SYSTEM32\\\\bash.exe" aka WSL), so for now I guess I'll just have to include that YAML block in any Rmd file I'm working in.

Started working on cod temp/size data analysis assigned by Steven but haven't been able to push to the lab Github repo (project-cod-temperature) bc, while I successfully cloned the repo to RStudio, I haven't been able to connect them so I'm able to push changes back to it. Will ask about it during Science Hour tomorrow
