---
title: "SICB Registration, Reviewing October Goals"
author: "Kathleen Durkin"
date: "2023-11-01"
categories:
    - misc.
tags:
    - SICB
---

In the spirit of yesterday's holiday, I completed the scary task of registering for SICB out-of-pocket and then submitting the reimbursement request 🥴. This afternoon I also attended a workshop on making research presentations and slides more communicative and accessible, led by Tim.

With the start of a new month, I also wanted to review progress on the goals I set for myself for the last bit of October:

**✓ Successfully run a blast search in Raven.** Completed! I was able to run through Steven's full code for blasting and annotating a cod transcriptome, and I'll hopefully be able to glean enough from his code to understand how to write my own in the future.

**✗ Read up on the cod temperature/growth project.** Not yet 😕.

**✓ Read up on E5 coral project and start to get settled in it.** Getting there! I've started reading up on ncRNAs and, while I had to miss the last two meetings of the E5 group because of a midterm and a function required for one of my scholarships, I'll be meeting with the working group tomorrow morning.

**✓ Get registered for SICB.** Completed!

Also, as seen above, I've figured out how to add emojis to my lab notebook -- gamechanger!
