---
title: "April 2025, Daily Log"
author: "Kathleen Durkin"
date: "last-modified"
categories: ["monthly goals"]
format:
  html:
    code-fold: true
execute:
  warning: false
---

## 30 April 2025

#### Wednesday

## 29 April 2025

#### Tuesday

## 28 April 2025

#### Monday

## 25 April 2025

#### Friday

## 24 April 2025

#### Thursday

## 23 April 2025

#### Wednesday

## 22 April 2025

#### Tuesday

## 21 April 2025

#### Monday

## 18 April 2025

#### Friday

## 17 April 2025

#### Thursday

## 16 April 2025

#### Wednesday

## 15 April 2025

#### Tuesday

## 14 April 2025

#### Monday

-   SWED103

-   looking into different housing options for 3 month short term lease/sublease in DC, for Smithsonian fellowship

## 11 April 2025

#### Friday

## 10 April 2025

#### Thursday

## 09 April 2025

#### Wednesday

## 08 April 2025

#### Tuesday

## 07 April 2025

#### Monday

## 04 April 2025

#### Friday

-   2 h -- working on thesis proposal

## 03 April 2025

#### Thursday

-   1 hr -- SWED103

-   1 hr -- FISH546

-   0.5 -- quick meetings w Mark and Sam to talk about SIFP/GRFP funding

-   1.5 hr -- Lab meeting:

```         
-   Schedule annual meting w Steven

-   ~~reschedule weekly/biweekly meetings w Steven~~

-   ~~Need to be submitting monthly reports for RA position (see form in handbook)~~

-   ~~Ping Ariana for meeting about ML work~~

-   ~~check lab website to make sure I've added my recent presentations/papers~~

-   add pOverA filtering to ML

-   ~~Did some last additions and polishing to the Undergraduate Guide for the lab website~~
```

-   1 hr -- FISH546 finished assignment 1 and week 1 questions

-   1.5 hr -- SWED103 hmwk, discussion posts, weekly quiz

## 02 April 2025

#### Wednesday

## 01 April 2025

#### Tuesday

-   1 hr -- SWED103 class

-   1.5 hr -- FISH546 class

-   1 hr -- misc admin stuff. paid tuition, emailed w Andrea, slack messages, etc.

-   5 hr -- working with timeseries stuff, see posts: [timeseries ML pt.2](../../projects/E5_coral/2025_04_01_timeseries_ML%202.qmd), [timeseries FA/FE](../../projects/E5_coral/2025_04_01_timeseries_FA_FE.qmd)
