---
title: "April 2025, Monthly Goals"
author: "Kathleen Durkin"
date: "2025-04-02"
categories: ["monthly goals"]
format:
  html
---

## April Goals

-   Wrap up E5 deep dive tasks

-   complete draft for E5 deep dive paper

-   Complete a workable EPIMAR presentation

-   Complete MS thesis proposal

-   Set another committee meeting to review progress, summer plans, send proposal draft, etc.

-   Plan for SIFP summer fellowship

    -   ~~Set dates~~

    -   ~~Figure out where research funding will be coming from (Andrea? Steven? both?), what the \$ amount needed will be, etc.~~

    -   Set timeline (due dates for sample select, QCing, prep, sequencing, data analysis, etc.)

    -   Figure out where sequencing will be done (does LAB have own Promethion or does it need to be out-of-house?) and what approximate cost will be

    -   ~~Complete Smithsonian onboarding (security check, getting set up for ID, etc.)~~

    -   Look into housing (may need to wait till May for better availability)

    -   ~~Figure out how SIFP living stipend will merge with SAFS funding/insurance~~

-   Reminder: Submit [RA reporting form](https://docs.google.com/forms/d/e/1FAIpQLSd162whQvdjHRkhDHJJf9A59VhLCjJEqaZ7VqKYaixx7rYnFg/viewform) at end of month (can enter "NSF" in the Funding Source section)
