---
title: "January 2025, Monthly Goals"
author: "Kathleen Durkin"
date: "2025-01-09"
categories: ["monthly goals"]
format:
  html
---

## January goals

-   **Log activities daily in Lab Notebook.**\
    Last quarter I got overwhelmed with work and stopped posting my daily activities in my lab notebook. I want to reinstate that habit!

-   **Log all data analysis work (e.g. running a WGCNA) in dedicated post in appropriate project page.**\
    Similar to the first goal, I've been relying on Github to log all the analysis work I've been doing. That work should also be detailed in my lab notebook.

-   **Spend maximum 50 hours/week working. Log daily hours in Lab Notebook.** \
    Last quarter, with the intensive TA position, grant applications, committee prep, and transitioning to E5 expression work/leadership, I worked a *lot*, and I was really burned out by the end of the quarter. I want to hold myself accountable to a more manageable work schedule this quarter. This time logging will begin my first week back from SICB (Monday, Jan 13). I expect my time breakdown to be roughly: \
    20hr/wk classes (SWED 101, FISH 513); 15hr/wk TAing (QSCI 381); 15hr/wk thesis work.\

## Overview of last few months

I failed to set goals or consistently log daily activities for the last several months, but here's an overview of what I got done last quarter:

-   Submitted completed GRFP application

-   Submitted completed SIFP application

-   Began work and leadership on E5 deep-dive-expression project

-   Began work on E5 time-series-molecular project

-   TA-ed my first class at UW (and learned a lot about the importance of making your TA work efficient)

-   Formed Master's committee and had first committee meeting

-   Presented E5 time-series-molecular work (specifically, coexpression of genes, miRNA, and lncRNA) at SICB -- my first in-person conference presentation!
