---
title: "January 2025, Daily Log"
author: "Kathleen Durkin"
date: "last-modified"
categories: ["monthly goals"]
format:
  html
---

## 31 January 2025

#### Friday

-   **0.5 hr** - prep for E5 meeting

-   **1 hr** -- E5 meeting

-   **1.5 hr** -- SWED102 class

-   **0.5 hr** -- QSCI381 ed discussion board responses, canvas inbox

-   **3 hr** -- talk with prospective student, Sydney, get lunch w her and lab, etc.

-   **0.5 hr** -- E5, add final tasks + person assignments to deep-dive-expression Github issues

-   **2 hr** -- SWED102 writing assignment

-   **0.5 hr** -- updating lab notebook and summing weekly hours

Daily total: **9.5 hr**

Weekly Overview:

|                 | Monday | Tuesday | Wednesday | Thursday | Friday  | TOTALS                 |
|-----------------|--------|---------|-----------|----------|---------|------------------------|
| **Classes**     | 1      | 1       | 3         | 5        | 3.5     | **13.5**               |
| **TAing**       | 8.5    | 3.5     | 4.5       | 0.5      | 0.5     | **17.5**               |
| **Thesis work** | 0      | 3.5     | 2         | 3.5      | 2.5     | **11.5**               |
| **Misc.**       | 0.5    | 1       | 0         | 2.5      | 3       | **7**                  |
| **TOTALS**      | **10** | **9**   | **9.5**   | **11.5** | **9.5** | [**49.5**]{.underline} |

As a reminder, one of my monthly goals is to work a ***maximum*** **of 50hr/wk**, with a rough time allocation of: **20hr/wk** classes (SWED 101, FISH 513); **15hr/wk** TAing (QSCI 381); **15hr/wk** thesis work.

I've realized that I didn't account for the miscellaneous time commitments that come with being in grad school (e.g. seminar, emails, etc.), so I decided to start tracking that as well.\
\
This week looks good! I (barely) stayed within the 50 hr limit, I was able to keep TA hours under 20 hr/week and increase time devoted to thesis work. The miscellaneous time commitments were a little high this week because of the prospective grad student, Sydney, who visited the department and lab this week.

## 30 January 2025

#### Thursday

Early start to the day to prep for FISH513 today and E5 tomorrow

-   **2 hr** -- brainstorming/project planning for E5 meeting tomorrow

-   **1 hr** -- SWED102 class

-   **2 hr** -- FISH513 lit review + slides creation for presentation today

-   **0.5 hr** -- QSCI381 weekly meeting

-   **0.5 hr** -- lunch/meeting visiting prospective grad students

-   **1 hr** -- lab meeting

-   **2 hr** -- FISH513

-   **0.5 hr** -- prep meeting w Steven for E5 meeting tomorrow

-   **2 hr** -- Seminar + TGIT + meeting/talking with prospective grad students

Daily total: **11.5 hr**

## 29 January 2025

#### Wednesday

-   **2.5 hr** -- QSCI381 finished grading Assignment 2 and posted grades. Somehow a couple section BD students managed to submit to Gradescope? Double checked assignment settings on other assignment's I've already created to ensure they're only viewable to BA and BB.

-   **1.5 hr** -- SWED102 class

-   **2 hr** -- QSCI381 office hours

-   **1.5 hr** -- misc. related to [EPIMAR 2025](../../projects/misc/2025_01_29_EPIMAR_budgeting.qmd)

-   **0.5 hr** -- notebook post and daily log updates

-   **1.5 hr** -- FISH513 compiling GCRMN and WoRMS info for presentation tomorrow, adding to slides

Daily total: **9.5 hr**

## 28 January 2025

#### Tuesday

Got to campus early to get some work done, but honestly just ended up reading a bunch of news articles about the Trump admin freezes of federal grant funding, updates on the NIH freeze, and updates of the NSF cancelling grant review panels, sooooooo

-   **1 hr** -- existential crisis about the trajectory of research, academia, higher education, and my own life/career under an administration that has repeatedly vowed to dismantle these very institutions

-   **1 hr** -- SWED102 class

-   **0.5 hr** -- QSCI381 checking/answering posts on Ed Discussion board

-   **3 hr** -- E5 work, looking for instances of an miRNA targeting genes that encode DNA methylation machinery (largely lit review + some coding)

-   **2hr** -- QSCI381 Lab

-   **0.5 hr** -- weekly meeting w Steven, focused on project planning for deep-dive expression work

-   **1 hr** -- QSCI381 creating helper doc for students on Multinomial Coefficient (posted to Canvas)

Daily total: **9 hours**

## 27 January 2025

#### Monday

-   **1 hr** -- SWED102 class

-   **2.5 hr** -- QSCI381 Lab prep (had to skim all of this week's course content, since I haven't used probability stuff in a while), setting up Module 5 Assignment and Lab pages

-   **2.5 hr** -- QSCI381 Lab

-   **3.5 hr** -- QSCI grading (50% done)

-   **0.5 hr** -- misc. (start-of-week read-throughs and responses for emails, Slack, Ed Discussion chat, etc.)

Daily total: **10 hours**

## 24 January 2025

#### Friday

## 23 January 2025

#### Thursday

-   \>2hrs spent on Dr appointment + travel today, so shorter work day today

-   **1 hr** -- SWED102 class

-   **2 hr** -- FSH513 class

-   **2 hr** -- SWED101 hw + study for test tomorrow

-   **1 hr** -- TGIT

Daily total: **6 hours**

## 22 January 2025

#### Wednesday

-   **1 hr** -- SWED102 class

-   **1 hr** -- SWED102 office hours to cover Week 1 material i missed while at SICB.

-   **0.5 hr** -- QSCI381 misc. (check new Ed Discussion posts, check Canvas inbox, discuss week's meeting items w Steven and Tsering)

-   **2.5 hr** -- QSCI381 office hours

-   **1.5 hr** -- lab stuff (read paper for lab meeting, helped Megan move some U cars from campus lot to FTR)

-   **1 hr** -- SWED102 hw/studying for friday exam

-   **1 hr** -- FSH513 reading

Daily total: **8.5 hr**

## 21 January 2025

#### Tuesday

-   **1 hr** -- SWED102 class

-   **1 hr** -- SWED102 weekly quiz, hw

-   **1.5 hr** -- QSCI381 grading (completed!)

-   **2.5 hr** -- QSCI381 Lab

-   **3 hr** -- QSCI381 miscellaneous (creating WI2025 versions thru Lab 6 and Assignment 6, created .Rmd templates for Assignments 3-5, corrected Assignment 3 page, created Lab 3 page, Creating Gradescope Submission Assignments for my studentd (thru Assignment 7), creating Gradescope templates thru Assignment 5, linking Canvas and Gradescope thru Assignment 5)

Daily total: **9 hr**

## 20 January 2025

#### Monday

MLK Day (technically a holiday)

-   **2 hr** -- QSCI381 (recorded lab video, answered a bunch of weekend emails and questions in Ed Discussion)

-   **2.5 hr** -- QSCI381 (graded Assignment 1 -- 84% done)

Daily total: **4.5 hr**

## 17 January 2025

#### Friday

-   **1.5 hr** -- E5 molecular biweekly meeting (notes [here](https://docs.google.com/document/d/1Fdd6xC9tJmAf9Iydcf3er-YwabKmwK3jGVw4ppfxfhM/edit?tab=t.0))

-   **1 hr** -- SWED102 class

-   **1 hr** -- SWED102 HW, weekly quiz, nok.se HW

-   **2.5hr** -- QSCI381 bonus office hours (will not normally host additional friday office hours)

-   **1 hr** -- deep-dive-expression and timeseries-molecular work. Backups to Gannet, re-familiarizing myself with status of both, etc.

-   **1 hr** -- writing/formatting EPIMAR 2025 abstract, looking into submission options. Currently seems like you have to pay for a conference registration before you can submit an abstract, but I wouldn't attend if abstract not accepted... Emailed Technical Secretariat (Steven cc'd). Hopefully there's an option to submit without paying or to receive a registration refund if abstract not accepted.

-   **0.5 hr** -- updating lab notebook, weekly summary

Daily total: **8.5 hrs**

Weekly Overview:

|                 | Monday | Tuesday | Wednesday | Thursday | Friday | TOTALS                   |
|-----------------|--------|---------|-----------|----------|--------|--------------------------|
| **Classes**     | 1      | 2       | 4         | 6        | 2      | **15**                   |
| **TAing**       | 8.5    | 7       | 3.5       | 1        | 2.5    | **22.5**                 |
| **Thesis work** | 0      | 0       | 1         | 3        | 4      | **8**                    |
| **TOTALS**      | 9.5    | 9       | 8.5       | 10       | 8.5    | [***45.5***]{.underline} |

As a reminder, one of my monthly goals is to work a ***maximum*** **of 50hr/wk**, with a rough time allocation of: **20hr/wk** classes (SWED 101, FISH 513); **15hr/wk** TAing (QSCI 381); **15hr/wk** thesis work.\
\
So far I'm happy with my progress! I worked a logged-total of **45.5 hrs** this week, spending **15hrs** on classes, **22.5hrs** on TAing, and **8hrs** on thesis stuff. The breakdown could definitely be adjusted. I expect to spend significantly less time on TAing after this first week, as students require less assistance for basic R tasks, and as the course site requires less setup/maintainance. I should spend more time on classes, particularly FISH315 research, and thesis work.

## 16 January 2025

#### Thursday

-   **1 hr** -- SWED102 class

-   **1 hr** -- QSCI381 weekly meeting

-   **1 hr** -- Lab meeting

-   **2 hr** -- FISH513 class

-   **3 hr** -- FISH513 research

-   **2 hr** -- SAFS seminar and TGIT

Daily total: **10 hrs**

## 15 January 2025

#### Wednesday

-   **1 hr** -- SWED102 class

-   **0.5 hr** -- SED102 HW

-   **1 hr** -- miscellaneous (emails, writing thank you letters for ARCS fellowship donors, etc.)

-   **1 hr** -- QSCI381 miscellaneous work (responding to student emails, reviewing recent discussion posts, fixing Assignment 1 rubric, grading first few Assignment 1 submissions to check that Canvas and Gradescope are linked appropriately, looked thru Assignment 2 and Lab 2 for 381 meeting tomorrow)

-   **2.5 hr** -- QSCI381 Office Hours

-   **2.5 hr** -- FSH513 research (compiling relevant papers, setting up notes structure, start lit review)

Daily total: **8.5 hr**

## 14 January 2025

#### Tuesday

-   **1 hr** -- SWED102 class

-   **1 hr** -- SWED102 HW

-   **2.5 hr** -- QSCI381 Lab

-   **4.5 hr** -- misc work for QSCI381 (figuring out how to link Canvas and Gradescope Assignments and implementing, creating Assignment 1 key, creating .Rmd templates for student use for Assignment 1, Lab 1, Lab 2, and posting all in appropriate Canvas pages, answering student emails)

Daily total: **9 hr**

## 13 January 2025

#### Monday

-   **1 hr** -- SWED102 class

-   **6 hr** -- misc work for QSCI381 (file modification, putting together Lab pages and .Rmd Keys, setting up Gradescope Assignment 1 for my sections, prepping Lab materials for today, creating a helper doc for .Rmd -\> PDF render and Gradescope submission, editing all Assignment pages to include note about Gradescope submission for my sections, create ED Discussion Announcement about Gradescope for my sections, etc.)

-   **2.5 hr** -- QSCI 381 Lab

Daily Total: **9.5 hr**

## 10 January 2025

#### Friday

-   SWED101 class

-   catching up on SWED101 missed work/hw (backlog from when I was at SICB)

-   submit SICB meals reimbursement

-   Prep for first QSCI 381 Lab on Monday

## 09 January 2025

#### Thursday

-   SWED102 class

-   QSCI 381 meeting w Steven and Tsering

-   Sent out TA announcement to my QSCI 381 sections, looked through some of the upcoming course content

-   catching up on emails from break/SICB, paid tuition, lab notebook setup for January posts/goals

-   FISH 513 lit review, class

## 08 January 2025

#### Wednesday

SICB

## 07 January 2025

#### Tuesday

SICB

## 06 January 2025

#### Monday

SICB

## 05 January 2025

#### Sunday

SICB

## 04 January 2025

#### Saturday

SICB

## 03 January 2025

#### Friday

SICB

## 02 January 2025

#### Thursday

## 01 January 2025

#### Wednesday

Out
