---
title: "October 2025, Daily Log"
author: "Kathleen Durkin"
date: "last-modified"
categories: ["daily log"]
format:
  html:
    code-fold: true
execute:
  warning: false
---

## 31 October 2025

#### Friday

## 30 October 2025

#### Thursday

## 29 October 2025

#### Wednesday

## 28 October 2025

#### Tuesday

## 27 October 2025

#### Monday

## 24 October 2025

#### Friday

## 23 October 2025

#### Thursday

-   SWED201 class -- 1hr

-   SEAS Board meeting -- 1 hr

-   Grad-GPx meeting -- 1hr

    -   Updated Plan of Study, sent through the DocuSign signature pipeline, got all 3 committee member signatures 🙏, and submitted via SAFS Grad Program Milestones submission form

-   GSS Planning Committee meeting -- 1 hr

    -   set up GSS Volunteer Google form and wrote up email call for volunteers -- scheduled to send on Monday (10/27)

-   FISH510 -- finished [slidedeck](https://docs.google.com/presentation/d/1zEVQEBN8Tg0aFTi4o4f5ktTVdATh6_yo_mQhQZfnIRM/edit?usp=sharing) for Week 5 presentation (10/28)

## 22 October 2025

#### Wednesday

## 21 October 2025

#### Tuesday

## 20 October 2025

#### Monday

## 17 October 2025

#### Friday

## 16 October 2025

#### Thursday

## 15 October 2025

#### Wednesday

## 14 October 2025

#### Tuesday

## 13 October 2025

#### Monday

## 10 October 2025

#### Friday

## 09 October 2025

#### Thursday

## 08 October 2025

#### Wednesday

## 07 October 2025

#### Tuesday

## 06 October 2025

#### Monday

-   1 hr -- SWED201 novel reading

-   1 hr -- SWED201 class

-   0.5 hr -- admin (emails, setting the weeks task's/deadlines, responding to slacks)

-   1.5 hr -- Lab meeting

-   1 hr -- FINS meeting

-   2 hr -- SEAS meeting

-   0.5 hr -- Set up and integrate notion calendar, task manager

## 03 October 2025

#### Friday

## 02 October 2025

#### Thursday

## 01 October 2025

#### Wednesday

-   SWED201 Class and HW

-   October goals

-   FISH510 reading and discussion posts

-   SWED201 fika
