---
title: "September 2025, Daily Log"
author: "Kathleen Durkin"
date: "last-modified"
categories: ["daily log"]
format:
  html:
    code-fold: true
execute:
  warning: false
---

## 30 September 2025

#### Tuesday

-   SWED201

-   FISH510

-   FISH510 reading

-   finish kraken meta-genomics classifier on all Flongle data

-   

## 29 September 2025

#### Monday

-   SWED201

-   emails/department stuff (reporting recent awards/honors to Sam, tuition checks, registration update, potentially volunteering as GRFP mentor following increased interest)

-   updating `timeseries-molecular` sRNA count matrices with standardized naming format, and associated debugging issues with running an R script from command line in Raven

-   added trimmed sRNA read links + details to `timeseries-molecular` wiki

-   Started Kraken metagenomics summaries of Group1 Library 2 Flongle and Group 1 Library 3 Flongle (will likely need to run overnight)

## 26 September 2025

#### Friday

-   SWED201

-   finished all SIFP notebook digital transcriptions

-   finished SIFP file transfers, checksum generation, and repo organization

-   linked all SIFP tapestation summaries

## 25 September 2025

#### Thursday

-   SWED201 class

-   bought SWED201 textbooks, school materials

-   catching up on last \~2wks of emails (SI and UW)

-   quarter planning:

    -   goals

    -   compiling list of professional development options to keep my eye on coming quarter (SEAS, Seattle Aquarium or Burke Museum volunteering, future teaching options, etc.)

    -   creating spreadsheets of conferences and fellowships/grants to keep an eye on in the coming quarters

-   
