{
  "hash": "5f7bea82951410d2c6837db52d8cdc52",
  "result": {
    "markdown": "---\ntitle: \"February 2025, Daily Log\"\nauthor: \"Kathleen Durkin\"\ndate: \"last-modified\"\ncategories: [\"monthly goals\"]\nformat:\n  html:\n    code-fold: true\nexecute:\n  warning: false\n---\n\n\n## 28 February 2025\n\n#### Friday\n\n-   2 hr -- E5 work, siRNA BLASTs, looking into existing TE annotation\n\n-   1.5 hr -- E5 molecular biweekly meeting -- meeting notes [here](https://docs.google.com/document/d/1Fdd6xC9tJmAf9Iydcf3er-YwabKmwK3jGVw4ppfxfhM/edit?tab=t.0)\n\n-   1.5 hr -- SWED102 class\n\n-   1 hr -- updating lab notebook for the week (e.g. summarizing weekly hours)\n\n[**Weekly summary:**]{.underline}\n\n|                 | Monday | Tuesday | Wednesday | Thursday | Friday | TOTALS |\n|-----------------|--------|---------|-----------|----------|--------|--------|\n| **Classes**     | 4      | 1       | 1         | 1.5      | 1.5    | 9      |\n| **TAing**       | 4      | 6       | 7         | 1        | 0      | 18     |\n| **Thesis work** | 0      | 2       | 4         | 7        | 3.5    | 16\\.   |\n| **Misc.**       | 1      | 0       | 0         | 3.5      | 1      | 5.5    |\n| **TOTALS**      | 9      | 9       | 12        | 13       |        |        |\n\n##### \n\n[**2 month summary**]{.underline}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(googlesheets4)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggplot2)\nhours <- read_sheet(\"https://docs.google.com/spreadsheets/d/1iGCiQlMPibYPxe2w_sVP0_9L6kkd0rxkxO5Kq71IR6o/edit?gid=0#gid=0\")\nhours <- hours[!is.na(hours$Totals),]\nhours$Weekday <- factor(hours$Weekday, levels = c(\"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\", \"Friday\"))\n\navg_daily <- mean(hours$Totals)\n\navg_weekly <- hours %>%\n  group_by(Week) %>%\n  summarise(weekly_total = sum(Totals)) %>%\n  summarise(avg_weekly_total = mean(weekly_total)) %>%\n  pull(avg_weekly_total)\n\npaste0(\"My daily average is \", round(avg_daily,1), \" hours, with a weekly average of \", round(avg_weekly,1), \" hours.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"My daily average is 9.2 hours, with a weekly average of 46.2 hours.\"\n```\n:::\n\n```{.r .cell-code}\n# Plot weekly hours over time\nweekly_totals <- hours %>%\n  group_by(Week) %>%\n  summarise(Total_Hours = sum(Totals))\n\nggplot(weekly_totals, aes(x = Week, y = Total_Hours, group = 1)) +\n  geom_line() +\n  geom_point() +\n  theme_minimal() +\n  labs(title = \"Total Hours per Week Over Time\", x = \"Week\", y = \"Total Hours\") +\n  ylim(0,55) +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](February_2025_posts_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Plot hours by weekday for each week\nggplot(hours, aes(x = Weekday, y = Totals, group = Week, color = Week)) +\n  geom_line() +\n  geom_point() +\n  theme_minimal() +\n  labs(title = \"Daily Hours per Week\", x = \"Weekday\", y = \"Total Hours\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](February_2025_posts_files/figure-html/unnamed-chunk-1-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# Stacked bars of average hours each weekday by category\nhours_long <- hours %>%\n  select(Weekday, Classes, TAing, `Thesis work`, Misc.) %>%\n  pivot_longer(cols = -Weekday, names_to = \"Category\", values_to = \"Hours\") %>%\n  group_by(Weekday, Category) %>%\n  summarise(Avg_Hours = mean(Hours)) %>%\n  ungroup()\n\nggplot(hours_long, aes(x = Weekday, y = Avg_Hours, fill = Category)) +\n  geom_bar(stat = \"identity\") +\n  theme_minimal() +\n  labs(title = \"Average Hours per Weekday by Category\", x = \"Weekday\", y = \"Average Hours\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](February_2025_posts_files/figure-html/unnamed-chunk-1-3.png){width=672}\n:::\n:::\n\n\nThis is pretty interesting! My weekly hours have stayed pretty consistent over the last two months and, while daily hours vary by day and week, the average breakdown of my hours by day and category makes a lot of sense! My TAing work is heavily front-loaded at the beginning of the week, since I teach labs and host office hours Mon/Tues/Wed and have to finish grading by Wed. Classes remain pretty consistent throughout, with a peak on Thursday when FSH513 meets. My research hours increase over the week as TAing commitments drop off, peaking on Fridays when my day is almost completely clear of other commitments.\n\n## 27 February 2025\n\n#### Thursday\n\n-   **1.5 hr** -- SWED102 class\n\n-   **1 hr** -- QSCI381 weekly meeting\n\n-   **1.5 hr** -- Lab meeting, cleaning/organizing in lab\n\n-   **7 hrs** -- E5 work. Readings on siRNA features and softwares, figuring out how to handle ShortStack's output of lcusters but *not* siRNA sequences\n\n-   **2 hr** -- seminar + tgit\n\nDaily total: **13 hr**\n\n## 26 February 2025\n\n#### Wednesday\n\n-   **5 hr** -- QSCI381 grading\n\n-   **1 hr** -- SWED102 class\n\n-   **2 hr** -- QSCI381 office hours\n\n-   **4 hr** -- E5 stuff. Wrapping up deep-dive-expression and timeseries-molecular reruns of miRanda and PCC with expanded inputs and additional post-miranda complementarity filters, plotting in cytoscape, etc.\n\nDaily total: **12 hrs**\n\n## 25 February 2025\n\n#### Tuesday\n\n-   **4 hr** -- QSCI381 Grading\n\n-   **1 hr** -- SWED102 class\n\n-   **2 hr** -- QSCI381 Lab\n\n-   **1 hr**-- E5 plots, summary\n\n-   **1 hr** -- weekly meeting w Steven\n\nDaily total: **9 hrs**\n\n## 24 February 2025\n\n#### Monday\n\n-   **3 hr** -- SWED102 HW and test prep\n\n-   **1 hr** -- SWED102 class and exam\n\n-   **1 hr** -- misc start of the week emails, canvas inbox, slack, and ed discussion checks\n\n-   **1 hr** -- QSCI381 Lab Prep\n\n-   **2 hr** -- QSCI381 Lab\n\n-   **1 hr** -- QSCI381 grading\n\nDaily total: **9 hrs**\n\n## 21 February 2025\n\n#### Friday\n\n-   **1 hr** -- SWED102 class\n\n-   **9 hr** -- E5 coding\n\nDaily total: **10 hr**\n\nWeekly summary:\n\n|                 | Monday\\* | Tuesday  | Wednesday | Thursday | Friday | TOTALS                 |\n|-----------|-----------|-----------|-----------|-----------|-----------|-----------|\n| **Classes**     | 0        | 1        | 5         | 5.5      | 1      | **12.5**               |\n| **TAing**       | 2        | 10.5     | 2         | 0.5      | 0      | **15**                 |\n| **Thesis work** | 0        | 1        | 4.5       | 2.5      | 9      | **17**                 |\n| **Misc.**       | 0        | 0        | 1         | 0        | 0      | **1**                  |\n| **TOTALS**      | **2**    | **12.5** | **12.5**  | **8.5**  | **10** | [**45.5**]{.underline} |\n\n\\* Federal holiday (Presidents' Day)\n\nThis was a good week! Despite the federal holiday I spent less time on classes than expected, hit my desired TAing hours exactly, and was able to spend a little extra time on research. Ideally I should have reduced my overall hours a bit more, since I would proportionally want 40 hrs in a 4-day work week.\n\n## 20 February 2025\n\n#### Thursday\n\n-   **1.5 hr** -- SWED102\n\n-   **1.5 hr** -- troubleshooting launching an Rstudio server through Klone -- got it to work! And was able to run correlation analyses, whcih is the whole reason I needed to use Klone. Yay!\n\n-   **1 hr** -- weekly lab meeting. discussed Zach's lncRNA paper and Klone\n\n-   **2 hr** -- FSH513 lit review on coral historical baselines (\"prehuman\" and pre-1980, when first mass bleaching event was recorded). Also, some reading on the concept of \"shifting baselines,\" which will likely be relevant to final FISH513 manuscript\n\n-   **0.5 hr** -- QSCI381 weekly meeting\n\n-   **2 hr** -- FSH513 class\n\nDaily total: **8.5 hr**\n\n## 19 February 2025\n\n#### Wednesday\n\n-   **1.5 hr** -- SWED102 HW and weekly Quiz\n\n-   **1.5 hr** -- SWED102 class\n\n-   **1.5 hr** -- FSH513 finished digitizing data from GCRMN 2020 hard coral cover figure, read into R and plotted\n\n-   **2 hrs** -- degree stuff. Looked over my Plan of Study again and realized that the Degree Audit tool is inaccurate -- I actually need \\~12 additional credits of graded coursework, not the \\~5 I thought I had left. I decided on FISH546 (Bioinformatics), CSE416 (Machine Learning), and FISH 544 (Conservation Genetics) to meet the credit requirement and sent my M.S. Plan of Study to committee members for signing.\n\n-   **1 hr** -- Read lncRNA paper for Lab Meeting tomorrow (Deng et al., 2022, doi: 10.1007/s11160-022-09734-7, selected by Zach)\n\n-   **2 hrs** -- QSCI381 Office Hours\n\n-   **0.5 hr** -- FSH513 wrote up methods thus far. Will need to do more lit review before writing discussion, focusing on potential gaps in the GCRMN report (e.g. how much had reefs already declined by 1980, when this dataset starts?)\n\n-   **1 hr** -- E5, read through some of my sources to double check that miRanda isn't making any mammal-specific sequence feature assumptions (other than the seed region) -- don't think it is. Read through current state of deep dive expression manuscript + comments/to-do.\n\n-   **1.5 hr** -- trying to launch an RStudio instance through Klone again, still getting same issue as in January. Details in the [github issue](https://github.com/RobertsLab/resources/issues/2066) and my [notebook post](../../projects/misc/2025_02_19_klone_rstudio.qmd)\n\nDaily total: **12.5 hrs**\n\n## 18 February 2025\n\n#### Tuesday\n\n-   **1 hr** -- SWED102 class\n\n-   **2.5 hr** -- QSCI381 lab\n\n-   **1 hr** -- weekly lab meeting w Steven\n\n-   **0.5 hr** -- QSCI381 Ed discussion/Canvas Inbox\n\n-   **7.5 hr** -- QSCI381 Assignment 5 grading\n\nDaily total: **12.5 hrs**\n\n## 17 February 2025\n\n#### Monday\n\nPresident's day\n\nTook most of day off for federal holiday\n\n-   2 hr -- QSCI381 review weekly content and make lab video for today's section\n\nDaily total: **2 hrs**\n\n## 14 February 2025\n\n#### Friday\n\n-   **2 hr** -- E5 work, adding coexpression consideration to comparison of target prediction parameters, meeting prep\n\n-   **1.5 hr** -- E5 meeting -- meeting notes [here](https://docs.google.com/document/d/1Fdd6xC9tJmAf9Iydcf3er-YwabKmwK3jGVw4ppfxfhM/edit?tab=t.0#heading=h.upfrtc9mnidd)\n\n-   **1.5 hr** -- SWED102 class\n\n-   **2 hr** -- QSCI381 weekly office hours\n\n-   **2 hr** -- FSH513 data digitization\n\n-   **0.5 hr** -- QSCI381 answering canvas inbox and ed discussion messages\n\n-   **1 hr** -- misc (emails, lab notebook updates, etc.)\n\nDaily total: **10.5 hr**\n\nWeekly summary:\n\n|                 | Monday | Tuesday | Wednesday | Thursday | Friday   | TOTALS                 |\n|-----------|-----------|-----------|-----------|-----------|-----------|-----------|\n| **Classes**     | 1      | 1       | 1         | 4.5      | 3.5      | **11**                 |\n| **TAing**       | 8      | 4.5     | 4         | 3        | 2.5      | **22**                 |\n| **Thesis work** | 0      | 2.5     | 0         | 2.5      | 3.5      | **8.5**                |\n| **Misc.**       | 0      | 0       | 0         | 0        | 1        | **1**                  |\n| **TOTALS**      | **9**  | **8**   | **5**     | **10**   | **10.5** | [**42.5**]{.underline} |\n\nSimilar to last week, which I'm actually happy with since I was sick for one of the days this week! My TA hours were higher though, which is not the direction I want them to be moving. Some of this time was setup for the next few weeks, so hopefully that helps.\n\n## 13 February 2025\n\n#### Thursday\n\n-   **1 hr** -- E5 ran [comparison of miRanda target prediction](../../projects/E5_coral/2025_02_13_deepdive_miRanda_comparisons.qmd) using different inputs and filtering\n\n-   **1.5 hr** -- SWED102 class\n\n-   **1 hr** -- FSH513 data consolidation and digitization\n\n-   **0.5 hr** -- QSCI381 weekly meeting\n\n-   **1.5 hr** -- Lab picture and Lab meeting\n\n-   **2 hr** -- FSH513 class\n\n-   **2.5 hr** -- QSCI381 Misc. Canvas inbox messages, Ed discussion messaging w Tsering, creating updated docs for Assignment/Lab 7 and 8 and updating all of the Assignment and Lab Canvas pages. Looked through Assignment 9 stuff and messaged Steven about discrepancies. Added gradescope assignments\n\nDaily total: **10 hrs**\n\n## 12 February 2025\n\n#### Wednesday\n\nGave myself ✨food poisoning✨, so just focused on trying to finish grading today. Moved normal office hours to Friday.\n\n-   **1 hr** -- SWED102 class\n\n-   **4 hr** -- QSCI381 grading\n\nDaily total: **5 hrs**\n\n## 11 February 2025\n\n#### Tuesday\n\n-   **1 hr** -- SWED102 class\n\n-   **2 hr** -- E5 work, doing some reading on expected miRNA behavior (binding and location of targets) in cnidarians\n\n-   **2.5 hr** -- QSCI381 Lab\n\n-   **0.5 hr** -- weekly meeting w/ Steven\n\n-   **2 hr** -- QSCI381 grading\n\nDaily total: **8 hrs**\n\n## 10 February 2025\n\n#### Monday\n\n-   **0.5 hr** -- QSCI381 catch up on Ed discussion and Canvas Inbox stuff from the weekend\n\n-   **1 hr** - SWED102 class\n\n-   **3 hr** -- QSCI381 fix this week's assignment and lab pages (need to ask Tsering if she is still able to help w this), skim this week's course content, skim this week's Assignment 5 and Lab 5 and work through any problems I'm not sure about, additional misc prep for Lab\n\n-   **2.5 hr** -- QSCI381 Lab\n\n-   **2 hr** -- QSCI381 grading\n\ndaily total: **9 hr**\n\n## 07 February 2025\n\n#### Friday\n\n**2 hr** -- E5 work\n\n**1.5 hr** -- SWED102 class\n\n**1 hr** -- catch up on E5 github issues and on [lab RSS feed issue](https://github.com/RobertsLab/resources/issues/2090#issuecomment-2643821466). Think we figured it out, so my daily updates and notebook posts should hopefully show up in the `notebook-entries` slack channel!\n\n**1 hr** -- FSH513 meeting w Ray\n\n**0.5 hr** -- SWED102 quiz and second writing assignment\n\n**0.5 hr** -- QSCI381 Ed discussion responses\n\n**3 hr** -- E5 work. Updated gene expression summaries, lncRNA-miRNA binding (miRanda still running), plus lit review into cnidarian/plant miRNA binding and into siRNA binding (in prep for running siRNA target prediction)\n\nDaily total: **9.5 hr**\n\nWeekly overview:\n\n|                 | Monday | Tuesday  | Wednesday | Thursday | Friday  | TOTALS               |\n|-----------|-----------|-----------|-----------|-----------|-----------|-----------|\n| **Classes**     | 2.5    | 1        | 3         | 4        | 3       | **13.5**             |\n| **TAing**       | 5.5    | 9.5      | 2         | 1        | 0.5     | **18.5**             |\n| **Thesis work** | 0      | 1        | 2         | 0        | 6       | **9**                |\n| **Misc.**       | 0      | 1        | 0         | 3        | 0       | **4**                |\n| **TOTALS**      | **8**  | **12.5** | **7**     | **8**    | **9.5** | [**45**]{.underline} |\n\nThis week I hit the hours/week goal nicely, but my allocation is a bit skewed. I'm spending more time on TAing and less time on thesis work than I'd like. While I'm still within the 20hr/wk slot allowable for my TA position, I'd like to bring the hours down to 15hr/wk to allow more time for my own research.\n\n## 06 February 2025\n\n#### Thursday\n\n-   **1 hr** -- SWED102 class\n\n-   **1 hr** -- FSH513 downloaded SQLite db and query file for HeatCRD database and figuring out how to access stuff in an SQLite DB\n\n-   **1 hr** -- QSCI381 weekly meeting\n\n-   **1 hr** -- Lab meeting\n\n-   **2 hr** -- FSH513 class\n\n-   **0.5 hr** -- emails/github issues checks, Canvas Inbox, Ed Discussion, etc.\n\n-   **1.5 hr** -- Updating personal info, presentations on Lab Website, adding to some of the github issues we created during lab meeting today related to Lab Website [updates](https://github.com/RobertsLab/resources/issues/2080), [additions](https://github.com/RobertsLab/resources/issues/2089)\n\nDaily total: **8 hr**\n\n## 05 February 2025\n\n#### Wednesday\n\n-   **1 hr** -- SWED 102\n\n-   **2 hr** -- QSCI381 office hours\n\n-   **2 hr** -- FSH513 summarizing CRGMN 2020 primary findings & adding to slides, looking inot data/methods of HeatCRD data\n\n-   **1 hr** -- misc. catch up on emails, lab/E5 github issues, lab/E5 slack messages\n\n-   **0.5 hr** -- heard from Andrea that I'm likely to receive SIFP (though not yet official)! Read through all of my submitted application materials to re-familiarze myself with the work I proposed.\n\n-   **0.5 hr** -- new goals for February\n\nDaily total: **7 hrs**\n\n## 04 February 2025\n\n#### Tuesday\n\n-   **1 hr** -- SWED102 class\n\n-   **2.5 hr** -- QSCI381 lab\n\n-   **1 hr** -- weekly meeting w Steven (plus prep for meeting). Discussed plan/work timeline for EPIMAR\n\n-   **1 hr** -- miscellaneous (emails, skimming some papers sent in lab Slack, Ed discussion, Canvas Inbox, etc.)\n\n-   **7 hr** -- QSCI381 grading\n\nDaily total: **12.5 hrs**\n\n## 03 February 2025\n\n#### Monday\n\n-   **1.5 hr** -- SWED102 HW\n\n-   **1 hr** -- SWED102 class\n\n-   **3 hr** -- QSCI381 Lab prep (read through weekly material, skim Lab and Assignment, prep lab material) and misc. (Canvas inbox, Ed Discussion, etc.)\n\n-   **2.5 hr** -- QSCI381 Lab\n\nDaily total: **8 hrs**\n",
    "supporting": [
      "February_2025_posts_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}