---
title: "ICRS admin"
author: "Kathleen Durkin"
date: "2026-03-25"
categories: ["E5-coral"]
format:
  html:
    toc: true
execute: 
  eval: FALSE
engine: knitr
bibliography: ../../../references.bib
---

TLDR: Applying for travle funding for ICRS this summer in Auckland, New Zealand. More details on trip plannign [here](https://docs.google.com/document/d/1ddZ2nDEAb9HWEInXYi2vnGIoFtsWaTKq6x2OjHzwDf8/edit?usp=sharing).

I had an abstract accepted for presentation at the International Coral Reef Symposium (ICRS) this summer in Auckland, New Zealand! This is super exciting, because I've been wanting to attend ICRS since their last meeting four years ago, in 2022. It does, however, mean I'll need to source a *lot* of travel funding, since the E5 NSF grant concluded at the end of last summer. 

Today I officially registered for ICRS (\$380) and confirmed that I will be presenting. I also became an ICRS student member first (\$40), because it ended up net lowering the registration cost.

I then looked into what travel awards I can apply for. The options I found are:

- [FINS award](https://fish.uw.edu/students/student-organizations/fins-fisheries-interdisciplinary-network-of-students/student-awards/) (no set maximum, but could probably receive a few hundred dollars max)
- [GPSS travel award](https://www.gpss.uw.edu/funding/travel-grants/) (max $500 for international)
- [Graduate School Conference Presentation Award](https://grad.uw.edu/funding_posts/graduate-student-conference-presentation-awards/) (max $500 for international)
- [College of the Environment travel award](https://environment.uw.edu/students/current-students/scholarships-funding/travel-fund/) (max $1500 for international)

FINS award: I'm definitely eligible, as I'm an active FINS member (GSRS lead, SEAS board member). The application for Summer awards won't open for a few months though, so I'm just gonna hope I can get the registration cost covered by them.

GPSS: While I *would* have been eligible for this, they actually closed applications for the 2025-2026 cycle just a few weeks ago, due to a lack of funds. I can only guess this is a result of trump-era budget cuts.

Graduate School award: Apparently I'm *not* eligible for this right now. I last received this award in fall 2024 to attend SICB in January 2025. The website for this award states students are eligible if they haven't received it within the last **year**. However, when contacting Sam Scherer for assistance with applying, she actually told me the site is wrong and eligibility is **2 years** since receiving the award. It's been ~1.5 years since I got it, so I don't actually qualify. *Sigh*

CoE award: I beleive I *am* eligible for this one! That's awesome, since it's by far the largest award, but it's also the most in-depth application. I put together a detailed [budget proposal](https://docs.google.com/spreadsheets/d/1tskDFp_L-Nys21N3oR54gmlol8wDmc1u/edit?usp=drive_link&ouid=100772895184038139140&rtpof=true&sd=true) for the conference, filled out the student application portion, put together a draft submission for Steven's recommendation form, sent that to him, and confirmed he submitted his recommendation!