{
  "hash": "a0db3aeb3329fd28648b5a94a5abe476",
  "result": {
    "markdown": "---\ntitle: \"Timeseries molecular: Format input files for Cytoscape -- pt.2\"\nauthor: \"Kathleen Durkin\"\ndate: \"2025-05-07\"\ncategories: [\"E5-coral\"]\nformat:\n  html:\n    toc: true\nexecute: \n  eval: TRUE\nengine: knitr\nbibliography: ../../../references.bib\n---\n\n\nContinuation of [Timeseries molecular: Format input files for Cytoscape](./2025_04_28_timeseries_cytoscape_files.qmd). I want to add DEG information to nodes.\n\nI'm choosing to add annotations for features that are differentially expressed in a comparison of Timepoint 2 to Timepoint 4, as these are seasonally very divergent, and yield the highest number of DEGs.\n\nI only need to add DEG annotations to the \"Nodes\" files, which contain metadata for all the features (miRNA, lncRNA, genes) included in my networks.\n\nInput files:\n\n- Cytoscape \"Nodes\" file, generated in [Timeseries molecular: Format input files for Cytoscape](./2025_04_28_timeseries_cytoscape_files.qmd): `./output/nodes_timeseries_miRNA_lncRNA_genes.csv`\n\n- genes DEGs for Timepoint 2 v Timepoint 4: https://github.com/urol-e5/timeseries_molecular/blob/main/D-Apul/output/03.00-D-Apul-RNAseq-gene-expression-DESeq2/tp2.v.tp4.results.table.csv\n\n- miRNA DEGs for Timepoint 2 v Timepoint 4: https://github.com/urol-e5/timeseries_molecular/blob/main/D-Apul/output/03.10-D-Apul-sRNAseq-expression-DESeq2/miRNA_tp2.v.tp4.results.table.csv\n\n- lncRNA DEGs for Timepoint 2 v Timepoint 4: https://github.com/urol-e5/timeseries_molecular/blob/main/D-Apul/output/03.20-D-Apul-lncRNA-expression-DESeq2/lncRNA_tp2.v.tp4.results.table.csv\n\n# Load packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'dplyr' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(tidyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tidyr' was built under R version 4.2.3\n```\n:::\n:::\n\n\n\n# Read in files\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes <- read.csv(\"./output/2025_04_28_timeseries_cytoscape_files/nodes_timeseries_miRNA_lncRNA_genes.csv\") %>% select(-X)\n\n# Using raw htmls\ngenes_2v4 <- read.csv(\"https://github.com/urol-e5/timeseries_molecular/raw/refs/heads/main/D-Apul/output/03.00-D-Apul-RNAseq-gene-expression-DESeq2/tp2.v.tp4.results.table.csv\")\n\nmiRNA_2v4 <- read.csv(\"https://github.com/urol-e5/timeseries_molecular/raw/refs/heads/main/D-Apul/output/03.10-D-Apul-sRNAseq-expression-DESeq2/miRNA_tp2.v.tp4.results.table.csv\")\n\nlncRNA_2v4 <- read.csv(\"https://github.com/urol-e5/timeseries_molecular/raw/refs/heads/main/D-Apul/output/03.20-D-Apul-lncRNA-expression-DESeq2/lncRNA_tp2.v.tp4.results.table.csv\")\n```\n:::\n\n\nMerge DEG files (type will still be denoted by feature name -- \"FUNXXXX\" for genes, \"ClusterXXX\" for miRNA, \"lncRNAXXX\" for lncRNA)\n\n::: {.cell}\n\n```{.r .cell-code}\nmerged_2v4 <- rbind(genes_2v4, miRNA_2v4, lncRNA_2v4)\n```\n:::\n\n\nReduce to significantly differentially expressed features (padj < 0.05)\n\n::: {.cell}\n\n```{.r .cell-code}\nmerged_2v4_sig <- merged_2v4 %>% filter(padj < 0.05)\n\nnrow(merged_2v4_sig[grepl(\"FUN\", merged_2v4_sig$X),])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 684\n```\n:::\n\n```{.r .cell-code}\nnrow(merged_2v4_sig[grepl(\"Cluster\", merged_2v4_sig$X),])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n\n```{.r .cell-code}\nnrow(merged_2v4_sig[grepl(\"lncRNA\", merged_2v4_sig$X),])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 347\n```\n:::\n:::\n\nWhen comparing expression in Timepoint 2 to Timepoint 4, there are 684 differentially expressed genes, 1 differentially expressed miRNA, and 347 differentially expressed lncRNA\n\nAdd to Nodes file\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes$DEG_tp2_tp4 <- ifelse(nodes$id %in% merged_2v4_sig$X, \"yes\", \"no\")\n\nnrow(nodes[nodes$DEG_tp2_tp4 == \"yes\" & grepl(\"FUN\", nodes$id),])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 360\n```\n:::\n\n```{.r .cell-code}\nnrow(nodes[nodes$DEG_tp2_tp4 == \"yes\" & grepl(\"Cluster\", nodes$id),])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n\n```{.r .cell-code}\nnrow(nodes[nodes$DEG_tp2_tp4 == \"yes\" & grepl(\"lncRNA\", nodes$id),])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 28\n```\n:::\n:::\n\nOF the nodes in our (unfiltered) interaction network, 360 genes, 1 miRNA, and 28 lncRNA are differentially expressed between TP2 and TP4. The genes number is surprising to me, since that means more than half of all the differentially expressed genes are present in our interaction network!\n\nSave\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite.csv(nodes, \"./output/2025_05_07_timeseries_cytoscape_files_2/nodes_timeseries_miRNA_lncRNA_genes_DEG2v4.csv\", quote=FALSE)\n```\n:::\n\n\n\n\n\n\nLoad edges\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_PCC_0_7<- read.csv(\"./output/2025_04_28_timeseries_cytoscape_files/edges_PCC_0.7_timeseries_miRNA_lncRNA_genes.csv\") %>% select(-X)\n```\n:::\n\n\n\nLoad functional annotations\n\n::: {.cell}\n\n```{.r .cell-code}\nFA <- read.table(\"https://github.com/urol-e5/deep-dive-expression/raw/refs/heads/main/D-Apul/output/02-Apul-reference-annotation/Apulcra-genome-mRNA-IDmapping-2024_12_12.tab\", header=TRUE)\nFUNids <- read.table(\"https://github.com/urol-e5/deep-dive-expression/raw/refs/heads/main/D-Apul/output/15-Apul-annotate-UTRs/Apul-mRNA-FUNids.txt\", header=FALSE) %>% select(V1, V4)\n\nFUNids$V4 <- gsub(\"Parent=\", \"\", FUNids$V4)\nFA <- left_join(FA, FUNids, by=c(\"V1\" = \"V1\"))\nFA <- FA %>% select(V4, Gene.Ontology.IDs, Gene.Ontology..biological.process.) %>% distinct()\ncolnames(FA) <- c(\"gene_id\", \"GO_id\", \"GO_BP\")\n```\n:::\n\n\nJoin\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_PCC_0_7_GO <- left_join(edges_PCC_0_7, FA, by = c(\"target\" = \"gene_id\"))\n```\n:::\n\n\nFormat\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_PCC_0.7_GOid <- edges_PCC_0_7_GO %>% \n  select(-GO_BP) %>%\n  filter(!is.na(GO_id)) %>%\n  separate_rows(GO_id, sep=\"; \")\n\nedges_PCC_0.7_GOBP <- edges_PCC_0_7_GO %>% \n  select(-GO_id) %>%\n  filter(!is.na(GO_BP)) %>%\n  separate_rows(GO_BP, sep=\"; \")\n```\n:::\n\n\nAnnotate nodes\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes_GO <- left_join(nodes, FA, by = c(\"id\" = \"gene_id\"))\n\nnodes_GOid <- nodes_GO %>%\n  select(-GO_BP) %>%\n  filter(!is.na(GO_id)) %>%\n  separate_rows(GO_id, sep=\"; \")\n\nnodes_GOBP <- nodes_GO %>%\n  select(-GO_id) %>%\n  filter(!is.na(GO_BP)) %>%\n  separate_rows(GO_BP, sep=\"; \")\n```\n:::\n\n\nSave\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite.csv(edges_PCC_0.7_GOid, \"./output/2025_05_07_timeseries_cytoscape_files_2/edges_PCC_0.7_timeseries_miRNA_lncRNA_genes_DEG2v4_GOid.csv\", quote=FALSE)\nwrite.csv(edges_PCC_0.7_GOBP, \"./output/2025_05_07_timeseries_cytoscape_files_2/edges_PCC_0.7_timeseries_miRNA_lncRNA_genes_DEG2v4_GOBP.csv\", quote=FALSE)\n\nwrite.csv(nodes_GOid, \"./output/2025_05_07_timeseries_cytoscape_files_2/nodes_timeseries_miRNA_lncRNA_genes_DEG2v4_GOid.csv\", quote=FALSE)\nwrite.csv(nodes_GOBP, \"./output/2025_05_07_timeseries_cytoscape_files_2/nodes_timeseries_miRNA_lncRNA_genes_DEG2v4_GOBP.csv\", quote=FALSE)\n```\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}