{
  "hash": "a1866cfb09bd02266dd221174ab976cd",
  "result": {
    "markdown": "---\ntitle: \"Qubit DNA Quantification\"\nauthor: \"Kathleen Durkin\"\ndate: \"2025-07-14\"\ncategories: [\"SIFP_2025\"]\nformat:\n  html\nbibliography: ../../../references.bib\n---\n\n\nUsed Qubit flourometer to quantify DNA concentration of extracted E. tourneforti samples.\n\n### LAB 1X dsDNA Qubit Protocol\n\n![](images/LAB_Qubit_Protocol_1.png)\n\n![](images/LAB_Qubit_Protocol_2.png)\n\n![](images/LAB_Qubit_Protocol_3.png)\n\nNote: Used 2uL of sample DNA for each Qubit rxn\n\n### Results\n\nHad to assign new labels to the samples for Qubiting, since the USNM Catalog numbers are too large to fit on the Qubit tube lids\n\n[**Standards (first run):\\\n**]{.underline}Standard #1: 37.57\\\nStandard #2: 14064.10\n\n[**Standards (second run, with dilutions):**]{.underline}\\\nStandard #1: 36.17\\\nStandard #2: 14557.00\n\n|                    |                    |                 |                        |\n|-----------------|-----------------|----------------:|---------------------|\n| **Year.Collected** | **Catalog.Number** | **Qubit.label** | **Concentration.ngul** |\n| 1886               | USNM 14366         |             A01 | \\* 0.173               |\n| 1886               | USNM 14399         |             A02 | 33.9                   |\n| 1898               | USNM 19054         |             A03 | \\* 6.03                |\n| 1898               | USNM 42137         |             A04 | 15                     |\n| 1960               | USNM 51730         |             A05 | 20.9                   |\n| 1960               | USNM 51732         |         **A06** | **89.4**               |\n| 1960               | USNM 51728         |             A07 | 35.2                   |\n| 1960               | USNM 51892         |         **A08** | **86.3**               |\n| 1912               | USNM 52295         |             A09 | \\* 7.08                |\n| 2000               | USNM 100609        |         **A10** | **161**                |\n| 2000               | USNM 100610        |         **A11** | **84.7**               |\n| 2000               | USNM 1007393       |         **A12** | **116**                |\n| 2002               | USNM 1018355       |             A13 | 44.3                   |\n| 1912               | USNM 1180630       |             A14 | \\* 1.41                |\n| 2019               | USNM 1606824       |         **A15** | **167**                |\n| 2019               | USNM 1606826       |         **A16** | **189**                |\n| 2019               | USNM 1740336       |         **A17** | **163**                |\n| 2019               | USNM 1740363       |         **A18** | **152**                |\n| 2019               | USNM 1740390       |         **A19** | **126**                |\n| 2019               | USNM 1740407       |         **A20** | **133**                |\n| 1880               | USNM 50368         |             B01 | 26.5                   |\n| 1912               | USNM 50603         |             B02 | \\* 2.28                |\n| 1960               | USNM 51727         |             B03 | 27                     |\n| 1960               | USNM 51729         |             B04 | 48.9                   |\n| 1960               | USNM 51857         |             B05 | 43.7                   |\n| 1960               | USNM 51858         |             B06 | 28.5                   |\n| 1960               | USNM 51859         |             B07 | 43.9                   |\n| 1960               | USNM 51860         |             B08 | 56                     |\n| 1960               | USNM 51861         |             B09 | 52                     |\n\n::: callout-note\nBolded values indicated the sample was originally too high concentration to be accurately quantified by the Qubit assay. For these samples I made a 10X dilution (1uL DNA sample, 9uL Zymo DNA Elution Buffer), then re-Qubited the dilutions. Values shown above are the calculated \"true\" concentrations (10X dilution concentration, multiplied by 10).\n:::\n\nGenerally, almost all extractions have a good amount of DNA! The recommended minimum quantity of DNA for Nanopore Native Library Prep is 400ng. Since I'll have \\~40uL DNA left for each sample after eluting in 50uL and using a small portion for QC steps, I'm **aiming for a minimum DNA concentration of 10 ng/uL**.\n\nOnly 5 samples failed to meet this threshold (starred above). All 5 are from my set of old specimens (\\>100 yo). I only have 8 total specimens from this collection period, and I want an n=5 for sequencing. **I'll need to do additional extractions for the 5 specimens with low concentrations (USNM 14366, USNM, 19054, USNM 52295, USNM 1180630, USNM 50603).** I may also want to do an additional extraction for USNM 42137 (15.0 ng/uL), since its not much higher than my desired minimum concentration.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(googlesheets4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'googlesheets4' was built under R version 4.2.3\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ggplot2' was built under R version 4.2.3\n```\n:::\n\n```{.r .cell-code}\nconc <- read_sheet(\"https://docs.google.com/spreadsheets/d/1zDMy7AOCM8Ug85q4vr9CoMDxfF-zDJk1DnaxakSt1Hg/edit?usp=sharing\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n! Using an auto-discovered, cached token.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n  To suppress this message, modify your code or options to clearly consent to\n  the use of a cached token.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n  See gargle's \"Non-interactive auth\" vignette for more details:\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n  <https://gargle.r-lib.org/articles/non-interactive-auth.html>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nℹ The googlesheets4 package is using a cached token for 'kdurkin1@uw.edu'.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n✔ Reading from \"E_tourneforti\".\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n✔ Range 'E_tourneforti_samples'.\n```\n:::\n\n```{.r .cell-code}\nggplot(conc, aes(x=Year.Collected, y=Concentration.ngul, color=Country)) +\n  geom_point(size=2) + \n  geom_line(aes(y=10), color='black') +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 3 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](2025_07_14_qubit_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n(anything collected in the US was collected off the coast of Florida)\n\nHorizontal line indicates the 10 ng/uL cutoff, or the minimum concentration that will yield at least the library prep requirement of 400ng DNA from a volume of 40uL.\n",
    "supporting": [
      "2025_07_14_qubit_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}